### ISSUE TITLE
Rumble doesn't work after version "March 4, 2020 - New Input Plugin"

### ISSUE THREAD

**Issue by FaunoLabirintite** [loganmc10/m64p#10]
It works fine with an Xbox 360 controller on Feb 25, 2020 (The Red Dot edition), but it doesn't work with the newer versions (neither March 4 nor March 15 versions). Probably an issue with the new input plugin used. 

I've also tried switching the input plugin to the one bundled with the Red Dot edition, but then the controllers don't work.

**Comment by loganmc10** [comment]
Are you using Windows or Linux?

Admittedly I wrote the rumble code "blind" as I don't have a controller that supports rumble

**Comment by loganmc10** [comment]
Also, do you have "rumble" selected for your pak in the controller config?

**Comment by FaunoLabirintite** [comment]
> 
> 
> Are you using Windows or Linux?
> 
> Admittedly I wrote the rumble code "blind" as I don't have a controller that supports rumble

I'm on Windows 10.


> 
> 
> Also, do you have "rumble" selected for your pak in the controller config?

Yes, I've even tried deleting the controller profiles, changing the controller profiles, etc.

**Comment by FaunoLabirintite** [comment]
I've also tried changing the rumble setting via the config file in the ROAMING folder.

**Comment by loganmc10** [comment]
Can you try this build:

https://m64p.s3.amazonaws.com/m64p/m64p-win64-06609e7.zip

I realized I missed a bit of code to initialize the haptic feedback code. Hopefully this fixes it

**Comment by Piloto40** [comment]
works with this new build, thanks

**Comment by FaunoLabirintite** [comment]
> 
> 
> Can you try this build:
> 
> https://m64p.s3.amazonaws.com/m64p/m64p-win64-06609e7.zip
> 
> I realized I missed a bit of code to initialize the haptic feedback code. Hopefully this fixes it

I can confirm it is working fine now, thanks a lot!

**Comment by loganmc10** [comment]
Thanks for confirming, fixed version has been released: https://github.com/loganmc10/m64p/releases/tag/Mar192020
