### ISSUE TITLE
Switch from Travis CI to Github Actions

### ISSUE THREAD

**Issue by joeldenning** [loganmc10/m64p#100]
Travis CI is rate limiting open source projects, and also doesn't support osx Big Sur. @loganmc10 would you be open to switching to Github actions, which supports big sur? 

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners

**Comment by loganmc10** [comment]
Are you sure that compiling on Big Sur is the proper solution? When you compile on a newer version of the OS, it will stop working on the older versions (you'll have the opposite problem).

Typically with Linux you'd compile on the oldest version possible (this is why it's compiled on Ubuntu 18.04 even though 20.04 is available)

**Comment by joeldenning** [comment]
I'm having a friend check whether the DMG in [this comment](https://github.com/loganmc10/m64p/issues/99#issuecomment-741387133) works for him on Big Sur. If it does, then I think that the issue is likely which os is used to build it. To get things to build on Big Sur, I had to work around a couple issues with the brew dependencies that don't work on Big Sur, which involved me symlinking the Big Sur version of XCode so that it could be referenced as the Catalina version.

> When you compile on a newer version of the OS, it will stop working on the older versions

True - Apple is currently rolling out Big Sur to everyone, but some may stay on Catalina for a while. If we want to support older versions of osx, we could have two builds - one for big sur and one for catalina.

**Comment by joeldenning** [comment]
it's also possible that the issue is not related to big sur, but rather to any new code in that release. So we'll have to see with my friend and also @jerrypc2036 say about it

**Comment by loganmc10** [comment]
Part 1 of this request is complete, I've moved everything from Travis to GitHub actions. I'll trust your judgement on the Mac build, just submit a PR with whatever changes you want to make to the build process for Mac

**Comment by loganmc10** [comment]
GitHub Actions is a lot faster than Travis... Not only is there not a multiple hour queue, but the jobs all run in parallel, so building for Linux+Windows+Mac only takes 13.5 minutes total, very nice

**Comment by joeldenning** [comment]
Both @jerrypc2036  and my friend confirmed that my local build worked for them on Big Sur, so the difference must be between the environment that was used in Travis versus my computer's environment. I'll investigate this further. @loganmc10 can I download the DMGs for individual builds that were uploaded to s3? What's the url to download them?

**Comment by joeldenning** [comment]
Actually I found the DMGs right there in Github's UI as an artifact! So downloading from s3 won't be necessary. I will try the new DMG created by the Github Actions runner and see if that works on Big Sur. If it doesn't, I'll try creating a new job that builds on Big Sur (the current job is using catalina)

**Comment by loganmc10** [comment]
yeah github puts the artifacts right there which is nice. It'll work for PRs too, so if you open a PR it'll build it and put the artifacts there to download

**Comment by joeldenning** [comment]
The DMG at https://github.com/loganmc10/m64p/actions/runs/411158075 works for me on Big Sur! So apparently it's not required to build it on Big Sur - it must have been something else specific to the travis environment that caused it not to work on Big Sur.

@jerrypc2036 can you confirm the DMG available at https://github.com/loganmc10/m64p/actions/runs/411158075 works for you?

**Comment by loganmc10** [comment]
The Travis build actually ran on 10.14, GitHub Actions is using 10.15, so it's likely that this build will only work on 10.15+, and it could have been that building on 10.14 wasn't compatible with Big Sur
