### ISSUE TITLE
Mayflash adaptor - input not detected 

### ISSUE THREAD

**Issue by Exequiel3k** [loganmc10/m64p#101]
Hi,
I tried using the adaptor and it doesn’t detect button presses, when trying to configure a profile.
I selected the appropriate gamepad device (id displayed: N64 Gamepad) for all four players and none worked when trying to config...

(This also relates to closed issue #12)

**Comment by loganmc10** [comment]
Closing in favour of https://github.com/loganmc10/m64p/issues/142
