### ISSUE TITLE
osx - cannot play two consecutive games

### ISSUE THREAD

**Issue by joeldenning** [loganmc10/m64p#104]
This isn't a blocker for using m64p, but osx crashes sometimes after you close a netplay session.

Here's the stacktrace: https://gist.github.com/joeldenning/92ae465d4c8671aa1c5c689e57241f1e

Seems related to the discord integration?

**Comment by loganmc10** [comment]
The project now only includes ParaLLEl-RDP, which depends on Vulkan. A Mac developer would need to adapt it before it will work again. So for the time being Mac is no longer supported
