### ISSUE TITLE
Controller Profile "Auto" either not working or functionality is unclear

### ISSUE THREAD

**Issue by renandr** [loganmc10/m64p#105]
I have one controller configuration for each game I'm playing currently. One for Perfect Dark, that I called it "Default" and another for F-Zero X and another for Kirby 64.
I am not sure how the "Auto" profile is supposed to work when I switch between the games. Should the profile be picked automatic, based on the game? It seems to be a little unclear from a UX perspective.
When I chose Auto, some strange configuration seems to be used, I don't remember ever setting the B button as the X button in my HORI Switch Battle Pad 😄

**Comment by loganmc10** [comment]
The Auto profile is "try to figure out the button mappings for me". There is not currently a way to specify a profile per game

**Comment by renandr** [comment]
Haha, ok. Yeah I totally projected my own expectation into it 😆 
I wonder how it tries to figure that out...

**Comment by loganmc10** [comment]
It only works if the controller is an Xbox/PlayStation style controller. If it supports Xinput then the emulator knows where the buttons are physically located and it can assign the inputs based on what most people use when playing N64 (using the right analog stick as C buttons for instance)

**Comment by renandr** [comment]
Ah okay, so I see now why the X was assigned as B, makes sense :)
