### ISSUE TITLE
Give indication of savestate being saved

### ISSUE THREAD

**Issue by anonymous7002** [loganmc10/m64p#110]
When you save a savestate, there's no indication of it being saved.

**Comment by joeldenning** [comment]
I agree it might be nice to have a visual indicator for this. One thing to note is that the save state does show up in the logs, though:

![image](https://user-images.githubusercontent.com/5524384/103575953-a75b4b00-4e8f-11eb-97ce-558013ba23ed.png)

You can see the logs by going to File -> View Logs

**Comment by loganmc10** [comment]
Visual indicators are quite hard in mupen64plus. All on-screen rendering is owned by the GFX plugin. I haven't looked in a while but I don't think there is a way for the core to send text to the GFX plugin to render onscreen

**Comment by anonymous7002** [comment]
Why not use the status bar?

**Comment by loganmc10** [comment]
That's a good idea, I'll leave this open, but I don't have time in the near future to work on this

**Comment by anonymous7002** [comment]
Currently, the status bar has almost no use.

**Comment by loganmc10** [comment]
Closing all feature requests, I will accept PRs for these kinds of things but the work isn't directed based on feature requets.
