### ISSUE TITLE
too many initializers

### ISSUE THREAD

**Issue by ZachBacon** [loganmc10/m64p#112]
compiling from git master on linux is showing an error where https://github.com/m64p/mupen64plus-gui/blob/903d611083b6e41c161b72bdf9baf3655b166222/mainwindow.cpp#L26 has too many initializers and errors out in compilation

`mainwindow.cpp:41:85: error: too many initializers for ‘m64p_video_extension_functions’
   41 |                                                  qtVidExtFuncGLGetDefaultFramebuffer};
`

**Comment by loganmc10** [comment]
You are having this problem because you have older mupen64plus headers somewhere on your system. If you've installed mupen64plus via a package manager they are probably somewhere in /usr/include and need to be removed

**Comment by ZachBacon** [comment]
not the case, I'm using 2.5.9 which is the latest current stable.

**Comment by loganmc10** [comment]
You need to uninstall 2.5.9 and any existing mupen64plus install if you'd like to use m64p. Your other option would be to download the binary build that is available on the Releases page of this repository

**Comment by ZachBacon** [comment]
Not going to happen, I'm a package manager, I'm literally attempting to provide a compiled binary build. From a packagers standpoint, it's a total mess what you have. Like I understand why you have it such, but it's a mess nevertheless.

**Comment by loganmc10** [comment]
I appreciate the kind words. m64p is an emulator based on mupen64plus. It's not compatible with the released versions of mupen64plus. It's not just a frontend.

It's built using the build.sh script included in this repo, and like I said, it conflicts with existing installs of mupen64plus. Hopefully that helps you understand the package management aspect better.

**Comment by ZachBacon** [comment]
Aye, I mean personally I like the project, shame I can't use it on a vanilla build of mupen64plus. But I guess this won't land in a repository for my distro any time soon. 

But I do like what I see so far with your project, keep up the work, for now I'll stick to a portable compile for myself then.
