### ISSUE TITLE
Allow pausing when in menu / Autopause game when opening a menu

### ISSUE THREAD

**Issue by anonymous7002** [loganmc10/m64p#114]
When you want to edit controls, you have to pause the game before that. If already in the menu, you have to close the menu, pause the game and reopen the menu.
Ways to fix:
1. Allow pausing when in menu
2. Make the game automatically pause when opening a menu
3. Allow editing controls when the game is not paused

**Comment by anonymous7002** [comment]
Also, the dialog box is misleading. "Stop the game before editing controls".

**Comment by loganmc10** [comment]
Closing all feature requests, I will accept PRs for these kinds of things but the work isn't directed based on feature requets.
