### ISSUE TITLE
Can't launch ROM from command line on macOS

### ISSUE THREAD

**Issue by jcharun** [loganmc10/m64p#116]
Launching a ROM from command line don't seems to work on macOS 10.15.7.

**Comment by loganmc10** [comment]
@joeldenning does this work for you? I don't have a Mac to test

**Comment by joeldenning** [comment]
I'll test this out later.

**Comment by joeldenning** [comment]
I tested this today and it works for me when I build locally, but not with the public release for osx. Not sure what the difference is.

**Comment by loganmc10** [comment]
What doesn't work exactly? It crashes, or it just doesn't do anything?

**Comment by joeldenning** [comment]
It opens the GUI without opening the rom. Essentially the same as if you didn't pass in the command line arg.

Here's what I'm running:

```sh
./mupen64plus-gui /Users/joeldenning/roms/Super\ Smash\ Bros.\ \(U\)\ \[!\].z64
```

There's no stdout output, but it just shows the GUI instead of opening the rom:

![image](https://user-images.githubusercontent.com/5524384/104771208-2aea2700-572f-11eb-97ad-d98cc1c5159a.png)

**Comment by joeldenning** [comment]
One difference I just found is that when I pass in the rom as a command line argument, I can no longer close mupen64plus-gui without doing a Force Quit. So something must be going wrong that causes it to not even respond correctly to SIGINT/SIGTERM.

**Comment by loganmc10** [comment]
I put together a build that might fix it, can you guys test:

https://github.com/loganmc10/m64p/actions/runs/488977102

Mac OS is a little tricky because everything has to run in 1 thread, I think I may have been doing the command line launches wrong in single threaded mode

**Comment by joeldenning** [comment]
Unfortunately that build did not fix the issue with roms. It did, however, fix the problem where the process wouldn't stop without a Force Quit, so it might be a good change in general.

**Comment by loganmc10** [comment]
The project now only includes ParaLLEl-RDP, which depends on Vulkan. A Mac developer would need to adapt it before it will work again. So for the time being Mac is no longer supported
