### ISSUE TITLE
Beetle Adventure Racing freezes when choosing a certain car.

### ISSUE THREAD

**Issue by Tasosgemah** [loganmc10/m64p#119]
When you choose the green car and try to play on the first level, the game freezes on the track preview.

Here is a save file with the cars unlocked:

[Beetle Adventure Racing! (U) (M3) [!].zip](https://github.com/loganmc10/m64p/files/5841091/Beetle.Adventure.Racing.U.M3.zip)

**Comment by loganmc10** [comment]
I don't think I can reproduce this, I was able to get into Coventry Cove with the green car, did I misunderstand your description?
![image](https://user-images.githubusercontent.com/848146/105192330-36559d80-5af5-11eb-9fbc-ea5bb566667f.png)

**Comment by Tasosgemah** [comment]
Hmmm... it seems it does work if you select "full grid".

Ok try this: Select "duel" then the green car. When the track preview appears (where the camera shows you a bit of the track) press A to skip it so you start playing. It should freeze there. 

This happens with the green car AFAIK.

**Comment by loganmc10** [comment]
Yes in this case I could reproduce it, it's an in-game freeze, the music keeps playing. I tried all different combinations of settings and it didn't seem to make any difference.

**Comment by Tasosgemah** [comment]
btw, i remember this issue being pretty old. Like, using PJ64 in 2010 with the older Glide64 would still freeze. So it's not a regression that used to work some time. After all these years i remember it and i thought i would test it since N64 emulation has improved a lot.

**Comment by loganmc10** [comment]
Maybe it happens on a real N64....?

**Comment by Tasosgemah** [comment]
Can't test that since i don't have the game. But even if i had it it would be the PAL version since i live in Europe and have a PAL N64.

Tried the PAL version in mupen with the same save file and it doesn't freeze.

**Comment by Sync219** [comment]
I just tested this on my N64 (it's NTSC-U) and it froze the same way as on m64p on mines. Perhaps it may be a problem with the game itself.

**Comment by loganmc10** [comment]
Very interesting! Thanks for testing, must be an actual game bug
