### ISSUE TITLE
New user, no audio

### ISSUE THREAD

**Issue by JustJeff88** [loganmc10/m64p#120]
Very embarrassed to ask, but I just downloaded this and I have no audio. I am confident that it's not my system, the interface is fine, and the graphical emulation is on point, but I do not see anything for volume control, audio plug-ins or the like.

I am sure that it's an obvious solution, but my searches have not helped. Thank you in advance.

**Comment by loganmc10** [comment]
What OS and OS version are you running?

**Comment by JustJeff88** [comment]
Win7x64

**Comment by loganmc10** [comment]
Yeah Windows 7 isn't supported on m64p, you'll need to upgrade to a supported OS like Windows 10 or Ubuntu 18.04+
