### ISSUE TITLE
Audio crackling with and without LLE graphics

### ISSUE THREAD

**Issue by pitrako** [loganmc10/m64p#121]
After some time of playing the audio starts to make weird noises but game plays at full speed (example majora's mask). 

EDIT: It happens after 50-55 seconds approximately of starting the game, always.

EDIT 2: I can't find any option to adjust audio settings on the GUI, there's no audio section in mupen64plus.cfg either.

Windows 10 x64
RTX 2080
I7-9700K

**Comment by dotchicken** [comment]
Today I had something similar in DK64. After about one minute after loading our latest savegame the game makes a static crackling sound in addition to the normal sounds/music. 
The static appeared time dependent, meaning after loading from that savegame it appeared in every other part of the game we tried (different part of the same level, other levels) after roughly one minute.

What seems to have helped, was to start the game without savegame and instead relying on the internal memory card. The game progress luckily was the same. (something i normally dont rely on).

On that savegame I had around 7+ hours played.

**Comment by pitrako** [comment]
You know a way of changing the audio settings?, because I get the problem even If I don't use savestates. I read somewhere that mupen64plus has a section called "Audio-SDL" with this options:

[Audio-SDL]

# Mupen64Plus SDL Audio Plugin config parameter version number
Version = 1
# Frequency which is used if rom doesn't want to change it
DEFAULT_FREQUENCY = 33600
# Swaps left and right channels
SWAP_CHANNELS = False
# Size of primary buffer in output samples. This is where audio is loaded after it's extracted from n64's memory.
PRIMARY_BUFFER_SIZE = 16384
# Fullness level target for Primary audio buffer, in equivalent output samples. This value must be larger than the SECONDARY_BUFFER_SIZE. Decreasing this value will reduce audio latency but requires a faster PC to avoid choppiness. Increasing this will increase audio latency but reduce the chance of drop-outs.
PRIMARY_BUFFER_TARGET = 2048
# Size of secondary buffer in output samples. This is SDL's hardware buffer. The SDL documentation states that this should be a power of two between 512 and 8192.
SECONDARY_BUFFER_SIZE = 1024
# Audio resampling algorithm. src-sinc-best-quality, src-sinc-medium-quality, src-sinc-fastest, src-zero-order-hold, src-linear, speex-fixed-{10-0}, trivial
RESAMPLE = "speex-fixed-4"
# Volume control type: 1 = SDL (only affects Mupen64Plus output)  2 = OSS mixer (adjusts master PC volume)
VOLUME_CONTROL_TYPE = 1
# Percentage change each time the volume is increased or decreased
VOLUME_ADJUST = 5
# Default volume when a game is started.  Only used if VOLUME_CONTROL_TYPE is 1
VOLUME_DEFAULT = 80
# Synchronize Video/Audio
AUDIO_SYNC = False

But m64p does not generate these options for me, and inserting them in mupen64plus.cfg does not work.

**Comment by Jj0YzL5nvJ** [comment]
[Audio-SDL2](https://github.com/m64p/mupen64plus-audio-sdl2) is different from [Audio-SDL](https://github.com/mupen64plus/mupen64plus-audio-sdl). You can't use `Audio-SDL` in m64p unless you recompile `m64p` or `Audio-SDL` with the same version of SDL2 and rename `mupen64plus-audio-sdl.dll` as `mupen64plus-audio-sdl2.dll`.
`Audio-SDL` is usually more problematic with modern versions of Windows. But it works fine on XP, Vista and 7.

I generally prefer `Audio-SDL2`, but `Audio-SDL` works best in VERY specific situations. gonetz/GLideN64#2433

**Comment by pitrako** [comment]
I have to wait for Audio-SDL2 to improve I suppose?

**Comment by Jj0YzL5nvJ** [comment]
Improving cached interpreter or the dynarecs can improve audio response indirectly.
To really improve audio response in Windows platforms you need to make a WASAPI complaint plugin.

[Minimizing Audio Latency on Windows 10 with WASAPI](http://donyaquick.com/minimizing-audio-latency-on-windows-10-with-wasapi/)

**Comment by RokkumanX** [comment]
Just wanted to add my two cents here.

Despite m64p being locked to ParaLLEl and such these days you'd be surprised how bloody forgiving it is if you attempt what @Jj0YzL5nvJ suggesting.

I use for example `mupen64plus-audio-sdl.dll` renamed to `mupen64plus-audio-sdl2.dll` without problems in the latest build, furthermore I also get away with using the cxd4 RSP renamed to `mupen64plus-rsp-parallel.dll` and `mupen64plus-video-angrylion-plus.dll` renamed to `mupen64plus-video-parallel.dll` without any problems at all.

Although you have to configure the `mupen64plus.cfg` manually in order to change settings for Audio, cxd4 and AngryLion since the GUI is made with ParaLLEl in mind.

All in all, F***ING awesome!

**Comment by pitrako** [comment]
I rename mupen64plus-audio-sdl.dll to mupen64plus-audio-sdl2.dll and It says It can't load the plugin.

**Comment by RokkumanX** [comment]
[This](https://ci.appveyor.com/project/Narann/mupen64plus-audio-sdl/builds/37865824/job/2ovux85tlmhvswal) is what I use, mupen64plus-audio-sdl_v2.5.9-22-gaf6af5b_x64

[mupen64plus-audio-sdl2.zip](https://github.com/loganmc10/m64p/files/6630689/mupen64plus-audio-sdl2.zip)

Already renamed and ready to use.

**Comment by RokkumanX** [comment]
Here is cxd4 and AngryLion also ready to use if you are interested.

[mupen64plus-rsp-parallel.zip](https://github.com/loganmc10/m64p/files/6630718/mupen64plus-rsp-parallel.zip)
[mupen64plus-video-parallel.zip](https://github.com/loganmc10/m64p/files/6630720/mupen64plus-video-parallel.zip)

The mupen64plus-video-parallel.zip contains to versions of AngryLion, one which is 360 KB and one which is 524 KB.
The difference is that the 524 KB is the official one from ata4 and the 360 KB is from the last known m64p version to contain it.

**Comment by RokkumanX** [comment]
Don't take my word on it 100% (since I don't own ALL N64 games) but there should be no major disadvantages using this, I sure haven't noticed anything out of the ordinary and my games sounds just fine.

And you can configure audio options for this (like what you posted above) in the `mupen64plus.cfg` file with no issues.

**Comment by loganmc10** [comment]
Can you test again with the latest build? I've tried to make some improvements to audio-sdl2

**Comment by pitrako** [comment]
Less noticeable, but It's there yet, but most people won't hear It. Maybe it is not worth investing more time in fixing something that people won't notice.

**Comment by RokkumanX** [comment]
I can't seem to hear anything jiffy in latest builds with mupen64plus-audio-sdl2, but I'm keeping my copy of mupen64plus-audio-sdl in any case that something is off.

Alternatives is never wrong.

**Comment by anonymous7002** [comment]
Here's GLideN64.
[mupen64plus-video-parallel.zip](https://github.com/loganmc10/m64p/files/6759998/mupen64plus-video-parallel.zip)
