### ISSUE TITLE
Issue with Xinput controller Triggers bindings

### ISSUE THREAD

**Issue by dmeagher101** [loganmc10/m64p#122]
Binding an input to the right trigger on my xinput controller (which is an Xbox Series X controller, if that makes a difference) causes the emulator to act as if the guest input is pressed when the trigger is not, and vice versa. For instance, when playing Ocarina of Time, Link will hold up his shield when I'm not holding the trigger, and not hold it up when I am holding the trigger.

**Comment by loganmc10** [comment]
Can you please post a screenshot of the controller profile? I'm curious to see what value it assigned your triggers

**Comment by dmeagher101** [comment]
![m64p_profile](https://user-images.githubusercontent.com/24301135/113095092-ba886900-91a7-11eb-83e5-c43b50c0e339.PNG)

**Comment by thekovic** [comment]
I also experience this issue.
![image](https://user-images.githubusercontent.com/72971433/114030911-20958000-987b-11eb-9fb6-82fadea16d0a.png)

**Comment by loganmc10** [comment]
@dmeagher101 @thekovic @danielharvey @zenon49

Can you try this build: https://github.com/loganmc10/m64p/suites/2476708309/artifacts/53297051 (you may have to unzip it twice because of how GitHub packages it). Just ignore the prompt to update if one appears.

Please let me know if this fixes the issue with the triggers

**Comment by danielharvey** [comment]
Just an FYI guys, you have to be logged in, in order for the link to work

**Comment by danielharvey** [comment]
I was able to test and this build resolved my problem.  Thanks @loganmc10 !

**Comment by dmeagher101** [comment]
Yes it works for me as well

**Comment by loganmc10** [comment]
ok good enough for me. This fix will be included in the next release (probably within the next few days, just hoping to get a few other fixes in). I'm going to close this since this interim build can be used in the meantime.
