### ISSUE TITLE
Linux - Update Available always shows.

### ISSUE THREAD

**Issue by spinktvis** [loganmc10/m64p#123]
When you build from the latest git on Linux, upon starting m64p it'll always show; Update Available, A newer version is available, update? Yes/no.

Is there any way to stop this via a hidden setting somewhere? If not, can this please be added?

**Comment by loganmc10** [comment]
Yes true, the auto updater should only really be enabled for official builds.

I've pushed a fix for this ,please pull in the latest repo and give it another try, you'll probably need to clean your build dir. I'd recommend just deleting the repo and re-cloning it

**Comment by spinktvis** [comment]
Thanks for the fix. Tested it, and no more Update Available pop up. Closing this.
