### ISSUE TITLE
Linux - m64p Video Settings window 

### ISSUE THREAD

**Issue by spinktvis** [loganmc10/m64p#124]
Running Arch Linux, XFCE with the ArcDark theme. When fiddling around in the Video Settings window I noticed that I couldn't adjust the size of the window. It is static by the looks of it. I am using a display resolution of 1366x768. Due to this I am unable to see the OK, Cancel, Apply boxes, and whatever else might be cut off. My request would be to make all settings windows dynamic in size, instead of a static size, so we can adjust the sizes. Either the width and height and to full screen, or a scrollbar (like the Advanced Settings window) so we can scroll to see all the settings including the OK, Cancel, and Apply buttons. I have linked a screenshot for how it looks on my system. 

As a workaround I currently just use enter on the keyboard to apply settings since I cannot click the OK or Apply buttons.

[https://imgur.com/oxgJ01S.png](url)

**Comment by loganmc10** [comment]
GlideN64 has been replaced with ParaLLEl-RDP (https://github.com/loganmc10/m64p/releases/tag/v2021.6.6). Since this issues is related to GLideN64, it is being closed.
