### ISSUE TITLE
Raphnet N64 Plugin Error

### ISSUE THREAD

**Issue by PeterN64** [loganmc10/m64p#128]
I can choice the Plugin but when its set as main plugin i get this error
"Failed to load input plugin"

**Comment by loganmc10** [comment]
What OS are you using? And are you using m64p downloaded from the releases page of this repo, or some other source?

**Comment by PeterN64** [comment]
Downloaded from here, using Windows 10.

**Comment by PeterN64** [comment]
OK! I found out you have youre own raphnet plugin allready in the directionary and thats working how it should while the original one from the devs wont. Thanks alot

**Comment by loganmc10** [comment]
Yes m64p comes bundled with the raphnet plugin, glad you got it figured out
