### ISSUE TITLE
Howto Load Hires Texture ?

### ISSUE THREAD

**Issue by Nemesisk187** [loganmc10/m64p#13]
Hi, loganmc10

I often tried loading Hires Texture, I've always had no luck.

I activated the following in the settings

Use texture pack - check
Use full transparencies - check
Alternative CRC calculation - check
Save enhanced texture cache to hard disk - check
Compress texture cache - check

My  Path: GLideN64.ini
textureFilter\txPath=D:/Emu/N64/HD/hires_texture

The emulator simply cannot find the cache ?
ini issue ? / Gui issue ? / Plugin issue ?
I tested the cache with these emu "Project64" and it worked here
I Use Windows X64 1909
I Use Build from March 31, 2020
Do you have an idea ?
Thanks for solutions!

**Comment by loganmc10** [comment]
Can you please share the texture pack you are using and which game so I can try to replicate?

**Comment by Nemesisk187** [comment]
Yes!

https://www.mediafire.com/file/nrh28wa9ihk1lft/SUPER_MARIO_64.rar/file

**Comment by Nemesisk187** [comment]
could you replicate it?

**Comment by loganmc10** [comment]
I've removed hires texture support from the latest build, so I'm going to close this as a "won't fix"
