### ISSUE TITLE
I would like a .zip file. (Mac OS X)

### ISSUE THREAD

**Issue by otherlego** [loganmc10/m64p#130]
I got a garbled mess of files when I tried to extract the DMG using Keke, a screenshot of while I have attached.
![Screen Shot 2021-03-05 at 1 34 41 PM](https://user-images.githubusercontent.com/80130470/110176046-93f92d00-7db7-11eb-89e2-ecb0517cbdc2.png)

If you right click the m64p application, there should be an option that says compress. That will turn it into a .zip file, and hopefully I would be able to download that, the same way it is with the windows and linux distros.

**Comment by loganmc10** [comment]
Edited to make it more concise and to the point

**Comment by otherlego** [comment]
(Also, the dev in question im asking this to knows why I used keke)

**Comment by loganmc10** [comment]
The project now only includes ParaLLEl-RDP, which depends on Vulkan. A Mac developer would need to adapt it before it will work again. So for the time being Mac is no longer supported
