### ISSUE TITLE
pokemon puzzle league save

### ISSUE THREAD

**Issue by rusty887** [loganmc10/m64p#131]
Hi,
  I'm having trouble getting m64p to create a save file for pokemon puzzle league. I haven't had any problems with m64p and other games. I've tried project64 and mupen64plus-ui-python and they create a save file but I'd prefer to use m64p.

**Comment by wildgoosespeeder** [comment]
Same issue here too. Trying to import the save from Project64.

**Comment by loganmc10** [comment]
What happens exactly when you try to save?

**Comment by rusty887** [comment]
saving works fine until I close the emulator
if i clear a puzzle, quit the game mode, then enter it again (without closing mupen) my profile and progress will still be there
but in appdata/roaming/Mupen64Plus a save file never appears

**Comment by loganmc10** [comment]
There is a file called mupen64plus.ini in the same directory as the exe. Can you replace it with this one:

[mupen64plusini.zip](https://github.com/loganmc10/m64p/files/6627158/mupen64plusini.zip)

And let me know if that solves the issue?

**Comment by loganmc10** [comment]
Fixed in https://github.com/loganmc10/m64p/releases/tag/v2021.6.10
