### ISSUE TITLE
Taking a Screenshot in LLE Graphics Mode Crashes Emulator

### ISSUE THREAD

**Issue by wildgoosespeeder** [loganmc10/m64p#134]
I am using the Feb 23, 2021 release. This happens in every game I try.

**Comment by wildgoosespeeder** [comment]
#111 seems to be related. Didn't see this.

**Comment by Jj0YzL5nvJ** [comment]
ata4/angrylion-rdp-plus#89

Unfiltered mode issue.

**Comment by loganmc10** [comment]
GlideN64 has been replaced with ParaLLEl-RDP (https://github.com/loganmc10/m64p/releases/tag/v2021.6.6). Since this issue is related to GLideN64, it is being closed.
