### ISSUE TITLE
Taking a Screenshot in HLE Mode Doesn't Take a Picture of Internal Resolution

### ISSUE THREAD

**Issue by wildgoosespeeder** [loganmc10/m64p#135]
I am using the Feb 23, 2021 release.

Taking a screenshot in HLE looks like it takes a picture of the render portion of the window and not the internal resolution. Happens with any game I try. I set the video to original N64 resolution and not 2x and filtering is N64-style 3 point. Project64 with any graphics plug-in (angrylion preferred) seems to take a picture of the internal resolution or the resolution is adjusted on-the-fly. I have noticed some games run true 640x480 while most run 320x240. Pokémon Stadium 2 is a good example of this. It switches between the two modes when you go to the minigames.

**Comment by loganmc10** [comment]
GlideN64 has been replaced with ParaLLEl-RDP (https://github.com/loganmc10/m64p/releases/tag/v2021.6.6). Since this issue is related to GLideN64, it is being closed.
