### ISSUE TITLE
Conker's Bad Fur Day Glitchy Shadows

### ISSUE THREAD

**Issue by wildgoosespeeder** [loganmc10/m64p#136]
I am using the Feb 23, 2021 release. 

I noticed the shadows are glitchy using LLE mode for Conker's Bad Fur Day. Haven't tried HLE. It's most noticeable at the intro screen where Conker takes a chainsaw to the N64 logo. Other parts of the game may be affected.

m64p:
![m64pconkerbfd](https://user-images.githubusercontent.com/18543809/111339982-34681080-8646-11eb-9ef1-422dbaffb789.png)

Real:
![realn64conkerbfd](https://user-images.githubusercontent.com/18543809/111339983-3500a700-8646-11eb-859b-6ce1088dbdcc.png)

**Comment by Jj0YzL5nvJ** [comment]
Unfiltered + ata4/angrylion-rdp-plus#12

`ViMode = 0`
`DpCompat = 2`

If your processor is AMD, use:
`BusyLoop = True`

**Comment by loganmc10** [comment]
Angrylion has been replaced with ParaLLEl-RDP (https://github.com/loganmc10/m64p/releases/tag/v2021.6.6). Since this issue is related to Angrylion, it is being closed.
