### ISSUE TITLE
Unplugging the Emulated Controller

### ISSUE THREAD

**Issue by wildgoosespeeder** [loganmc10/m64p#138]
I am using the Feb 23, 2021 release.

No way to emulate unplugging an N64 controller while a game is running, especially for player 1 (all four controllers preferably). It kind of works if you set it up before starting the emulation. I understand this is pointless for standard play, but this is for completeness-sake. Some games can detect it disconnected and display a warning message. The way I envision this working is how N-Rage's plug-in works in Project64; a simple check box.

**Comment by Jj0YzL5nvJ** [comment]
A good implementation would be greatly appreciated.
https://imgur.com/Lg250wF

See:
mupen64plus/mupen64plus-input-sdl#66
mupen64plus/mupen64plus-core#539

**Comment by loganmc10** [comment]
Closing all feature requests, I will accept PRs for these kinds of things but the work isn't directed based on feature requets.
