### ISSUE TITLE
Can't Edit Mappings While a Game is Loaded

### ISSUE THREAD

**Issue by wildgoosespeeder** [loganmc10/m64p#139]
I am using the Feb 23, 2021 release.

Can't edit controller profiles when a game is running/paused. Why though? I also hope that an interface improvement is in the works, similar to that of mGBA and Dolphin, to test mappings compared to a picture of the N64 controller.

**Comment by loganmc10** [comment]
Closing all feature requests, I will accept PRs for these kinds of things but the work isn't directed based on feature requets.
