### ISSUE TITLE
Controller issue April 1 release

### ISSUE THREAD

**Issue by quattj** [loganmc10/m64p#14]
I am running Windows 7 64-bit with the April 1 2020 release of m64p.  
I have a Mayflash to Wii Classic controller adapter PC045 
http://www.mayflash.com/Products/PCUSB/PC045.html
This is my first time using m64p.  I normally use Project64 but would like to use Mupen64Plus as well.

I am able to use the controller configuration for my first controller.  I create a custom config and remap my buttons as I would like, with my first controller selected.  But then if I try to play a game, I do not have any input.  

If I quit the game, and switch the selected controller to my second controller in the config (with the same saved profile selected), I then can use my controller, but it treats it as auto config so my layout is wrong.

If I keep the second controller selected, and try to modify the saved profile, I have no input in the configuration screen.  If I switch it back to the first controller, I again have input in the configuration screen.

So: input configuration works correctly.
In-game controls do not follow the input configuration.

**Comment by loganmc10** [comment]
What kind of controller is the 2nd controller?

**Comment by quattj** [comment]
The second controller is also a Wii Classic controller plugged in to the same adapter.

**Comment by loganmc10** [comment]
Can you go to:

C:\Users\%username%\AppData\Roaming\Mupen64Plus

And share the input-profiles.ini and input-settings.ini files?

**Comment by loganmc10** [comment]
By the way, I have a similar adapter (Raphnet 2 player classic adapter), and on Windows I noticed it labelled controller 1 as 0 and vice versa, they were reversed. Have you tried setting "controller 1" are player 1 and "controller 0" as player 2?

**Comment by quattj** [comment]
I had to change the extension to .txt to attach.  I have only configured my first control.  It may be possible that I could use them both if I configured them both and then swapped the selection, but I think it is better to try to fix the actual issue, especially since you mentioned recently that this is a brand new input plugin :)

[input-settings.txt](https://github.com/loganmc10/m64p/files/4428076/input-settings.txt)
[input-profiles.txt](https://github.com/loganmc10/m64p/files/4428077/input-profiles.txt)

**Comment by loganmc10** [comment]
How many controllers show up in the gamepad dropdown? Is it just ```0:Mayflash Wii Classic Controller``` and ```1:Mayflash Wii Classic Controller```, or are there others?

The profile doesn't make any sense to me, it's like it's mixing 2 different controllers together

**Comment by quattj** [comment]
There are three controllers.  I also have a Mayflash Magic-NS, which lets me use any of the console controllers that use bluetooth (Wii U Pro, PS4, XBox One, etc). 
If you look at the attached image, everything there is correct for how I configured it.  The D-Pad shows as a hat switch.  The left stick is the N64 stick, and I split the C buttons between the right stick and the right two buttons on the controller.

I will configure the other two controllers so you can see those as well, in case it is doing something bizarre.  I do see that the hat switch numbers are wonky.  I'll upload them in a few minutes.

**Comment by loganmc10** [comment]
The thing that is bizarre is that it shows up as a Hat at all. The input plugin attempts to use xinput as the driver, and then falls back to directinput. xinput has no concept of "hat", just axis and button. When I see "leftshoulder", that tells me xinput, when I see "hat" that tells me directinput. So the profile has a mixture of xinput and directinput settings.

**Comment by quattj** [comment]
Okay, I see what you are saying.  Yes, the Wii Classic controls are directinput.  Normally in other programs the L, ZL, R, and ZR show up as either buttons (5, 6, 7, 8) or two buttons and a random axis if I have them set to analog.  I'll grab a screenshot of the windows game control screen as well.

**Comment by loganmc10** [comment]
Ok, yes, with directinput, I shouldn't see "leftshoulder", it would be like "button 5", it has no way to know which button is the left shoulder. That's why it looks a bit odd. For the dpad, if it was xinput, I would expect to see "dpadleft" instead of a Hat value

**Comment by quattj** [comment]
Player 1 configured yesterday with dinput Classic control #1.  Player 2 configured dinput Classic control #2.  Player 3 xinput PS4 control.

The windows settings box show all the available buttons. Physical layout is SNES pad style.
Button order A B X Y L R ZL ZR Select Start Home
I noticed the input plugin lists the xinput names for the buttons as well.  So where it shows A and X, is actually my B (2) and Y (4).

[input-settings - Copy.txt](https://github.com/loganmc10/m64p/files/4428752/input-settings.-.Copy.txt)
[input-profiles - Copy.txt](https://github.com/loganmc10/m64p/files/4428753/input-profiles.-.Copy.txt)
![Player2](https://user-images.githubusercontent.com/63088660/78386477-a1a4a200-75ab-11ea-9350-bd296205b76c.jpg)
![Player3](https://user-images.githubusercontent.com/63088660/78386479-a1a4a200-75ab-11ea-883d-989812e7e170.jpg)
![WinSettings](https://user-images.githubusercontent.com/63088660/78386480-a23d3880-75ab-11ea-87a2-91927a4d6185.jpg)

**Comment by quattj** [comment]
I will also add that I just actually tried out the emulator with all three controllers configured.  Pokemon Puzzle League.
First control is player 2, second control is player 1.  Neither one of the controls use the assigned button configurations.  The dpad is non-functional, and the left analog stick acts as the dpad.  It appears to be using the default auto-config for xinput for both dinput controls.

**Comment by loganmc10** [comment]
Are you able to change the hat mode of the wii classic controllers? From my googling it seems like hitting Home + the L or R button will change the dpad mode to buttons/analog instead of hat?

**Comment by quattj** [comment]
It's the same as setting one of the modes in the Windows control panel.  The default, Hat Switch, offers the most functionality.  Analog mode mode changes the dpad to buttons 12 13 14 15, which affects software that can use the diagonals of the dpad as well as u/d/l/r. Digital mode assigns full 100% up, down, left, right analog stick to each direction on the dpad. (my description of digital mode in my previous reply was incorrect)

Just for fun I will test Analog mode right now.

In Analog mode, with the dpad moving to buttons 12 13 14 15, they show up in the input configuration as dpup dpdown dpleft and dpright.  In the running emulator, results are the same.  Attempting to use default xinput for each control, with no dpad functionality and dpad usage moved to the analog stick.

So the input configuration sees and accepts the inputs from my controls, but is displaying xinput naming schemes for most items, and then the emulator is ignoring the input configuration and trying to use xinput for everything.

I am able to use all of my controls normally in project64 as well as in all the other system emulators I have.  The only quirks I generally see are the choices for the right stick axis.  Sometimes they are axis 3 and 6, sometimes 5 and 6, sometimes z  and z rotation depending on the software.

Here is a screenshot of the config from project64 for reference

![Untitled-1](https://user-images.githubusercontent.com/63088660/78391639-c0f3fd00-75b4-11ea-944f-622210bd64a4.jpg)

**Comment by quattj** [comment]
What about adding an option to choose either dinput or xinput?  That way it would not try to use the xinput bindings for dinput.  Not sure if that would help when actually running the emulator, but it might.  It would at least hopefully clear up the input configuration anomalies.

**Comment by loganmc10** [comment]
The underlying plugin that accepts the input is SDL2, it attempts to use xinput first, and falls back to directinput if xinput is unsuccessful

**Comment by loganmc10** [comment]
Can you try this release: https://github.com/loganmc10/m64p/releases/tag/Apr92020

And let me know if it's solved?

**Comment by quattj** [comment]
It works!  I can configure my controllers and they work!  
With these caveats:
Controller 1 is configured with controller 1.  Controller 2 is configured with controller 2.  In the emulator they reverse, so I have to configure them, and then swap them before playing for the first time.  I can live with that.
The configuration is still showing the xinput labels for everything (except the hat labels) but they all work as they should.
I tried to configure the controls after exiting a running game and the config would not recognize button presses, but I closed and reopened the emulator and the configuration worked again.

**Comment by loganmc10** [comment]
> Controller 1 is configured with controller 1. Controller 2 is configured with controller 2. In the emulator they reverse, so I have to configure them, and then swap them before playing for the first time

Yeah there won't be much I can do about that, controller ordering is determined by SDL

> The configuration is still showing the xinput labels for everything (except the hat labels)

This is correct and expected. It tries to use the xinput labels if it can, and falls back to direct input

> I tried to configure the controls after exiting a running game and the config would not recognize button presses

I'll look into this a bit, this is pretty minor though, I'll close this issue
