### ISSUE TITLE
Pantalla Negra

### ISSUE THREAD

**Issue by The-AlexX** [loganmc10/m64p#145]
Al momento de iniciar el juego en multijugador online se pierde el video del juego mostrando una pantalla negra y solo llegandose a apreciar el audio, pasa con varios juegos que si agarran en un solo jugador pero en multijugador se buguea.
![IMG-20210402-WA0015](https://user-images.githubusercontent.com/81878472/113489190-007f4e80-9480-11eb-8c0f-1981e63d019c.jpeg)

**Comment by Jj0YzL5nvJ** [comment]
Espero que tu edición de Windows 10 sea compatible con directivas de grupo (GPO), de no ser así necesitaras buscar ayuda por fuera para averiguar como forzarlas manipulando el registro del sistema.
https://github.com/loganmc10/m64p/wiki/Quality-of-Service

[Asegurate de que tus cortafuegos no interfieran con UPnP.](https://en.wikipedia.org/wiki/Universal_Plug_and_Play#Other_components)

**Comment by loganmc10** [comment]
UPnP doesn't have any effect on m64p netplay. QoS wouldn't make a difference in this case either.

To be honest I'm not sure what the answer is, the fact that you can hear audio would mean that the game is working and netplay is working.

To be clear, when you say multiplayer, do you mean local multiplayer, or netplay?

**Comment by Jj0YzL5nvJ** [comment]
Si el juego responde con el sonido pero la pantalla sigue en negro, prueba con presionar las teclas `Windows + G` simultáneamente.

**Comment by loganmc10** [comment]
GlideN64 has been replaced with ParaLLEl-RDP (https://github.com/loganmc10/m64p/releases/tag/v2021.6.6). Since this issue is related to GLideN64, it is being closed.
