### ISSUE TITLE
failed to load core library

### ISSUE THREAD

**Issue by OmarBP** [loganmc10/m64p#146]
I use this emulator in a Mac running Big Sur and works perfectly, but I tried to use it in an old Mac using High Sierra and when I try to open the emulator I only get a message saying "Failed to load core library" and the app closes immediately

**Comment by loganmc10** [comment]
The project now only includes ParaLLEl-RDP, which depends on Vulkan. A Mac developer would need to adapt it before it will work again. So for the time being Mac is no longer supported
