### ISSUE TITLE
No picture in Extreme G and Extreme G 2

### ISSUE THREAD

**Issue by dezraj** [loganmc10/m64p#148]
I have no picture with Extreme G and Extreme G 2. The sound plays fine but the screen is black. I've only experienced this with these games so far.

I'm using intel UHD 630 integrated graphics, which has poor opengl drivers, so perhaps this could be the cause. But maybe it could be worked around via m64p and/or gliden64?

Anyway I hope it could be fixed because it's too difficult to buy a dedicated GPU where I live now (Brazil). Prices are out of reality.

My setup:
i5-10400
UHD 630 graphics w/ latest drivers (which are the same for anything 6th gen CPU Skylake or above, by the way)
16gb ram
Win10
mupen64plus-gui Apr 12 2021 (all default plugin options)

**Comment by loganmc10** [comment]
Don't worry it's not your computer, I can reproduce this on my PC, it appears to be a bug that appeared in GLideN64 sometime in February. If you use the Feb 10 build it should work (https://github.com/loganmc10/m64p/releases/tag/Feb102021)

I'll track down what caused the issue and report it to GLideN64

**Comment by dezraj** [comment]
🙌 Thank you so much for your info and fast support Logan!
I'm looking forward to testing a new version whenever it comes out. 👍

**Comment by loganmc10** [comment]
Newest release should have this problem resolved. Please re-open if its still happening
