### ISSUE TITLE
(Feature request) Portable config

### ISSUE THREAD

**Issue by dezraj** [loganmc10/m64p#150]
Would it be possible to have the configs and save files created in the root of m64p? It's not so intuitive to mess with hidden files (the AppData folder) in Windows in order to manage the save files, for example. Perhaps something like a portable.txt file as we have in Dolphin, PCSX2, DuckStation and other emus?

I don't know if this is a limitation of Mupen64Plus though.

**Comment by Amnesia1000** [comment]
Excellent idea, in Linux the configurations are stored in "/home/user/.config/mupen64plus" and for example the textures are stored in "/home/user/.local/share/mupen64plus/hires_texture". If everything could be stored in the same folder as the executable it would be more convenient.

**Comment by Jj0YzL5nvJ** [comment]
> If everything could be stored in the same folder as the executable it would be more convenient.

Mmm... something like taking: https://gist.github.com/Jj0YzL5nvJ/5242753837eed35768e61c240f572ecd
 
And replace
```
MYSCRIPT="$ORIG/m64p_test/m64pp"
```
for
```
MYSCRIPT="$ORIG/m64p_test/m64pp"
mkdir -p "$ORIG/m64p_test/conf" "$ORIG/m64p_test/save" "$ORIG/m64p_test/ss" "$ORIG/m64p_test/hires_texture"
```
,
```
echo "SEMIPORTABLE=\"--corelib \$ORIG/$CORE_NAME --plugindir \$ORIG --datadir \$ORIG\"">>"$MYSCRIPT"
```
for
```
echo "PORTABLE=\"--corelib \$ORIG/$CORE_NAME --plugindir \$ORIG --datadir \$ORIG --configdir \$ORIG/conf --savestate \$ORIG/save --sshotdir \$ORIG/ss\"">>"$MYSCRIPT"
```
and
```
echo "\$ORIG/./mupen64plus \$SEMIPORTABLE \"\${@}\"">>"$MYSCRIPT"
```
for
```
echo "\$ORIG/./mupen64plus \$PORTABLE --set Video-GLideN64[txPath]=\$ORIG/hires_texture \"\${@}\"">>"$MYSCRIPT"
```
?

**Comment by Jj0YzL5nvJ** [comment]
> Would it be possible to have the configs and save files created in the root of m64p?

[m64p_portable.zip](https://github.com/loganmc10/m64p/files/6550345/m64p_portable.zip)

**Comment by dezraj** [comment]
Thanks Jj0YzL5nvJ! When I run your command prompt I have this error message when I click on "open rom":

![image](https://user-images.githubusercontent.com/27839354/119756849-74374980-be7a-11eb-9a1a-89e2a0c236c1.png)

But if I click "ok" and locate my rom it runs normally.

Except that this workaround creates the whole tree of folders in the root o m64p, so "Portable -> AppData -> Roaming -> Mupen64Plus" -> and finally the "save" folder which we wanted.

I'd rather have these folders in the emulator root for less clicks (that is, easier access).

Thanks anyway for your help!

**Comment by Amnesia1000** [comment]
But this is for compiling mupen64plus, not m64p.

**Comment by dezraj** [comment]
> But this is for compiling mupen64plus, not m64p.

You mean the command prompt? I thought it was for m64p. Well, I know nothing about coding. But I could use it with the current m64p release the way I reported in my previous reply. 😕

**Comment by Amnesia1000** [comment]
Sorry, I was saying to Jj0YzL5nvJ. I have not tested your code, since it is a CMD but I will test if the code works to compile on Linux.

**Comment by Amnesia1000** [comment]
Check the code, I had already tried something similar, but it is not what you are trying to achieve, or rather asking for. What is expected is that automatically when starting the executable, either Windows or Linux, when configuring it, automatically saves the configuration in the same directory of the executable.

**Comment by Jj0YzL5nvJ** [comment]
> ![image](https://user-images.githubusercontent.com/27839354/119756849-74374980-be7a-11eb-9a1a-89e2a0c236c1.png)

 ¬¬u . . . . . . . [m64p_portable.zip](https://github.com/loganmc10/m64p/files/6551600/m64p_portable.zip)

@Amnesia1000, try:
```
#!/bin/bash
set -e

ORIG=`dirname "$0"`
mkdir -p "$ORIG/ss" "$ORIG/save" "$ORIG/hires_texture"
PORTABLE="--corelib $ORIG/libmupen64plus.so.2.0.0 --plugindir $ORIG --datadir $ORIG --configdir $ORIG --sshotdir $ORIG/ss --set Core[SaveStatePath]=$ORIG/save --set Core[SaveSRAMPath]=$ORIG/save"

$ORIG/./mupen64plus $PORTABLE --set Video-GLideN64[txPath]=$ORIG/hires_texture "${@}"

```

**Comment by dezraj** [comment]
Thank you Jj0YzL5nvJ. Your command prompt file no longer shows the error message when loading a rom. But I've noticed that it doesn't save the gfx plugin options that I change. It seems it will always the default config. For example, I always have to enable the OSD to show the fps because it won't save these settings.

Is that the expected behavior with your file?

Thank you anyway for your trying to help. 👍
