### ISSUE TITLE
Indiana Jones and the Infernal Machine: Game freezes after Level 12

### ISSUE THREAD

**Issue by thekovic** [loganmc10/m64p#151]
After finishing Level 12 Meroe, the game slows down to 0-1 FPS in the shop, effectively freezing and preventing from continuing. A workaround is to set CountPerOp = 1 but that slows down the game speed by ~25 % (basically slow motion) I'd like to query if a more robust fix would be possible.

![image](https://user-images.githubusercontent.com/72971433/114955512-25e76180-9e5d-11eb-836a-cd8f115bbb34.png)

EDIT: Reopened because issue still exists including the slowdown at CountPerOp = 1.

**Comment by pahuffman** [comment]
I am also experiencing this issue. You can use the CountPerOp = 1 workaround. As soon as you enter King Sol's mines, you can save, undo the setting, and continue as normal. Annoying to be sure but it is possible to get around.

**Comment by thekovic** [comment]
I am aware of the CountPerOp = 1 workaround however playing with that is annoying as it introduces slowdown and audio crackling.

**Comment by pahuffman** [comment]
Oh I completely agree. It's really annoying. My only point was once you pass the shop screen you can save and revert the setting back to 0. You don't have to keep the CountPerOp = 1 setting for anything other than that one particular shop.

**Comment by thekovic** [comment]
You gotta reach the shop first which means playing Meroe with CountPerOp = 1

**Comment by pahuffman** [comment]
You can play all the way until the game freezes with CountPerOp = 0. Then when you restart with CountPerOp = 1, it puts you right next to the mine cart at the end of the level. All you have to do is turn around, jump in the cart, and end the level to the shop. Once you exit the shop to the next level, you can restart again with CountPerOp = 0.

**Comment by thekovic** [comment]
I am aware. I didn't want to mention this but what you're describing is irrelevant when you play the level like this https://www.youtube.com/watch?v=fWeXv5CkJ8g

**Comment by pahuffman** [comment]
Hahaha that's one of the greatest glitches I've ever seen. Is there a way to end the glitch in the final room, save, then do the workaround?

**Comment by thekovic** [comment]
Impossible to finish the level if you do that because you don't have the gasoline and wheel necessary to repair the minecart and finish the level the intended way (rather than flying directly into the level end trigger). You could gather these items beforehand but that loses minutes of time.

**Comment by thekovic** [comment]
I am very pleased to report that when using the new dynarec, this issue is no longer present. Unless something breaks in the future, I believe this can closed.
