### ISSUE TITLE
Latest version (April 12th) won't start on macOS

### ISSUE THREAD

**Issue by Shrapnel21** [loganmc10/m64p#152]
Hi there!
I downloaded the latest version and it won't start on macOS Catalina, it just gives an error about being unable to load the video plugin and sits there doin nothing.
The error pops up again if I try loading a ROM, and then the emulator hangs.
The previous version worked just fine, I redownloaded it and I'm using it in place of the last one without any problem.
Thanks and keep up the good work! =)

**Comment by loganmc10** [comment]
I believe it only works with Big Sur, but I don't have a Mac to test unfortunately

**Comment by Shrapnel21** [comment]
Oh, ok, I get it now. Thanks! =)

**Comment by olliebarbs** [comment]
Hi, I get this error on Big Sur too. Neither the April 12th version nor the 19th work for me. The video plugin doesnt load as the original comment says. I can still use earlier versions. 
Thanks for all your hard work on this amazing project

**Comment by loganmc10** [comment]
The project now only includes ParaLLEl-RDP, which depends on Vulkan. A Mac developer would need to adapt it before it will work again. So for the time being Mac is no longer supported
