### ISSUE TITLE
Huge slowdown in performance

### ISSUE THREAD

**Issue by sappergr** [loganmc10/m64p#153]
The last two releases made in april have caused  major slowdown in perfomance. I haven no clue what is causing it though. Wave Race can't get more than 5 fps for example.

**Comment by loganmc10** [comment]
Can you provide some system specs/details?

**Comment by sappergr** [comment]
**CPU**: FX-4300, **RAM**: 8gb DDR3 1600 **GPU**: GeForce 730 1gb, Like I said I'm experiencing a huge slowdown in the current build, The emulator is really struggling to reach 100% speed. Everything is fine with any other N64 emulators I've tried (libretro cores and Project 64).

I suspect that something in the current build is causing a resource hog, also note that I'm using the out of the box default settings and I've not tampered with them. Sorry if I'm not providing enough information, I know nothing about coding.

**Comment by loganmc10** [comment]
Can you try with the latest build? Is this still a problem now that the emulator switched to a different GFX plugin?
