### ISSUE TITLE
8BitDo SN30 Pro+ xinput mode - A and B configurations are ignored

### ISSUE THREAD

**Issue by mariomadproductions** [loganmc10/m64p#155]
When using the 8BitDo SN30 Pro+ in its xinput mode, the mappings for the N64 A and B buttons are ignored, instead the controllers B and Y<sup>1</sup> buttons are mapped to the N64 A and B buttons.

<sup>1</sup>bottom and left buttons, respectively. probably sent via xinput as the xbox 360 "A" and "X" buttons.

**Comment by loganmc10** [comment]
Are you using the default profile, or did you make your own controller profile? If you made your own, can you post a screenshot?

**Comment by mariomadproductions** [comment]
Seems like this has fixed itself. Not sure what has changed.

Anyway:
![image](https://user-images.githubusercontent.com/9919020/115623327-f5864400-a2f0-11eb-8ca0-282be8f35c7d.png)
