### ISSUE TITLE
Help Wanted:  How to enable Cheats

### ISSUE THREAD

**Issue by EnterUserNameHere1984** [loganmc10/m64p#156]
I am using Windows 10.  I am aware that the original Mupen64Plus had cheat functionality through command line, however m64p has replaced the command line with GUI but there doesn't seem to be a tab for cheats.  

  I transitioned from Project 64 to m64p as it is so far a much more accurate emulator.  I played through most of Banjo Kazooie on PJ64 and used a 60fps cheat to make the game more playable.  

  I could just be spoiled by this point but afterwards playing the game on m64p at a stuttery ~25 fps made it pretty unplayable for me, or at least very aggravating.  
 There is a cheat text included with the emulator (mupencheat.txt) but seemingly no way to enable them.  Everywhere I looked no one seemed to have an answer, even on the user guide.  
One guy I know manged to figure it out but he seems to have forgot how to do it.  

Perhaps in the future there could be A PJ64 style cheats menu but as of now is there any way to enable cheats?

**Comment by Jj0YzL5nvJ** [comment]
[Example...](https://github.com/loganmc10/m64p/blob/main/mupen64plus-core/data/mupen64plus.ini#L9226-L9234)

P.S: Netplay will only work with users with exactly the same `mupen64plus.ini` that you have.

**Comment by EnterUserNameHere1984** [comment]
Tested It out, it works!  Still, glad to get these patches working!  Thanks there was no documentation anywhere I could find about this.

As for the second comment I agree changing framerates in games can often be more trouble than it's worth, but if there are no issues or the issues are very minor.  (Like in banjo kazooie the only real issue is text moving a bit faster than it should)
