### ISSUE TITLE
Pokemon Snap crashes emulator in latest build at Professor Oak

### ISSUE THREAD

**Issue by 2nukes** [loganmc10/m64p#158]
I think this is a regression. Newest build crashes when Oak is grading photos. I downloaded the Feb 10 build and it does not crash, but has the issue with Pokemon not being recognized/glitch with photos.

**Comment by loganmc10** [comment]
Can you try this build and let me know?

https://github.com/loganmc10/m64p/suites/2640531845/artifacts/57966878

Just ignore the update message when you launch it

**Comment by loganmc10** [comment]
Closing. Please reopen if it's still an issue
