### ISSUE TITLE
Extreme G picture is randomly trembling / shaking / unstable

### ISSUE THREAD

**Issue by dezraj** [loganmc10/m64p#159]
I'm experiencing this weird issue with Extreme G. The picture will become unstable and start trembling eventually when playing the game. It mostly happens in the game menus as far as I've noticed. I don't know exactly how to trigger it, but it looks like if you let the game demo run until it loads the first race and rapidly press A to leave it, it will probably trigger the bug in the menus.

I've recorded a video of the bug happening in which I use the method described above to reproduce it: https://drive.google.com/file/d/1WCHv1WtbC69d0Y4p51BJ9pSxoAIL8k9d/view?usp=sharing

It's somewhat difficult to get used to this shaking screen and enjoy the game play, and since I don't know if the cause lies on m64p, mupen64plus or the graphics plugin, I'm reporting it here.

I'm using Windows 10 and integrated Intel UHD630 graphics with latest drivers.

I hope you can reproduce it and possibly fix it.

**Comment by Jj0YzL5nvJ** [comment]
[I can reproduce this on upstream. Plus a second derived issue.](https://imgur.com/a/EMKvGei)

[Extreme-G.zip](https://github.com/loganmc10/m64p/files/6483957/Extreme-G.zip)

**Tricky FBInfo bug?**
```
--windowed --resolution 640x480 --emumode 0 --gfx mupen64plus-video-GLideN64.so --set Video-GLideN64[EnableCustomSettings]=False --set Video-GLideN64[EnableN64DepthCompare]=2 --set Video-GLideN64[DisableFBInfo]=False --set Video-GLideN64[FBInfoReadColorChunk]=True --set Video-GLideN64[EnableCopyColorToRDRAM]=1
```

**Comment by loganmc10** [comment]
GlideN64 has been replaced with ParaLLEl-RDP (https://github.com/loganmc10/m64p/releases/tag/v2021.6.6). Since this issue is related to GLideN64, it is being closed.
