### ISSUE TITLE
Controller mapping for emulators functions

### ISSUE THREAD

**Issue by j8r** [loganmc10/m64p#161]
It would be very useful to be able to asign custom keys, including controller buttons, to system functions, like loading/saving a game state, exiting, configuration menu.
I haven't seen this in the UI, might be possible directly in a configuration file (which could be fine).

The use case is to be able to only use a controller - and nothing else - to play (which means loading/saving a game).

I'll take as example MAME, which has virtually all functions configurable to virtually any button, and allows combinations like
`KEYCODE_1 OR JOYCODE_1_BUTTON10 NOT JOYCODE_1_BUTTON5 JOYCODE_1_BUTTON6 `

Without going such route, having a button to bring a menu like Retroarch would be even better - and possibly simpler.

**Comment by loganmc10** [comment]
Closing all feature requests, I will accept PRs for these kinds of things but the work isn't directed based on feature requets.
