### ISSUE TITLE
Games look buggy

### ISSUE THREAD

**Issue by Toadfield** [loganmc10/m64p#166]
I didn't play n64 games for a while,last month I only played snes games,but today I wanted to play some n64 game again,I tried to play Kirby and the crystal shards,but when I resize the window or make it fullscreen,then it looks like this
![image](https://user-images.githubusercontent.com/68649672/120927338-f2001e00-c6e0-11eb-8350-7f03f4a44ac0.png)

**Comment by loganmc10** [comment]
GlideN64 has been replaced with ParaLLEl-RDP (https://github.com/loganmc10/m64p/releases/tag/v2021.6.6). Since this issue is related to GLideN64, it is being closed.
