### ISSUE TITLE
[Feature Request] When you start a game that then the window resolution gets rezised to the same as how it was before

### ISSUE THREAD

**Issue by Toadfield** [loganmc10/m64p#167]
What I mean is,normally it looks like this:
![image](https://user-images.githubusercontent.com/68649672/120927937-f3cae100-c6e2-11eb-9d9e-2b1f4a693490.png)
but when I start a game,then it looks like this:
![image](https://user-images.githubusercontent.com/68649672/120927959-0a713800-c6e3-11eb-9126-b9fb445575c7.png)
I have to resize the window so it is properly displayed.

**Comment by loganmc10** [comment]
GlideN64 has been replaced with ParaLLEl-RDP (https://github.com/loganmc10/m64p/releases/tag/v2021.6.6). Since this issue is related to GLideN64, it is being closed.
