### ISSUE TITLE
[Feature Request] That you can overclock the N64

### ISSUE THREAD

**Issue by Toadfield** [loganmc10/m64p#168]
With Project64 you can overclock the N64 I think.
This feature is necassery cause many games lag.

**Comment by Jj0YzL5nvJ** [comment]
I'm more interested in "underclocking" or "variable frame rate emulation". Donkey Kong 64 runs too fast and messing with CountPerOp only breaks the game more. GoldenEye demos are very broken too.

**Comment by loganmc10** [comment]
Closing all feature requests, I will accept PRs for these kinds of things but the work isn't directed based on feature requets.
