### ISSUE TITLE
[Feature Request] Per-game settings for Parallel-RDP

### ISSUE THREAD

**Issue by Turaltay** [loganmc10/m64p#169]
I opened the ParaLLEl Video tab and changed the value for Upscaling but the emulator didn't save it. Same for other settings like Fullscreen. Is this a similar problem like the saving problem with non-Latin characters? Additionally i wanted to ask if it is possible to crop the left, right, top and bottom black borders (like in GlideN64) specifically for every game. This was a great feature and i would be really happy to use it with ParaLLEl.

**Comment by loganmc10** [comment]
The released build still doesn't have the Unicode fix, I'm waiting for a PR to get merged with mupen64plus-core.

**Comment by Turaltay** [comment]
Alright. Thank you for the quick reply! Will or is there some cropping feature within ParaLLEl? Every game seems to have specific black borders. This was handled pretty easy with GlideN64.
Example one is for Mario Kart 
![1](https://user-images.githubusercontent.com/39458480/121015159-f426b300-c79a-11eb-9c53-43c41f46d72e.png)
Example two is for Bomberman 64
![2](https://user-images.githubusercontent.com/39458480/121015193-fe48b180-c79a-11eb-8e0b-e1d890f65fa9.png)

Would be nice if we could do this with ParaLLEl too.

**Comment by loganmc10** [comment]
Parallel-RDP does have a CropOverscan option, where you can specify the number of pixels to crop:
![image](https://user-images.githubusercontent.com/848146/121025906-e35a4b00-c762-11eb-89c4-16f30d10feb8.png)

It's not possible to specify a different value for each edge. That is a limitation of the plugin itself, so there isn't much I can do there.

As for per-game settings, I wouldn't rule that out, but it's not something I plan on implementing. I'd be happy to accept a PR if someone wants to write a system for per-game settings in m64p

**Comment by mudlord** [comment]
That would be something on the plugin side I have to do in pull requests. Down the line a proper Vulkan only rendering/compute context hopefully could be done which removes the image copy side of it (might help speed on very old cards, since PCIE4 is more than enough)

**Comment by loganmc10** [comment]
Closing all feature requests, I will accept PRs for these kinds of things but the work isn't directed based on feature requets.
