### ISSUE TITLE
Xena - Warrior Princess - Talisman of Fate black screen/not booting

### ISSUE THREAD

**Issue by pitrako** [loganmc10/m64p#170]
Does not boot even with the new added parallel graphics plugin.

**Comment by loganmc10** [comment]
Xena requires a CountPerOp setting of 3, I assume you've changed CountPerOp to something else?

![image](https://user-images.githubusercontent.com/848146/121025563-852d6800-c762-11eb-9391-a2aa32d1969a.png)

"0" means take the value from the INI file, which would be 3 in the case of Xena, but if you've set this to 1 or 2, it'll override what is in the INI file and Xena won't boot

**Comment by pitrako** [comment]
If I set countperop to 0 or 3 in core options It doesn't boot either way, in mupen64plus.ini and core options I have this:
![xena1](https://user-images.githubusercontent.com/42267151/121029729-25a67b00-c7a9-11eb-8761-355d6ef9a946.jpg)
![xena2](https://user-images.githubusercontent.com/42267151/121029745-28a16b80-c7a9-11eb-8fb1-b94198bc73c7.jpg)

**Comment by loganmc10** [comment]
Can you boot the game, and then go to Emulation-View Log and post what you see here:

```
Core: Goodname: Xena Warrior Princess - The Talisman of Fate (U) [!]
Core: Name: XENAWARRIORPRINCESS 
Core: MD5: 1AC234649D28F09E82C0D11ABB17F03B
Core: CRC: 0553AE9D EAD8E0C1
```

**Comment by pitrako** [comment]
Core: Using full mem base
Core: Goodname: Xena Warrior Princess - The Talisman of Fate (E) [!]
Core: Name: XENAWARRIORPRINCESS 
Core: MD5: EC2BCB1B7FC7D068BE1F39E79E49A842
Core: CRC: 0A1667C7 293346A6
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
Core: Version: 1449
Core: Manufacturer: Nintendo
Core: Country: Europe (0x50)
Core: input plugin did not specify a render callback; there will be no on screen display by the input plugin.
Core: Using video capture backend: dummy
Core: Game controller 0 (Standard controller) has a Memory pak plugged in
Core: Game controller 1 (Standard controller) has a Memory pak plugged in
Core: Game controller 2 (Standard controller) has a Memory pak plugged in
Core: Game controller 3 (Standard controller) has a Memory pak plugged in
Core: Using CIC type X102
Core: Initializing 4 RDRAM modules for a total of 8 MB
Core: Starting R4300 emulator: Cached Interpreter

**Comment by pitrako** [comment]
USA version works.

**Comment by loganmc10** [comment]
Yeah it looks like the E version needs CountPerOp=4. I just submitted a PR to mupen64plus-core to have the INI updated:

https://github.com/mupen64plus/mupen64plus-core/pull/863

**Comment by pitrako** [comment]
Thanks, a while ago I opened an issue about a light sound crackling after some time of playing in all games I tried (for example majora's mask, goldeneye, hercules and this game) and the games seem full speed (no slowdowns), what might happening?:
https://github.com/loganmc10/m64p/issues/121

**Comment by loganmc10** [comment]
Fixed in https://github.com/loganmc10/m64p/releases/tag/v2021.6.10
