### ISSUE TITLE
Request for a final build with GLideN64 with disabled update features

### ISSUE THREAD

**Issue by darklinkpower** [loganmc10/m64p#171]
My laptop has a 860m graphics card and a 4710HQ which unfortunately is not enough to run m64p with Parallel outside of 1x resolution.

My request is to see if it is possible to release a final build with disabled update features so users that can't use the new m64p for compatibility or performance reasons can stay in an old build with GLiden64 without having to see the update dialogue when m64p starts. I hope that I'm not missing something and there isn't a setting to disable update checks, but even then I think a final legacy build with update features disabled by default could be useful for a lot of people.

**Comment by loganmc10** [comment]
Sure, I've updated the included files with the last GLideN64 build:

https://github.com/loganmc10/m64p/releases/tag/v2021.5.30

To remove the auto updater

**Comment by darklinkpower** [comment]
Thanks a lot, I appreciate it.
