### ISSUE TITLE
[Feature Request] More beautiful settings menu

### ISSUE THREAD

**Issue by thekovic** [loganmc10/m64p#175]
The old GlideN64 menu was very comfortable to navigate and provided clear explanations for its options. The menu for ParaLLEI is a regression, being implemented the same way as the Core options menu, a long scroll down list with no explanations.

Also, please move the CountPerOp options higher in the list, it's something I change often for games and scrolling down is inconvenient.

**Comment by loganmc10** [comment]
This project is no longer taking feature requests, however you are able to get an explanation of the options by hovering your mouse over the name:

![image](https://user-images.githubusercontent.com/848146/121378993-decb9900-c900-11eb-9754-954a8647446a.png)
