### ISSUE TITLE
Black Screen on Several Mario 64 Hacks

### ISSUE THREAD

**Issue by 0lhi** [loganmc10/m64p#177]
**Describe the bug**

Black Screen on the following games:

Super Mario Star Road Final (MD5 80e5019c9dd12648f909b3a5715ed580)
Super Mario Star Road Deluxe: (MD5 e7038e631b0680ed0aea983c586a6cd6)
SM64 The Green Stars v2 (MD5 2594eb00366410979c3ba3149d4b8a30)

A sound can be heard, but only in the beginning.

Games with a visible intro that are unplayable:

Star Road Multiplayer 1.2.1 (MD5 66d68c94762672e166e2a387fa01b387)
SM64 The Green Stars (MD5 08281bc1205374e55412386564f5641d)
Super Mario 74 (MD5 15d688de0d23bb437d95c358c635465f)
Super Mario 74 Extreme Edition (MD5 ee7673685f78ab9a6990b4f36eea1df3)
Super Mario Bros 3D (MD5 07ce89e75e2d731b91c5475a51b64417)

The normal Super Mario 64 (MD5 20b854b239203baf6c961b850a4a51a2) works as expected.

**To Reproduce**
Acquire any of these games to test yourself.

**Expected behavior**
The games should work. At least for Super Mario Star Road Final, I can confirm that it works on RetroArch with the ParaLLEl core. I can test the others, too, if need be.

**Screenshots**
\-

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Version: m64p June 9 2021
 - GPU: GeForce GTX 1050

**Additional context**
\-

**Comment by loganmc10** [comment]
These ROM hacks are unsupported. They don't work on a real N64. I would suggest playing them using Project64, which is what they are designed for.

I would consider them Project64 games, not N64 games.

Note: this doesn't go for all ROM hacks, but many Super Mario 64 hacks were written in such a way that they don't work on real hardware
