### ISSUE TITLE
hires textures appear to be broken

### ISSUE THREAD

**Issue by CDBlueX** [loganmc10/m64p#18]
Hires custom textures used to work, but with this latest release (and perhaps the one before, I didn't test it in the April 1st release) they don't seem to work anymore.  I tried placing my htc files in the cache folder (where they used to be/work) and hires_texture folders, and neither appears to work.  I checked my mupen64plus.cfg and GLideN64.ini files and both show enabled...  txHiresEnable = True and textureFilter\txHiresEnable=1  System in question is Windows 10, 64-bit (latest 1909 release).

**Comment by loganmc10** [comment]
Hires textures aren't supported anymore in m64p
