### ISSUE TITLE
Where did all the settings go after the latest update?

### ISSUE THREAD

**Issue by arilando** [loganmc10/m64p#180]
After the latest update i can't find any place to set upscaling, widescreen etc. Changing the settings in "Core and Video settings" doesn't do anything.

**Comment by loganmc10** [comment]
GlideN64 was replaced with ParaLLEl-RDP, the settings for ParaLLEl-RDP can be found in "Core and Video Settings" under the "Parallel video" tab

You need to restart the game for settings to take affect
