### ISSUE TITLE
Have Upscaling on by default (to 2x at least?)

### ISSUE THREAD

**Issue by bkimmett** [loganmc10/m64p#181]
I'm part of a community of Paper Mario romhack makers. M64P's recent switch to ParaLLeL graphics has given the emulator better compatibility with our romhacks, but people who use it are complaining that the game looks pixelated (because new versions of M64P default to 1x upscaling).

As most people in the modern day don't really want to play N64 games in a tiny window, **could it be possible that upscaling would start at 2x by default on new installations of M64P?** It feels like most players would want this, and we'd stop having to explain to people how to set the setting.

**Comment by loganmc10** [comment]
No, ParaLLEl-RDP is much more demanding than GlideN64, defaulting to 2x would cause performance issues for many users
