### ISSUE TITLE
When starting Ocarina of Time, It just crash

### ISSUE THREAD

**Issue by kirk33120** [loganmc10/m64p#183]
**Describe the bug**
It crashed the emulator when starting OoT

**To Reproduce**
1. Go to 'm64p'
2. Click on 'open rom'
3. Click on 'Ocarina of Time v.1.0
4. Crash

**Expected behavior**
To run the game perfectly

**Screenshots**
None
**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 10 Pro
 - GPU: Intel HD Graphics (It just said that)

**Additional context**
I'm scared if the problem is cause by my laptop gpu
and this is my first time using it

**Comment by loganmc10** [comment]
You should try to find out what kind/model of Intel HD Graphics you have. This emulator requires Intel Skylake or newer, which I believe is Intel HD Graphics 500 or newer

**Comment by kirk33120** [comment]
welp the gpu of this thing is 2012 and Intel HD Graphics 500 is 2015. thx for the support man

**Comment by loganmc10** [comment]
Yes sorry the emulator requires Vulkan 1.1 support.
