### ISSUE TITLE
Dynamic Recompiler crash during gameplay in Indiana Jones and the Infernal Machine

### ISSUE THREAD

**Issue by thekovic** [loganmc10/m64p#184]
**Describe the bug**
In certain levels, there are cobwebs and vines that Indy must cut through with his machete to progress (see image). Attempting to do this crashes the emulator when R4300Emulator is set to 2 ("Dynamic Compiler"). Reverting back to old value of 1 gets around the crash.

**To Reproduce**
1. Reset config to default using the "Reset All Settings" button which sets R4300Emulator to new default of 2.
2. Go to a level with a cobweb/vine (good examples are Level 9 - Teotihuacan or Level 10 - Olmec Valley)
3. Equip the machete and attack the cobweb/vine to cut through them
4. Experience crash

**Expected behavior**
No crash when using the dynamic recompiler.

**Screenshots**
![image](https://user-images.githubusercontent.com/72971433/122910827-f3734c80-d356-11eb-8ba8-70b9e033f6ec.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - CPU: i5-8300H
 - GPU: GTX 1050Ti

**Comment by loganmc10** [comment]
Can you provide a savestate at a location so it can be reproduced quickly?

**Comment by thekovic** [comment]
This save state (slot 9) should be made at the exact location as shown in the screenshot.
[Indiana Jones and the Infernal Machine (U) [!].zip](https://github.com/loganmc10/m64p/files/6693657/Indiana.Jones.and.the.Infernal.Machine.U.zip)

**Comment by thekovic** [comment]
Sure, here you go 
[Indiana Jones.zip](https://github.com/loganmc10/m64p/files/6695728/Indiana.Jones.zip)

**Comment by thekovic** [comment]
Seeing issue #185 report similar crashing to this issue, I did more comprehensive testing and I now have (nearly) complete list of items that crash the game.
**Crashes:**
- any firearm (including Bazooka)
- swinging fists/machete at an enemy
- swinging fists/machete at a wall/cobweb/vine
- using Urgon's Part
Game also crashes when human NPC (the Russians) use their weapons.
**Doesn't crash:**
- swinging whip at air
- swinging whip at wolves in Level 3 - Tian Shan River
- swinging machete at air
- using the lighter
- using Azerim's part, Taklit's part and Tool from Beyond
Not tested:
- using Nub's Part
- swinging whip at human NPC (they kept crashing my game before the whip could land)

I feel like I should have tested all this before submitting the issue in the first place. I wasn't open-minded enough with regards to what might be causing the crash, when I swung the machete at air and it didn't crash, I assumed it's just the vines. I apologize.

**Comment by loganmc10** [comment]
no worries, @Gillou68310 is on the case, he'll get it figured out

**Comment by thekovic** [comment]
I see, he's the one doing the new dynarec in [#871](https://github.com/mupen64plus/mupen64plus-core/pull/871)

**Comment by m4xw** [comment]
> 
> 
> Seeing issue #185 report similar crashing to this issue, I did more comprehensive testing and I now have (nearly) complete list of items that crash the game.
> **Crashes:**
> 
>     * any firearm (including Bazooka)
> 
>     * swinging fists/machete at an enemy
> 
>     * swinging fists/machete at a wall/cobweb/vine
> 
>     * using Urgon's Part
> 
> 
> Game also crashes when human NPCs (the Russians) use their weapons.
> 
> **Doesn't crash:**
> 
>     * swinging whip at air
> 
>     * swinging whip at wolves in Level 3 - Tian Shan River
> 
>     * swinging machete at air
> 
>     * using the lighter
> 
>     * using Azerim's part, Taklit's part and Tool from Beyond
> 
> 
> **Not tested:**
> 
>     * using Nub's Part
> 
>     * swinging whip at human NPC (they kept crashing my game before the whip could land)
> 
> 
> I feel like I should have tested all this before submitting the issue in the first place. I wasn't open-minded enough with regards to what might be causing the crash, when I swung the machete at air and it didn't crash, I assumed it's just the vines. I apologize.

That would be this one (applies to all backends) https://github.com/libretro/mupen64plus-core/commit/22ef791ce7cf3a1eb88ef20fc1058f36799182a1

Ofc this is not a fix :P

**Comment by loganmc10** [comment]
Fixed in latest release: https://github.com/loganmc10/m64p/releases/tag/v2021.6.23 . Please reopen if it happens again after updating
