### ISSUE TITLE
GPD Win 3 (Intel Iris Xe G7) graphical glitches when upscaling

### ISSUE THREAD

**Issue by Manu270891** [loganmc10/m64p#185]
**Describe the bug**
Running upscaled games on the GPD Win 3 (Core i7-1165G7 with Intel Iris Xe G7 GPU) shows some graphical glitches not present on my PC (AMD Ryzen 9 3900XT with RTX 2080 SUPER). Both machines are running the emulator on the same settings.

**To Reproduce**

1. Reset the config to the default using the "Reset All Settings".
2. OPTIONAL for Indiana Jones and the Infernal Machine: Change the "R4300Emulator" setting to "1". "2" makes the game crash with some actions, for example, when shooting the gun.
3. Change the "Upscaling" setting to anything above "1" ("2", "4" or "8"). The GPD Win 3 at 15W TDP only sustains stable framerates at "2".
4. Experience the graphical glitches, as shown below.

**Expected behavior**
No graphical glitches on the GPD Win 3 when upscaling the graphics.

**Screenshots**
GPD Win 3 with the "Upscaling" setting at "2" on Indiana Jones and The Infernal Machine:
![GPD Win 3](https://user-images.githubusercontent.com/11939758/122950834-144e9880-d37d-11eb-8bfd-a27f3706bd6e.png)
My PC with the "Upscaling" setting at "2" on Indiana Jones and The Infernal Machine:
![PC](https://user-images.githubusercontent.com/11939758/122950897-20d2f100-d37d-11eb-898e-a6bbda23e4ef.png)
GPD Win 3 with the "Upscaling" setting at "2" on Perfect Dark:
![Perfect Dark](https://user-images.githubusercontent.com/11939758/122953082-bb7fff80-d37e-11eb-9e01-42d683aa7332.png)

**Desktop (please complete the following information):**
 - OS: Windows.
 - Version: 10 21H1.
 - Device: GPD Win 3.
 - CPU: Intel Core i7-1165G7.
 - GPU: Intel Iris Xe G7.

**Comment by loganmc10** [comment]
Are you able to test the RetroArch mupen64plus-next core? It also includes Parallel-RDP(you have to enable it in the settings). I'm curious if it happens there or if this is specific to m64p

**Comment by Manu270891** [comment]
> Are you able to test the RetroArch mupen64plus-next core? It also includes Parallel-RDP(you have to enable it in the settings). I'm curious if it happens there or if this is specific to m64p

RetroArch mupen64plus-next core crashes on my GPD Win 3 if I select the "Parallel-RDP" RDP Plugin, it doesn't matter which RSP plugin I select. Angrylion and GlideN64 still work.

**Comment by loganmc10** [comment]
Ok, I don't know if I'll be able to be much help. Both the games you showed (Indiana Jones and Perfect Dark) use interlacing, and the artifacts look a little like they have something to do with interlacing. You could try going into Settings->Core and Video Settings->ParaLLEl video and change the "Deinterlace mode". Besides that, I don't have any good suggestions.

**Comment by Manu270891** [comment]
> Ok, I don't know if I'll be able to be much help. Both the games you showed (Indiana Jones and Perfect Dark) use interlacing, and the artifacts look a little like they have something to do with interlacing. You could try going into Settings->Core and Video Settings->ParaLLEl video and change the "Deinterlace mode". Besides that, I don't have any good suggestions.

It's also happening on The Legend of Zelda: Ocarina of Time which I don't think it uses interlacing. I'll update this post if I discover the fix.

**Comment by thekovic** [comment]
What I noticed and found interesting on these screenshots, is that some of the polygons seem to be drawn out of order. You can see it on the very near walls to the left and right of the image. They appear to be rendered earlier than the wall that's partially covered by them. As if it's not being culled properly or something. The interlacing artifacts on the sky happen to be in places that would normally not be seen. I don't know how to possibly explain the near floor at the bottom of the image that's not being rendered properly though.

**Comment by Manu270891** [comment]
> Ok, I don't know if I'll be able to be much help. Both the games you showed (Indiana Jones and Perfect Dark) use interlacing, and the artifacts look a little like they have something to do with interlacing. You could try going into Settings->Core and Video Settings->ParaLLEl video and change the "Deinterlace mode". Besides that, I don't have any good suggestions.

So, I enabled the logging feature on RetroArch to see what's happening. This is the error it shows: "This device probably does not support 8/16-bit storage".
I tried running Parallel-RDP on my Android devices (Google Pixel 5 and Samsung Galaxy Tab S7+, both with Adreno GPUs) without any success. I know that Parallel-RDP doesn't work on my Android devices because it requires the "VK_KHR_8bit_storage" and "VK_KHR_16bit_storage" Vulkan extensions implemented in the GPU drivers. Adreno GPUs still don't have the "VK_KHR_8bit_storage" extension implemented in their drivers ([paraLLEl N64 RDP – Android support and Intel iGPU improvements – What you should know (and what to expect)](https://www.libretro.com/index.php/parallel-n64-rdp-android-support-and-intel-igpu-improvements-what-you-should-know-and-what-to-expect/))
So, apparently, Intel Xe GPUs don't have one or both of these extensions implemented in their GPU drivers.

**Comment by loganmc10** [comment]
Sort of odd, I have a Surface Pro (Intel HD 620 graphics), and although upscaling is really slow, it works on both Windows and Linux without any glitches.

**Comment by Manu270891** [comment]
> Sort of odd, I have a Surface Pro (Intel HD 620 graphics), and although upscaling is really slow, it works on both Windows and Linux without any glitches.

I updated my previous answer, the Intel Iris Xe G7 does support those extensions. I checked it using [VK-Z](http://www.geeks3d.com/vkz/)

**Comment by loganmc10** [comment]
Can you try this build: https://github.com/loganmc10/m64p/suites/3076934538/artifacts/70159228

You'll need to unzip it twice (that's just how GitHub Actions uploads them), and ignore the auto update message

**Comment by Manu270891** [comment]
> Can you try this build: https://github.com/loganmc10/m64p/suites/3076934538/artifacts/70159228
> 
> You'll need to unzip it twice (that's just how GitHub Actions uploads them), and ignore the auto update message

I managed to find why this is happening. Apparently, [beta drivers](https://downloadcenter.intel.com/en/download/30522/) cause this graphical glitches. Using the [stable drivers](https://downloadcenter.intel.com/en/download/30381/) fixes this issue, even Parallel-RDP on RetroArch works!

**Comment by loganmc10** [comment]
ok very cool, good to hear!
