### ISSUE TITLE
Lots of random screen flickering in San Francisco Rush

### ISSUE THREAD

**Issue by Kombatologist** [loganmc10/m64p#186]
**Describe the bug**
Lots of screen flickering during gameplay.

**To Reproduce**
Play the game. Very obvious. 

Video of gameplay here: https://youtu.be/MXwqQaaMhSw

**Desktop (please complete the following information):**

    OS: Windows
    Version: 10
    CPU: Ryzen 7 3800X
    GPU: RX 590

Additional context:
I have R4300Emulator enabled and Upscaling set to 2, though it also occurs while using the default settings. 

Appears to be identical to this closed GLideN64 issue from 2015, except we're not using GLideN64 anymore 
(I also did a complete race on Rush 2 and California Speed and they seem to run fine): https://github.com/gonetz/GLideN64/issues/373

**Comment by loganmc10** [comment]
Fixed in latest release: https://github.com/loganmc10/m64p/releases/tag/v2021.6.23
