### ISSUE TITLE
A small suggestion regarding the location of m64p log files

### ISSUE THREAD

**Issue by RokkumanX** [loganmc10/m64p#188]
This is not an issue per se, but I have noticed over the years that every time you use m64p there is files created in C:\Users\username\AppData\Local\Temp

Until earlier this week when I decided to open one of them with Notepad ++ I never knew what they were for.

After a while they can really start to pile up and before you know it there is a lot of them.

Would it be possible to store these in a logs folder in the m64p directory instead of the Temp folder in Windows?

I know you have a strict policy regarding requests, but this would make it easier to control all the log files having them in a logs folder instead.

Thank you very much for everything you have done!

**Comment by loganmc10** [comment]
I noticed this the other day actually and I think it should be fixed in the latest release 

Can you try deleting them all and then launching the emulator a few times? It shouldn't be making those files anymore

**Comment by RokkumanX** [comment]
Will do it right now, I'll be right back!

**Comment by RokkumanX** [comment]
Hey what do you know, they are actually not created anymore and the Temp folder is clean like a whistle.

I'm so happy right now, thanks man!
