### ISSUE TITLE
[ERROR]: Failed to create Vulkan device. + crash to terminal

### ISSUE THREAD

**Issue by freq-mod** [loganmc10/m64p#189]
**Describe the bug**
As of latest release, I can't use the program. Upon starting, in the terminal output `[ERROR]: Failed to create Vulkan device.` can be seen. The program starts however, but when loading the ROM, it crashes (segmentation fault?).

**To Reproduce**
1. run `./mupen64plus-gui`
2. open any ROM file
3. See error

**Expected behavior**
The game should run, I guess... Tested with 3 ROM files (SM64, Mario Kart, Donkey Kong 64)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - GPU: Intel HD 3000

**Comment by loganmc10** [comment]
Intel HD 3000 does not support Vulkan 1.1, which is now required by m64p:
![image](https://user-images.githubusercontent.com/848146/123275192-58e34c80-d4c1-11eb-9264-9b5086edc367.png)

If you'd still like to use GLideN64 (the old gfx plugin), you can download that version here: https://github.com/loganmc10/m64p/releases/tag/v2021.5.30
