### ISSUE TITLE
DInput missing diagonal on d-pad

### ISSUE THREAD

**Issue by quattj** [loganmc10/m64p#19]
Me again.  My brother is playing Mischief Makers using the Wii Classic controllers.

My config is as listed in the previous issue (#14).

The input plugin is not registering diagonal inputs with the dinput controls.  Up, Down, Left, and Right all work as expected, but pressing diagonally does not produce input.  It's particularly noticeable in level 3-7 Snowstorm Maze, but he had a feeling something was up earlier in the game.
It does work with the NRage plugin in Project64.

My other control (WiiU Pro) using the xinput wireless Mayflash adapter can produce diagonal input in Mupen64Plus.

**Comment by loganmc10** [comment]
Thanks for the report, I just published a release that should hopefully contain a fix for this issue:

https://github.com/loganmc10/m64p/releases/tag/April232020

**Comment by quattj** [comment]
Thanks for the super quick fix.  After a couple of glitches (I copied the new install over the old, so I think it needed to iron itself out) the d-pad is now working properly.
