### ISSUE TITLE
Missing dependencies in readme for fedora

### ISSUE THREAD

**Issue by LisandraBrave** [loganmc10/m64p#192]
The list of dependencies in the readme is incomplete. At the very least, `hidapi-devel nasm SDL2_net-devel` needs to be installed as well as the listed. Also related, `qmake` is apparently not shipped by default with that name, instead going by `qmake-qt5`

**Comment by loganmc10** [comment]
That list of dependencies is for running the program, not compiling it. I don't currently have a list of dependencies for compiling written anywhere
