### ISSUE TITLE
m64p does not build on ppc64le

### ISSUE THREAD

**Issue by anengineer1** [loganmc10/m64p#194]
**Describe the bug**
The program doesn't build

**To Reproduce**
Just do a ./build.sh on a ppc64le machine

**Expected behavior**
That the program builds

**Screenshots**
`Interprocedural optimizations enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yamira/software/m64p/parallel-rsp/build
Consolidate compiler generated dependencies of target lightning
[ 42%] Built target lightning
Consolidate compiler generated dependencies of target mupen64plus-rsp-parallel
[ 47%] Building CXX object CMakeFiles/mupen64plus-rsp-parallel.dir/parallel.cpp.o
In file included from /home/yamira/software/m64p/parallel-rsp/arch/simd/rsp/rsp_common.h:25,
                 from /home/yamira/software/m64p/parallel-rsp/state.hpp:4,
                 from /home/yamira/software/m64p/parallel-rsp/rsp_op.hpp:4,
                 from /home/yamira/software/m64p/parallel-rsp/rsp_jit.hpp:11,
                 from /home/yamira/software/m64p/parallel-rsp/parallel.cpp:4:
/usr/lib/gcc/powerpc64le-linux-gnu/10.2/include/emmintrin.h:56:2: error: #error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
   56 | #error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
      |  ^~~~~
In file included from /usr/lib/gcc/powerpc64le-linux-gnu/10.2/include/emmintrin.h:66,
                 from /home/yamira/software/m64p/parallel-rsp/arch/simd/rsp/rsp_common.h:25,
                 from /home/yamira/software/m64p/parallel-rsp/state.hpp:4,
                 from /home/yamira/software/m64p/parallel-rsp/rsp_op.hpp:4,
                 from /home/yamira/software/m64p/parallel-rsp/rsp_jit.hpp:11,
                 from /home/yamira/software/m64p/parallel-rsp/parallel.cpp:4:
/usr/lib/gcc/powerpc64le-linux-gnu/10.2/include/xmmintrin.h:54:2: error: #error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
   54 | #error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
      |  ^~~~~
In file included from /usr/lib/gcc/powerpc64le-linux-gnu/10.2/include/xmmintrin.h:79,
                 from /usr/lib/gcc/powerpc64le-linux-gnu/10.2/include/emmintrin.h:66,
                 from /home/yamira/software/m64p/parallel-rsp/arch/simd/rsp/rsp_common.h:25,
                 from /home/yamira/software/m64p/parallel-rsp/state.hpp:4,
                 from /home/yamira/software/m64p/parallel-rsp/rsp_op.hpp:4,
                 from /home/yamira/software/m64p/parallel-rsp/rsp_jit.hpp:11,
                 from /home/yamira/software/m64p/parallel-rsp/parallel.cpp:4:
/usr/lib/gcc/powerpc64le-linux-gnu/10.2/include/mmintrin.h:52:2: error: #error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
   52 | #error "Please read comment above.  Use -DNO_WARN_X86_INTRINSICS to disable this error."
      |  ^~~~~
/home/yamira/software/m64p/parallel-rsp/parallel.cpp:22:6: warning: 'void DebugMessage(int, const char*, ...)' defined but not used [-Wunused-function]
   22 | void DebugMessage(int level, const char *message, ...)
      |      ^~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/mupen64plus-rsp-parallel.dir/build.make:76: CMakeFiles/mupen64plus-rsp-parallel.dir/parallel.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/mupen64plus-rsp-parallel.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2`

![image](https://user-images.githubusercontent.com/52609000/123953375-70ca3d00-d9a7-11eb-8dbd-8e5c223e745d.png)

**Desktop (please complete the following information):**
 - OS: Void GNU/Linux
 - Version: Rolling release
 - GPU: Vega 64
 - CPU: POWER9
 - Arch: ppc64le

**Comment by loganmc10** [comment]
As noted at the top of your screenshot, this architecture is not officially supported
