### ISSUE TITLE
Mupen64Plus not starting (Linux)

### ISSUE THREAD

**Issue by X4X5** [loganmc10/m64p#195]
**Describe the bug**
After installing dependencies on Linux, I try to open mupen64plus, but it never opens.

**To Reproduce**

**Expected behavior**

**Screenshots**
`(xenial)x4x5@localhost:~/Downloads/mupen64plus$ ./mupen64plus-gui
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)`

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 16.04 (I had a different Linux computer before with the same version, and it worked)
 - GPU: ?

**Additional context**

**Comment by loganmc10** [comment]
Ubuntu 16.04 is end of life and not supported. The binaries provided in the release are compiled on Ubuntu 20.04, although it would probably work if you compiled it yourself on 18.04
