### ISSUE TITLE
Corrupted Screenshots?

### ISSUE THREAD

**Issue by delta7890** [loganmc10/m64p#196]
![starfox64-001](https://user-images.githubusercontent.com/34465681/124364479-cf91ef80-dc0f-11eb-8950-36dc6608355a.png)
Screenshots taken with the June 23rd 2021 build are coming out...well, like so.  Quite peculiar.  Using the new dynarec and parallel.

**Comment by Jj0YzL5nvJ** [comment]
gonetz/GLideN64#119
ata4/angrylion-rdp-plus#89
#111
#134

**Comment by loganmc10** [comment]
Should be fixed in https://github.com/loganmc10/m64p/releases/tag/v2021.7.5, please reopen if the issue persists
