### ISSUE TITLE
Individual game video settings not being used

### ISSUE THREAD

**Issue by quattj** [loganmc10/m64p#20]
In the versions that I've used prior to last night's release (April 23) I could change widescreen, anti-aliasing, etc per game.  With the newest version, video changes are being applied globally, even though the "Per Game" option is selected.  So, for example, Donkey Kong 64 and Mario Kart 64 look good with "Try To Adjust Game To Fit" as widescreen games, whereas Mischief Makers is awful with this option set.  I now can not set them individually, and must toggle the option when starting each game.

**Comment by cascardian** [comment]
With a fresh installation, I can't see the option for individual game profiles when starting them.

**Comment by loganmc10** [comment]
Yes this was an oversight on my part, I'll fix in the next release. Just keep in mind that the custom.ini file that stores these per game settings is now stored in the exe folder, not AppData, so it'll be overwritten on a new install unless you copy your old one over

**Comment by loganmc10** [comment]
Ok this should be fixed in the latest release:

https://github.com/loganmc10/m64p/releases/tag/Apr272020

**Comment by quattj** [comment]
Seems to be good.  I did have to re-save my settings for it to work.  Even though "4:3" was set in the individual game, the global was "try to fit" and it used this until I changed it in the game and changed it back to 4:3 and then re-saved.

**Comment by loganmc10** [comment]
Yes the GlideN64.custom.ini file is now stored in the same folder as the exe, so it'll get reset on a new install unless you copy the old one over

I did this because that gliden64.custom.ini has important settings for some games, and is sometimes has important updates in new releases
