### ISSUE TITLE
Perfect Dark - Lens Flare bug

### ISSUE THREAD

**Issue by DaRkL3AD3R** [loganmc10/m64p#200]
**Describe the bug**
When looking at lens flare sources that are positioned on the left side of the screen, the lens flares themselves become glitched and repeat in a long horizontal pattern across the screen. If the source moves to the right side of the screen, this issue does not present.

**To Reproduce**
1. Start the game and access the Carrington Institute
2. Enter the second floor hall and look through the windows at the sun (you may need to crouch)
3. Turn the camera left and right and look for the lens flare bug

**Expected behavior**
Lens flare should look consistent no matter the angle

**Screenshots**
https://imgur.com/a/VyGS0Fw

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version: 21H1 19043.1081
 - GPU: Nvidia 1080 Ti drivers 471.11

**Additional context**
Running latest builds of Mupen64Plus-Gui with ParaLLEl-RDP. 1x scaling resolution, all default settings.

**Comment by DaRkL3AD3R** [comment]
Just a small update to this issue I discovered: the issue only presents itself if the in-game option for Hi-Res is enabled. If you turn it off, the bug disappears.

**Comment by RokkumanX** [comment]
Yeah Hi-Res have caused it's share of issues and is known to be a trouble maker even in the past, I frankly haven't used it in Perfect Dark in eons.

As long as the game doesn't depend on it I stick with OFF, the game doesn't look that bad with regular and it's not one would miss much with it ON, I mean you doesn't magically get 1080p Full HD.

**Comment by loganmc10** [comment]
This is almost certainly a bug with the graphics plugin, can you please file the issue here: https://github.com/Themaister/parallel-rdp/issues ?
