### ISSUE TITLE
Use a menu to set plugins

### ISSUE THREAD

**Issue by anonymous7002** [loganmc10/m64p#201]
I know you're trying to reduce the complexity and provide a simple emulator for everyone.

But in fact, you're intensively oversimplifying the emulator so much it actually becomes increasingly complex to do anything more complex than configuring the controls. Not sure if we can soon even configure the controls. Currently I have to change the filenames to use other plugins and resort to modifying incomplete parameters through a config file after GLideN64 and Angrylion were replaced with paraLLEl-RDP. 

I believe the latest master/main commit prevents the use of video plugins other than paraLLEl! Why would you do this, don't fix it if it ain't broken!

So would you mind if my first request was for you to add a simple menu to set the plugins, like Project64 and RMG do? That will drastically reduce the complexity significantly.

-- Lordlouckster

**Comment by loganmc10** [comment]
There are lots of good options if you're looking for an emulator that supports plugins. As you've mentioned, there is Projec64 and RMG. There is also RetroArch (mupen64plus-next) which supports GLideN64, Parallel, and I think even Angrylion.

m64p isn't going to support plugins except where necessary (for instance, the raphnet raw input plugin is still needed since the regular input plugin doesn't support raw input)

**Comment by RokkumanX** [comment]
@anonymous7002  @loganmc10 

Unfortunately the doors to RMG have been shut and the project have been archived which could only mean the project is dead at this point.

RMG was a breath of fresh air for Mupen64Plus and you could change plugins just like Project64, now that isn't an option anymore and the developer have abandoned the project.

With recent changes made to m64p the door to change plugins have also been shut which is devastating.

Project64 is what it is but Mupen64Plus have always been the better option.

Now we have to rely on Frankenstein builds yet again enable to use cxd4, angrylion-rdp-plus etc. in m64p.

Again, it's your project but I honestly don't see the gain in nerfing m64p just for ParaLLEl when you could let people choose between different plugins and have more options available.

N64 emulation is so fragile and emulators left for using is scarce, don't let this emulator become locked for one set of plugins.
cxd4 RSP, angrylion-rdp-plus still have it's uses, heck even the mupen64plus-audio-sdl plugin does.

Please reconsider this, you got nothing to lose letting people choose plugins.

**Comment by anonymous7002** [comment]
I opened a fork called Sneed64, originally made to revert this nerfing.

**Comment by weinerschnitzel** [comment]
Logan, I also hope you reconsider. I dug out a lappy of mine to test recent changes to GLideN64 and was a bit disappointed that I was locked into using parallel-rdp. I would be much happier with an "advanced items" or "expert mode" check box to allow plugin selection, with the defaults set so a novice user does not get lost.
