### ISSUE TITLE
Indiana Jones stuck on black screen after legal logos

### ISSUE THREAD

**Issue by thekovic** [loganmc10/m64p#202]
**Describe the bug**
Game is stuck with a black screen (no sound) after the first screen with legal info + whether Expansion Pak is used or not when using new dynarec (game launches fine with R4300 Emulator = 1)

**To Reproduce**
1. Launch Indiana Jones and the Infernal Machine

**Expected behavior**
Getting to menu

**Screenshots**
Last screen that works:
![image](https://user-images.githubusercontent.com/72971433/125941670-e29bcb34-a2c9-49da-ba91-b7c1f877a499.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: 1050Ti
 - CPU: i5-8300H

**Additional content:**
Game worked fine before July 13th release so must be a regression of some kind

**Comment by thekovic** [comment]
I tested build https://github.com/loganmc10/m64p/commit/921c27d02d9299fbe385e350d2dd6d60b0947899 which includes the latest fix for the dynarec from https://github.com/mupen64plus/mupen64plus-core/pull/887 and the issue is fixed with that.

**Comment by loganmc10** [comment]
Fixed in https://github.com/loganmc10/m64p/releases/tag/v2021.7.19
