### ISSUE TITLE
Dinosaur Planet crashes when loading a new game

### ISSUE THREAD

**Issue by vini1264** [loganmc10/m64p#204]
Dinosaur Planet loads fine on the emulator and the menu works fine, but when i start a new game or try to load a save it just crashes and the emulator exits without any error warning. It worked fine on a previous version.

**Comment by loganmc10** [comment]
Yes this seems to be a bug with the dynamic recomplier. You can get around it by going into Core and Video Settings->Core, and set "R4300Emulator" to 1. I'll file a bug with mupen64plus-core

**Comment by loganmc10** [comment]
Fixed in latest release https://github.com/loganmc10/m64p/releases/tag/v2021.7.27
