### ISSUE TITLE
Mismatch between plugin header in m64p and upstream Mupen64Plus

### ISSUE THREAD

**Issue by amatho** [loganmc10/m64p#206]
The `CONTROL` struct in [`mupen64plus-core/src/api/m64p_plugin.h`](https://github.com/loganmc10/m64p/blob/91f899f5d92d67d93ffc80af918a507bcf9f572d/mupen64plus-core/src/api/m64p_plugin.h#L147) in m64p has an extra field (`Type`) compared to upstream Mupen64Plus. The `CONTROL_INFO` struct contains a pointer to an array of `CONTROL`s, which now has a different memory layout. This caused a bug in my input plugin (which uses the upstream headers) when paired with a recent enough m64p release. Please consider fixing this, as it's basically impossible to work around while maintaining compatibility with regular Mupen64Plus.

**Comment by loganmc10** [comment]
m64p doesn't always follow upstream exactly. It's also not made to support different kinds of plugins (besides what is included).

Closing as "won't fix"

**Comment by amatho** [comment]
Btw, I think your changes in core don't comply with GPLv2, since you haven't stated your changes. I would recommend putting a notice in the source files in order to comply with the license.

**Comment by loganmc10** [comment]
The only changes are a PR that hasn't been merged into the upstream repo yet: https://github.com/mupen64plus/mupen64plus-core/pull/873

**Comment by amatho** [comment]
Ah I see, my bad.
