### ISSUE TITLE
No sound after first run

### ISSUE THREAD

**Issue by prietveld** [loganmc10/m64p#208]
In older releases of m64p I had sound the first time I started the emulator, but no sound at all in any subsequent runs. I used to be able to remedy the issue by deleting mupen64plus-gui.ini and starting the emulator again, but in recent versions this no longer works, and I only had sound the very first time I ran the emulator:

Versions I tried:

- Oct252020: Sound only works after first run, subsequent runs only after deleting mupen64plus-gui.ini prior to starting.
- v2021.5.30 & v2021.7.27: Sound only worked the very first time, haven't been able to get it working again.

OS: Window 7 64 bits

**Comment by loganmc10** [comment]
Windows 7 is not supported. You'll have to update your OS

**Comment by prietveld** [comment]
Fair enough, hadn't seen that in the requirements.
