### ISSUE TITLE
M64P crashes for me when starting roms

### ISSUE THREAD

**Issue by Jerey71** [loganmc10/m64p#209]
**Describe the bug**
As stated in the title, whenever I go to start a rom, m64p will attempt to load it, but crash soon after.

**To Reproduce**
1. Open mupen64plus-gui
2. Go to file option
3. Click Open ROM
4. Choose ROM, then press open
5. See error

**Expected behavior**
For the rom to run

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: Nvidia RTX 3060 Laptop

**Additional context**
Tested with 3 separate games. Mario 64 (zipped and unzipped), Conker's Bad Fur Day (zipped), and Smash (unzipped). This also seems to be an issue with the more recent versions, as a previous version from the 21st of May worked fine.

**Comment by loganmc10** [comment]
Can you try this:
https://nvidia.custhelp.com/app/answers/detail/a_id/5182

It seems like your computer is not detecting Vulkan support, which is now required by m64p

**Comment by Jerey71** [comment]
Sure I'll try that rn

**Comment by Jerey71** [comment]
I followed all the instructions in the link you gave me but they didn't work. It seems to be a problem with my AMD intergrated graphics card. When i have my computer set to choose whichever one it wants it always crashes, but when i force it to use my nvidia gpu it works fine. Would there be anyway to get my integrated graphics card to recognize vulkan or do i just have to use my nvidia one

**Comment by loganmc10** [comment]
You'd have to use the Nvidia one, it's likely that the integrated card doesn't support Vulkan, or at least doesn't support all the required Vulkan extensions.

**Comment by Jerey71** [comment]
Alright understood. Thanks for the help
