### ISSUE TITLE
Texture enhancement options don't work for April 9th and 23th releases

### ISSUE THREAD

**Issue by cascardian** [loganmc10/m64p#21]
The options tab is also gone. The settings are still created in the file, but they do nothing. The April 1st release works as expected. Also the only release to still copy the GLideN64.custom.ini file to the specified config folder if that has any significance.

**Comment by loganmc10** [comment]
Yes, texture enhancements and HD textures are no longer supported. The custom.ini is now stored and read in the game folder so that users get the newest version when they install an update

**Comment by cascardian** [comment]
Ah, I should have checked the closed issues, since it was already brought up. I apologise. Maybe a quick note in the releases section or in README.md should prevent further confusion?

Thank you for all your hard work.
