### ISSUE TITLE
Doesn't run on Ubuntu 18.04

### ISSUE THREAD

**Issue by MegaMech** [loganmc10/m64p#211]
`/usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version Qt_5.12' not found (required by ./mupen64plus-gui)`

```
apt-file search libQt5Gui.so.5
libqt5gui5: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
libqt5gui5: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.9
libqt5gui5: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.9.5
```

I tried installing 5.12. But it didn't appear to actually install.

Also, does the Vulkan renderer work in W8.1 and W7?

**Comment by loganmc10** [comment]
Minimum OS is Ubuntu 20.04 or Windows 10

**Comment by MegaMech** [comment]
Is it possible to add support for previous versions? We're considering using your fork for an online multiplayer mod of mk64. I don't think we could use this repo if it lacks support. I think some of the plugins here is desired, do you know if any of those could transfer relatively easily to the stock repo?

**Comment by MegaMech** [comment]
Also, in another issue, you said the fork would likely work on ubuntu 18. Could that older version still work?

**Comment by loganmc10** [comment]
Everything is open source so you're free to fork and modify the code as you please. However this project is provided "as-is"

m64p already includes built-in netplay, so you can play mk64 online already using this emulator

**Comment by MegaMech** [comment]
netplay is not a reliable form of networking. I'm developing an actual synced networked mod of mk64 using the decomp. github.com/n64decomp/mk64

**Comment by loganmc10** [comment]
Looks interesting, hopefully the code in this project can be of use. Closing as the original question was answered.

**Comment by MegaMech** [comment]
What part of the repo doesn't support w8 and w7? Is it the renderer? Vulkan claims to support those systems I could possibly do a PR to add support for them. Unless there's other dependencies as well that don't work on those.

**Comment by loganmc10** [comment]
Sorry I don't know the answer to that question

**Comment by MegaMech** [comment]
@loganmc10 The repo does in-fact support Windows 8.1 and Windows 7. Just had to update my AMD driver to `Adrenalin-2020-Edition-20.9.2-Sep29` (Well... I didn't actually try w7 but I'm using a w7 driver in w8.1 so...)

**Comment by loganmc10** [comment]
Most people tell me the audio doesn't work in Windows 7
