### ISSUE TITLE
Unable to build on Ubuntu 20.

### ISSUE THREAD

**Issue by jaoxford** [loganmc10/m64p#213]
**Describe the bug**
Unable to build on Ubuntu 20

**To Reproduce**
1. Download the libraries outlined in README for Ubuntu 20
2. Attempt to build, get various errors, install additional libraries: zlib, libpng, nasm
3. Follow the build instructions. 

**Expected behavior**
The project to build

**Screenshots**
![m64p_not_buildign_sdl_error](https://user-images.githubusercontent.com/26263928/133937506-ac2119a9-3da3-458b-8b0a-944e9e6f6dcc.png)

**Desktop :**
 - OS: Ubuntu
 - Version: [e.g. 10]
 - GPU: Nvidia RTX 2060

**Comment by loganmc10** [comment]
You are missing dependencies, run this command:

https://github.com/loganmc10/m64p/blob/778e4ecdd9df6909f3d4ed13f4c9618c8a18a67a/.github/workflows/build.yml#L17

**Comment by jaoxford** [comment]
Thanks a lot

**Comment by loganmc10** [comment]
It is a bit unclear, but the readme lists the dependencies needed to run the official binaries, not to compile from source
