### ISSUE TITLE
Emulator Crashes on Launch

### ISSUE THREAD

**Issue by Krutonium** [loganmc10/m64p#214]
**Describe the bug**
Same as #209

**To Reproduce**
1. Open Emulator
2. Open Rom
3. Crash

**Expected behavior**
Game Loads and Plays

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: AMD RX 5600 XT / GTX 750 Ti

**Additional context**
Appears to be identical issue to #209

**Comment by loganmc10** [comment]
If it's identical to https://github.com/loganmc10/m64p/issues/209, did the workaround described in that issue allow the game to launch?

**Comment by Krutonium** [comment]
I don't have AMD Switchable Graphics - This is a Desktop PC with an AMD GPU and an nVidia GPU.

**Comment by loganmc10** [comment]
Can you try this:

https://www.howtogeek.com/351522/how-to-choose-which-gpu-a-game-uses-on-windows-10/

To select the nVidia GPU for mupen64plus-gui?

**Comment by Krutonium** [comment]
In this case the AMD is the ideal GPU. That said, that menu doesn't work on my system, because it's not set up for it - The nVidia GPU is just for compute.

**Comment by Krutonium** [comment]
![pref](https://user-images.githubusercontent.com/3945538/134598346-7ecaad60-2ffe-4514-a214-df642c5e4ebd.PNG)

**Comment by loganmc10** [comment]
The only thing I can suggest is updating your GFX drivers if you haven't. Usually this happens because the required vulkan extensions aren't supported

**Comment by Krutonium** [comment]
Both of them are running the latest available drivers. 

NVidia: 472.12
AMD: 21.8.2

Could you perhaps send me a debug build so I can give you a crash log?

**Comment by loganmc10** [comment]
If you run mupen64plus-gui.exe inside a bash shell (you can get bash by downloading Git for Windows) it should output details about the gfx plugin to the console, that would likely tell you why it's not launching

**Comment by Krutonium** [comment]
```
pfckr@DESKTOP-FDPMRDU MINGW64 ~/Downloads/mupen64plus
$ ./mupen64plus-gui.exe
[INFO]: Layer count: 7
[INFO]: Found layer: VK_LAYER_NV_optimus.
[INFO]: Found layer: VK_LAYER_AMD_switchable_graphics.
[INFO]: Found layer: VK_LAYER_OBS_HOOK.
[INFO]: Found layer: VK_LAYER_RTSS.
[INFO]: Found layer: VK_LAYER_VALVE_steam_overlay.
[INFO]: Found layer: VK_LAYER_VALVE_steam_fossilize.
[INFO]: Found layer: VK_LAYER_ROCKSTAR_GAMES_social_club.
[INFO]: Enabling instance extension: VK_KHR_get_physical_device_properties2.
[INFO]: Enabling instance extension: VK_KHR_external_memory_capabilities.
[INFO]: Enabling instance extension: VK_KHR_external_semaphore_capabilities.
[INFO]: Enabling instance extension: VK_EXT_debug_utils.
[INFO]: Found Vulkan GPU: AMD Radeon RX 5600 XT
[INFO]:     API: 1.2.182
[INFO]:     Driver: 2.0.193
[INFO]: Found Vulkan GPU: NVIDIA GeForce GTX 750 Ti
[INFO]:     API: 1.2.175
[INFO]:     Driver: 472.48.0
[INFO]: Selected Vulkan GPU: AMD Radeon RX 5600 XT
[INFO]: GPU supports Vulkan 1.1.
[INFO]: Enabling device extension: VK_KHR_get_memory_requirements2.
[INFO]: Enabling device extension: VK_KHR_dedicated_allocation.
[INFO]: Enabling device extension: VK_KHR_image_format_list.
[INFO]: Enabling device extension: VK_KHR_sampler_mirror_clamp_to_edge.
[INFO]: Enabling device extension: VK_KHR_external_semaphore.
[INFO]: Enabling device extension: VK_KHR_external_memory.
[INFO]: Enabling device extension: VK_KHR_external_semaphore_win32.
[INFO]: Enabling device extension: VK_KHR_external_memory_win32.
[INFO]: Enabling device extension: VK_KHR_descriptor_update_template.
[INFO]: Enabling device extension: VK_KHR_maintenance1.
[INFO]: Enabling device extension: VK_KHR_maintenance2.
[INFO]: Enabling device extension: VK_KHR_maintenance3.
[INFO]: Enabling device extension: VK_KHR_bind_memory2.
[INFO]: Enabling device extension: VK_KHR_draw_indirect_count.
[INFO]: Enabling device extension: VK_KHR_shader_draw_parameters.
[INFO]: Enabling device extension: VK_EXT_calibrated_timestamps.
[INFO]: Enabling device extension: VK_KHR_storage_buffer_storage_class.
[INFO]: Enabling device extension: VK_EXT_conservative_rasterization.
[INFO]: Enabling device extension: VK_KHR_8bit_storage.
[INFO]: Enabling device extension: VK_KHR_16bit_storage.
[INFO]: Enabling device extension: VK_KHR_shader_float16_int8.
[INFO]: Enabling device extension: VK_KHR_multiview.
[INFO]: Enabling device extension: VK_EXT_subgroup_size_control.
[INFO]: Enabling device extension: VK_EXT_host_query_reset.
[INFO]: Enabling device extension: VK_EXT_shader_demote_to_helper_invocation.
[INFO]: Enabling device extension: VK_EXT_scalar_block_layout.
[INFO]: Enabling device extension: VK_KHR_uniform_buffer_standard_layout.
[INFO]: Enabling device extension: VK_KHR_timeline_semaphore.
[INFO]: Enabling device extension: VK_KHR_sampler_ycbcr_conversion.
[INFO]: Enabling device extension: VK_EXT_memory_priority.
[INFO]: Enabling device extension: VK_EXT_memory_budget.
[INFO]: Enabling device extension: VK_KHR_synchronization2.
[INFO]: Enabling device extension: VK_EXT_external_memory_host.
[INFO]: Enabling device extension: VK_KHR_driver_properties.
[WARN]: Current proprietary AMD driver is known to be buggy with 8/16-bit integer arithmetic, disabling support for time being.
Segmentation fault
```

**Comment by loganmc10** [comment]
That all looks pretty normal actually. Does it happen with every game?

Also, did you extract the zip? I don't think it works if you try to launch the exe from the zip. I assume you did if you got that output though

**Comment by Krutonium** [comment]
Yeah it's extracted, and yeah - I tried running Majora's Mask, Master Quest for said, and Quake64.

I don't know if it's relevant, but before the segfault there's around a second from the previous line of output.

**Comment by loganmc10** [comment]
Can you try the latest version? There have been some updates to the graphics plugin

**Comment by earthcrafterman** [comment]
Same issue

`
$ ./mupen64plus-gui.exe
[INFO]: Layer count: 9
[INFO]: Found layer: VK_LAYER_NV_optimus.
[INFO]: Found layer: VK_LAYER_AMD_switchable_graphics.
[INFO]: Found layer: GalaxyOverlayVkLayer.
[INFO]: Found layer: GalaxyOverlayVkLayer_VERBOSE.
[INFO]: Found layer: GalaxyOverlayVkLayer_DEBUG.
[INFO]: Found layer: VK_LAYER_OW_OVERLAY.
[INFO]: Found layer: VK_LAYER_OW_OBS_HOOK.
[INFO]: Found layer: VK_LAYER_VALVE_steam_overlay.
[INFO]: Found layer: VK_LAYER_VALVE_steam_fossilize.
[INFO]: Enabling instance extension: VK_KHR_get_physical_device_properties2.
[INFO]: Enabling instance extension: VK_KHR_external_memory_capabilities.
[INFO]: Enabling instance extension: VK_KHR_external_semaphore_capabilities.
[INFO]: Enabling instance extension: VK_EXT_debug_utils.
[INFO]: Found Vulkan GPU: GeForce RTX 3060 Laptop GPU
[INFO]:     API: 1.2.155
[INFO]:     Driver: 462.52.0
[INFO]: Found Vulkan GPU: AMD Radeon(TM) Graphics
[INFO]:     API: 1.2.150
[INFO]:     Driver: 2.0.155
[INFO]: Selected Vulkan GPU: GeForce RTX 3060 Laptop GPU
[INFO]: GPU supports Vulkan 1.1.
[INFO]: Enabling device extension: VK_KHR_get_memory_requirements2.
[INFO]: Enabling device extension: VK_KHR_dedicated_allocation.
[INFO]: Enabling device extension: VK_KHR_image_format_list.
[INFO]: Enabling device extension: VK_KHR_sampler_mirror_clamp_to_edge.
[INFO]: Enabling device extension: VK_KHR_external_semaphore.
[INFO]: Enabling device extension: VK_KHR_external_memory.
[INFO]: Enabling device extension: VK_KHR_external_semaphore_win32.
[INFO]: Enabling device extension: VK_KHR_external_memory_win32.
[INFO]: Enabling device extension: VK_KHR_descriptor_update_template.
[INFO]: Enabling device extension: VK_KHR_maintenance1.
[INFO]: Enabling device extension: VK_KHR_maintenance2.
[INFO]: Enabling device extension: VK_KHR_maintenance3.
[INFO]: Enabling device extension: VK_KHR_bind_memory2.
[INFO]: Enabling device extension: VK_KHR_draw_indirect_count.
[INFO]: Enabling device extension: VK_KHR_shader_draw_parameters.
[INFO]: Enabling device extension: VK_EXT_calibrated_timestamps.
[INFO]: Enabling device extension: VK_KHR_storage_buffer_storage_class.
[INFO]: Enabling device extension: VK_EXT_conservative_rasterization.
[INFO]: Enabling device extension: VK_KHR_8bit_storage.
[INFO]: Enabling device extension: VK_KHR_16bit_storage.
[INFO]: Enabling device extension: VK_KHR_shader_float16_int8.
[INFO]: Enabling device extension: VK_KHR_multiview.
[INFO]: Enabling device extension: VK_EXT_subgroup_size_control.
[INFO]: Enabling device extension: VK_NV_compute_shader_derivatives.
[INFO]: Enabling device extension: VK_EXT_host_query_reset.
[INFO]: Enabling device extension: VK_EXT_shader_demote_to_helper_invocation.
[INFO]: Enabling device extension: VK_EXT_scalar_block_layout.
[INFO]: Enabling device extension: VK_KHR_uniform_buffer_standard_layout.
[INFO]: Enabling device extension: VK_KHR_timeline_semaphore.
[INFO]: Enabling device extension: VK_KHR_sampler_ycbcr_conversion.
[INFO]: Enabling device extension: VK_EXT_memory_priority.
[INFO]: Enabling device extension: VK_EXT_memory_budget.
[INFO]: Enabling device extension: VK_EXT_external_memory_host.
[INFO]: Enabling device extension: VK_KHR_driver_properties.
[WARN]: Current NVIDIA driver is known to be slightly faster without 8/16-bit integer arithmetic.
Segmentation fault
`

**Comment by earthcrafterman** [comment]
Fixed by setting the graphics driver manually in graphics settings under display under windows settings

**Comment by RealALCoL** [comment]
Hi, i just d/l last mp64win, it open but when i load a rom nothing happens, Video Error: Could not start GFX plugin Core Status: Rom closed., lil help is needed, thanks for ur kind support
W10 x64 radeon AMD

**Comment by RealALCoL** [comment]
> > Hi, i just d/l last mp64win, it open but when i load a rom nothing happens, Video Error: Could not start GFX plugin Core Status: Rom closed., lil help is needed, thanks for ur kind support W10 x64 radeon AMD
> 
> That error means your GPU doesn't support the Vulkan features that are required. You can try updating your GFX drivers, but often it means your GPU is too old to run m64p

yeah its true, damn thanks anyway, have to stay with ugly pj64
