### ISSUE TITLE
Sound Issues

### ISSUE THREAD

**Issue by SySy233** [loganmc10/m64p#216]
Hi there

Would it be able to fix the sound or have a new plugin such as Wasapi, XAudio2 as there is major crackling in Goldeneye 007 & Killer Instinct Gold?

Thanks

**Comment by loganmc10** [comment]
Do you have any upscaling applied to the video? Usually this is the result of poor performance

**Comment by SySy233** [comment]
Upscaling is set to 1 (None). It's only on the Menu screens on Goldeneye007 & Killer Instinct Gold as the rest of the gameplay is flawless 60.

**Comment by SySy233** [comment]
I've fixed the issue by updating my AMD drivers :-))
