### ISSUE TITLE
Black screen when upscaling on Intel UHD 620

### ISSUE THREAD

**Issue by Kieran-Weaver** [loganmc10/m64p#217]
**Describe the bug**
The ParaLLEl plugin works fine on my laptop's nvidia MX150 when upscaling, but when I try the same settings (upscale = 2) on the Intel UHD 620, the game doesn't start.

**To Reproduce**
In the core and video settings, set Upscaling to 2, ScreenWidth to 1280, and ScreenHeight to 960. Launch the Paper Mario Black Pit Mod (version 1.3.3).

**Expected behavior**
The game starts and the title screen is shown.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - GPU: Intel UHD 620

**Comment by loganmc10** [comment]
How much RAM does your computer have? Upscaling requires quite a bit of video memory, which would be shared when using an integrated GPU

**Comment by Kieran-Weaver** [comment]
It has 8 GB of RAM total, of which windows says 1 GB is allocated to the integrated GPU. Task manager says m64p is using 530 MB of memory.

**Comment by loganmc10** [comment]
> It has 8 GB of RAM total, of which windows says 1 GB is allocated to the integrated GPU. Task manager says m64p is using 530 MB of memory.

This is probably your issue, if the integrated GPU only has 1GB RAM available to it, it probably doesn't have enough to run upscaling. Upscaling uses a lot of GPU memory
