### ISSUE TITLE
Impish Indiri support

### ISSUE THREAD

**Issue by X4X5** [loganmc10/m64p#218]
**Describe the bug**
I have just recently updated by Ubuntu to 21.10, which did release yesterday, admittedly. I went to install the dependencies for Mupen64Plus on Linux, but the dependencies wouldn't install. Only after I removed `qt5-default` did the command work on the README. Is there a way to get qt5 installed so I can use the emulator?

**To Reproduce**
On Impish Indiri, type `sudo apt install qt5-default`

**Expected behavior**
This dialogue
`Package qt5-default is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source`

**Screenshots**
![Screenshot from 2021-10-07 13-46-45](https://user-images.githubusercontent.com/50627538/136448804-244d6d9a-9973-4669-93dc-c1a6b7199c74.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Version: 21.10 (Impish Indiri)
 - GPU: Mesa Intel® UHD Graphics 600 (GLK 2)

**Comment by Jj0YzL5nvJ** [comment]
```
sudo apt-get update
apt-cache search qt5 | grep -i development
apt list | grep -i qt5
```
