### ISSUE TITLE
XInput Rumble Does Not Work

### ISSUE THREAD

**Issue by mattdog1000000** [loganmc10/m64p#220]
Rumble does not work in v2021.10.28 or v2021.10.27.
(It does work in v2021.10.11, though -- but that netplay is no longer supported.)

**To Reproduce**
1. Create a profile using an xinput device (any xbox 360, xbox one, or series X/S controller).
2. Use the newly created profile under Controller 1 in the Controller Configuration.
3. Use the xinput device for the Gamepad under Controller 1 in the Controller Configuration.
4. Use Rumble for the Pak in the Controller Configuration.
5. Play any game which supports rumble.
6. Notice there is no rumble.

**Expected behavior**
Rumble should occur.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11
 - GPU: Radeon RX580

**Additional context**
I was testing the new Nintendo Switch N64 Controller via BetterJoy -- if rumble could be natively supported without the need for BetterJoy that would be even nicer :)

**Comment by mattdog1000000** [comment]
It is easy to work around this issue by replacing SDL2.dll with the one included in v2021.10.11. :)

**Comment by loganmc10** [comment]
Fixed in latest release
