### ISSUE TITLE
Rom Crashes on Launch

### ISSUE THREAD

**Issue by joeconner121** [loganmc10/m64p#221]
Describe the bug
Same as #214 

To Reproduce

Open Emulator
Load Rom
Immediate Crash

Expected behavior
Game Loads Up

Screenshots

Desktop (please complete the following information):

    OS: Windows
    Version: 11
    GPU: AMD Ryzen 7 5800H with Radeon Graphics / NVIDIA GeForce RTX 3050 Ti Laptop GPU

Additional context
Appears to be identical issue to #214

**Comment by loganmc10** [comment]
Duplicate of #214
