### ISSUE TITLE
Games wont run- Boot - Win7

### ISSUE THREAD

**Issue by oddsito** [loganmc10/m64p#229]
**Describe the bug**
In the website it says " its simple , unzip and play " and so i did... but nothing ever starts or run... it just stays stuck and then if i try to load a rom again the software crashes and windows demands for it to be closed.

**To Reproduce**
1. Go to 'File --> Open ROM --> Majoras Mask (US) -- and the game will not boot/run -- nothing.

**Expected behavior**
I wanted the game to run 

**Screenshots**
It just stays in a white screen. I deleted the app now.  This happened on the 2 most recent versions.

**Desktop (please complete the following information):**
 - OS: [Windows 7 Ultimate
 - GPU: [Amd HD 8400]

**Additional context**

**Comment by loganmc10** [comment]
Windows 7 isn't supported unfortunately

**Comment by oddsito** [comment]
Thank you for the swift reply ... Thank you very much

**Comment by Jj0YzL5nvJ** [comment]
With that GPU it wouldn't work even with Windows 10 (no `VK_KHR_8bit_storage`)
