### ISSUE TITLE
m64p is using an outdated version of the video plugin

### ISSUE THREAD

**Issue by zant0** [loganmc10/m64p#23]
According to the log m64p is using GLideN64 v2.0.0. This version has graphic bugs even in popular games like Super Mario 64. The current version of the plugin is 4.0. (https://github.com/gonetz/GLideN64/releases/tag/Public_Release_4_0)
Downloading it and replacing it with the up to date version solves the graphic bugs. The downside is that the menu under Setting -> Video Settings isn't working anymore.

**Comment by loganmc10** [comment]
You can ignore that v2.0.0, it isn't accurate, this package using the latest version of GLideN64 from the git master (even newer than Public Release 4.0). If you notice a gfx bug, you can report it here:

https://github.com/gonetz/GLideN64
