### ISSUE TITLE
Error when using helper scripts 

### ISSUE THREAD

**Issue by drnjo** [loganmc10/m64p#231]
These scripts (https://github.com/mupen64plus/mupen64plus-core/raw/master/tools/m64p_helper_scripts.tar.gz 
(found them here: https://mupen64plus.org/wiki/index.php/CompilingFromGit)) are doing sth and then give these Errors:
`UI-Console Error: dlopen('/usr/local/lib/libmupen64plus.so.2') failed: /usr/local/lib/libmupen64plus.so.2: cannot open shared object file: No such file or directory
UI-Console Error: AttachCoreLib() Error: Emulator core '(null)' incompatible; Config API version 2.3.0 doesn't match application: 2.3.1`

**Comment by loganmc10** [comment]
Sorry the use of "m64p" for this project can be a little confusing, those helper scripts are meant for the upstream mupen64plus project, which you can download here: https://github.com/mupen64plus/mupen64plus-core/releases

They aren't meant for use with this project, which is sort of a "distribution" of mupen64plus
