### ISSUE TITLE
Any possibilities to port Mupen64Plus-QT GUI to m64p?

### ISSUE THREAD

**Issue by erudes91** [loganmc10/m64p#234]
Hello @loganmc10 @joeldenning @nanaian 

I was wondering if there's any way the GUI used here on the following project to be ported to this one.

https://github.com/dh4/mupen64plus-qt

I tried replacing files but that's not enough as the Parallel plugin used on this beautiful build is incompatible with the before hand mentioned project.

Any words on that?

**Comment by loganmc10** [comment]
No sorry, I don't have any plans to work on this
