### ISSUE TITLE
Feature Request: Updating from the software and a GUI suggestion

### ISSUE THREAD

**Issue by NovaStorm64** [loganmc10/m64p#24]
Hey,
I know this isn't an issue, but I saw that, unlike Project64, this emulator is updated frequently so switched to this. But the fact that I have to keep on checking GitHub for new releases is somewhat tiring, so I would greatly appreciate an update button in the settings drop-down menu.

As for the GUI, Is there no way to set a default ROM directory? And a nice Dolphin Grid or PJ64 style menu would make the program more accessible.

Finally, Discord integration ( ͡° ͜ʖ ͡°)
Anyways, keep up the great work!

**Comment by loganmc10** [comment]
The default ROM directory is set to the last directory you grab a ROM from, is that not working for you?

The other things probably won't happen for a long time, I'm currently working on netplay, which will take a very long time still

**Comment by loganmc10** [comment]
And by the way, GitHub should let you subscribe to releases, so you get an email everytime there is a new release

**Comment by NovaStorm64** [comment]
No, after playing Banjo-Tooie multipl;e time's I'm still getting a blank screen at startup.
And thanks for the tip, I used the method of adding .atom to the releases URL bar to add it to an RSS feed.
Looking forward to that netplay release!

**Comment by loganmc10** [comment]
Sorry I don't mean it'll show your ROMs on the main screen. But when you go to open a ROM it should remember the folder you browsed to last time

**Comment by loganmc10** [comment]
FYI, an auto updater is next on my todo list. I don't have any plans to add a ROM grid or discord integration 

(The discord integration is still a maybe, but I don't have any immediate plans to work on that)

**Comment by loganmc10** [comment]
Closing this since auto update is released: https://github.com/loganmc10/m64p/releases/tag/Oct262020

The other 2 I'm going to close as a "wont fix"

**Comment by loganmc10** [comment]
FYI Discord support added: https://github.com/loganmc10/m64p/releases/tag/Oct292020
