### ISSUE TITLE
Mapping two individual buttons to the same input

### ISSUE THREAD

**Issue by NicholasNRG** [loganmc10/m64p#25]
In the previously used input plugin I could have a particular input mapped to two different buttons, for example I could map C-Button Up to both the Y button and Up on the Right-Stick, so I could use either buttons for that input in particular. I can't find a way to do this in the new input plugin. Also there doesn't seem to be an InputAutoCfg.ini which I found was highly convenient and useful for globally modifying a specific type of controller.

**Comment by loganmc10** [comment]
Yes there is no more InputAutoCfg.ini, but you can make a profile and attach that to any controller.

As for a secondary input mapping, yes hopefully one day I can get around to adding that, probably won't be soon though

**Comment by NicholasNRG** [comment]
It would be nice to have the option to revert to the previous input plugin in the mean time, which I find is much more friendly for a plug and play type experience. With this new plugin I can't even figure out how to map the buttons for my N64 controller with a Mayflash SS/N64/PS2 adapter. It just doesn't receive any input from it at all on the New Profile windows. Yet I can use it in-game, with forced 100% range (the controller only reaches to about 50% range) and mismapped buttons. This is the only thing keeping me from using the new builds. I just use the February 25, 2020 build and overwrite the video, audio and rsp .dll's with those from new builds. I'm missing out on netplay yo :(

**Comment by Exequiel3k** [comment]
I agree with Nicholas, if you could please add back as an alternative the previous input handler method as I'm stuck on that build as well because of other issues (https://github.com/loganmc10/m64p/issues/12). It would great be appreciated

**Comment by thekovic** [comment]
Reinforcing the desire for binding multiple controller buttons to one input. I love your emulator but until this is added, I will have to use a different emulator which supports a plugin (input-sdl) that allows this.

**Comment by loganmc10** [comment]
Closing all feature requests, I will accept PRs for these kinds of things but the work isn't directed based on feature requets.
