### ISSUE TITLE
RE2 trouble.

### ISSUE THREAD

**Issue by Piloto40** [loganmc10/m64p#27]
In Resident Evil 2 the characters are disappearing.

**Comment by loganmc10** [comment]
Can you please post your OS and graphics card?

**Comment by Piloto40** [comment]
Windows 10 Pro and GeForce GTX 1070 TI.

**Comment by ulfman** [comment]
I have the same Problem.

System :
Windows 7 64-Bit Ultimate
Nvidia GTX 660

**Comment by Piloto40** [comment]
Fixed
