### ISSUE TITLE
Can't open video settings after replacing GlideN64 by new version

### ISSUE THREAD

**Issue by OtavioRaposo** [loganmc10/m64p#28]
Is this normal? I manually updated the video plugin after 03b404bd Sergey posted today.

**Comment by OtavioRaposo** [comment]
The games are working fine (shading problem solved).

**Comment by loganmc10** [comment]
Yeah no you can't do that, the video settings will only work if you use the version distributed with this package

**Comment by loganmc10** [comment]
I've put out a new release that contains those fixes though: https://github.com/loganmc10/m64p/releases/tag/may42020

**Comment by OtavioRaposo** [comment]
Very thanks. Much welcome.

**Comment by OtavioRaposo** [comment]
Are you sure? I'm having the shader issues again.

**Comment by loganmc10** [comment]
You might want to try deleting your shader cache, if you are on Windows that is here:

C:\Users\%user%\AppData\Roaming\Mupen64Plus\shaders

But yes, that release contains fixes in GLideN64 up to the latest commit, which was about 5 hours ago

**Comment by OtavioRaposo** [comment]
Yeah. Did that. Working like a charm. Thanks again.
