### ISSUE TITLE
Paper Mario issue

### ISSUE THREAD

**Issue by lucarreguy** [loganmc10/m64p#30]
I'm new here, and I don't know much English (I'm Brazilian)
I was testing my games, and in Paper Mario happens this
![image](https://user-images.githubusercontent.com/64933181/81236456-a5c14680-8fd3-11ea-8a9b-c8fe2e7a11b6.png)

There's a way to solve this?

**Comment by heckez-sys** [comment]
idk = i dont know ikr = i know right n1 = no one and stuff if u want to know slang 
u = you

**Comment by lucarreguy** [comment]
> nice to find a paper mario fan

This game is very good, but every time I play in this new version of the emulator, this screen happens. I'm not using cheats, I just want to play :)

**Comment by loganmc10** [comment]
At what point in the game does this happen?

**Comment by lucarreguy** [comment]
> At what point in the game does this happen?

I play for 5 minutes and happens. Initially, I thought it was because I played in other version of the emulator and the save file was carried. But I started a new game and happened too, in the cutscene of Peach and Mario talking in the Castle
ps: again, sorry for the bad english

**Comment by loganmc10** [comment]
Do you have any customized video settings? I know I've seen this happen when some of the gliden64 framebuffer settings are modified

**Comment by loganmc10** [comment]
Closing for lack of response, please reopen if needed
