### ISSUE TITLE
GUI crashes after stopping emulation and loading another game

### ISSUE THREAD

**Issue by bernhard263** [loganmc10/m64p#31]
Hello,

my problem is that the GUI crashes whenever I load a game, stop playing, then load a second game.

Steps to recreate the issue:
-Load a game
-Press ESC to stop emulation
-Load any other game

The application will crash without any message. Please let me know if you can recreate this issue or if it's just me. Also, is there is any debug or log message I could post here to help tracking down the problem?

On a side note, I wanted to file this bug in the mupen64plus-gui project as suggested on https://m64p.github.io , but the link there seems to be broken, so I had to post it here.

**Comment by loganmc10** [comment]
Thanks, what OS are you using?

**Comment by bernhard263** [comment]
I'm using Windows 10 64-bit, 4 GB RAM, Intel m3-7Y30.
What's weird is that I just tried it again and the issue is gone for now. I've had it randomly appear and disappear over the last few days. For a certain period, It either always works or always crashes. I will observe if it has something to do with RAM usage. I have another PC (desktop) that I will also test it on later.

**Comment by loganmc10** [comment]
I think I've made improvements that should fix this issue. Please reopen if it persists with the latest version
