### ISSUE TITLE
Wipeout 64: 2-d issue

### ISSUE THREAD

**Issue by Petersilientroll** [loganmc10/m64p#33]
2-d elements are only colorful bars (ntsc- and pal-version). :'(

os: windows 10 pro (x64)

graphic card: RTX 2060S

**Comment by loganmc10** [comment]
I can't reproduce, can you try the latest version? If it's still happening can you post a screenshot and point out the issue?

**Comment by Petersilientroll** [comment]
Thanks, the graphical issues are fixed in the netplay beta release (051820). :-)

 
 

Gesendet: Freitag, 05. Juni 2020 um 16:45 Uhr
Von: "Logan" <notifications@github.com>
An: "loganmc10/m64p" <m64p@noreply.github.com>
Cc: "Petersilientroll" <petersilientroll@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [loganmc10/m64p] Wipeout 64: 2-d issue (#33)


 

I can't reproduce, can you try the latest version? If it's still happening can you post a screenshot and point out the issue?
