### ISSUE TITLE
Netplay Issues

### ISSUE THREAD

**Issue by loganmc10** [loganmc10/m64p#35]
Issue tracker for netplay

1. GoldenEye desynced when testing
2. GoldenEye didn't start after sitting in the wait room for a while, looks like the players registered but then it froze. It did work when we tried it a second time (didn't sit in the wait room as long)

**Comment by sodomon2** [comment]
Hello

I'm having trouble creating a multiplayer game, it seems to say there's no rom loaded and it doesn't give me a server to choose from, the server selector remains blank, maybe because I'm trying to host a game on a local network?

This is the error. 

![net](https://user-images.githubusercontent.com/49420637/82456792-af8e8380-9a82-11ea-9d9f-3455ab1d7e1d.png)

I'm using the version:

m64p-May182020

**Comment by loganmc10** [comment]
Is that computer connected to the Internet? It's a bit odd that the server list is blank, it gets that list by download a file off the Internet

Also, did you compile, or download the binary build?

**Comment by sodomon2** [comment]
> Is that computer connected to the Internet? It's a bit odd that the server list is blank, it gets that list by download a file off the Internet
> 
> Also, did you compile, or download the binary build?

if the computer is connected to the internet

I had to compile it

**Comment by sodomon2** [comment]
I also noticed that you download the server list via the Internet

maybe that's the problem? 🤔

**Comment by loganmc10** [comment]
Yes the computer needs to be connected to the Internet for netplay to work

**Comment by sodomon2** [comment]
but my PC is already connected to the internet

**Comment by sodomon2** [comment]
this should happen on the console?

QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://m64p.s3.amazonaws.com/servers.ini")

**Comment by loganmc10** [comment]
Because that link is an https link, you'll need libssl and libcrypto installed, I assumed they were installed on all linux distros, but you could double check that those are installed

**Comment by sodomon2** [comment]
I checked and it seems that if I have them installed the libssl and libcrypto libraries

**Comment by loganmc10** [comment]
Seems like it may be a bug with your Qt version: https://bugreports.qt.io/browse/QTBUG-72463

**Comment by sodomon2** [comment]
my version of Qt is 5.12.0

**Comment by loganmc10** [comment]
Yes exactly, that bug (https://bugreports.qt.io/browse/QTBUG-72463) affects Qt 5.12.0, it is fixed in 5.12.2

**Comment by sodomon2** [comment]
in qt 5.12.2 is fixed?

**Comment by sodomon2** [comment]
there's no way to make it compatible with Qt 5.12.0?

**Comment by loganmc10** [comment]
No there is not

**Comment by sodomon2** [comment]
Hello

I've already updated qt, and I don't get the QNetworkReplyHttpImplPrivate::_q_startOperation error anymore

but now when I start the network game I get a segmentation fault

**Comment by loganmc10** [comment]
Can you try downloading the latest build again from the release page? I had to update it because there was an issue

**Comment by loganmc10** [comment]
The last release had a bug that caused a crash, I updated the binaries on the release page, so you'll have to either download those, or build the latest master

**Comment by sodomon2** [comment]
@loganmc10 I've compiled the latest master

https://github.com/loganmc10/m64p/commit/10910d73fe9d8ffda421c82202a9a58b2ffa9474

**Comment by loganmc10** [comment]
Is it still crashing? Are you able to post a backtrace?

**Comment by sodomon2** [comment]
Yeah, it's still crashing.

**Comment by loganmc10** [comment]
I'll need a backtrace, I don't think others are having this issue

**Comment by sodomon2** [comment]
maybe it's because I use thigh and not glibc?

**Comment by sodomon2** [comment]
@loganmc10  when I start the game I get the faul segmentation and this message

```
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 992, resource id: 9229020, major code: 40 (TranslateCoords), minor code: 0
```
