### ISSUE TITLE
windowed resolution resets

### ISSUE THREAD

**Issue by Max833** [loganmc10/m64p#38]
Hi! Great emulator. I have a lot of fun. Thanks for your work! :)

The only problem I have right now is that the windowed resolution resets as soon as I boot the game again. This means I always have to start the game, go to **Settings -> video settings -> click save and close** and _then_ the resolution changes (I use 1280 x 960). Seems like it doesn't maintain the defined resolution. I hope you can reproduce this.

**Edit:** There is one more thing: When I play majoras mask with my XBOX 360 controller the game enables always "Z" even though I don't press anything. Do you know what this could be?

**Comment by karai17** [comment]
This sounds similar to my issue where my "Z" trigger is activated when I am not pressing a button, and deactivates when I do press a button (#47). Perhaps this is an issue not with the keybindings, but the emulator's Z button itself?

**Comment by loganmc10** [comment]
@Max833 the controller issue should be fixed. Are you still having problems with the resolution?

When you have a game running, video settings changes apply only to that game. If you want global settings you need to apply them without any game running
