### ISSUE TITLE
Gamepad dropdown menu reverts to auto and controller doesn't work

### ISSUE THREAD

**Issue by mdueck** [loganmc10/m64p#39]
Using the controller configuration, I was able to create profiles for my two different types of controllers. And I can choose a specific gamepad for each of the Controller tabs so that all 4 of my controllers work perfectly in game. But the problem is that the controller tabs frequently revert the gamepad drop down menu back to auto. When this happens my controllers don't work until I again go into the controller configuration and choose one of the gamepads connected to my PC. I can't figure out when or why the gamepad choice reverts back to auto. Sometimes some controller tabs keep the chosen gamepad but other tabs don't. At other times they all revert back to auto. I'm very confused.

The four controllers I'm using are:

3 N64 replica controllers named
1:G-Shark GS-GP702
2:G-Shark GS-GP702
3:G-Shark GS-GP702

1 Xbox 360 controller with USB wireless adapter called 
0:XInput Controller

For anyone with the same issue, here is the **solution** as provided by ulfman:
1. Select the desired gamepads for each controller tab 
2. Change the "input-settings.ini" file to read only by right clicking it and going into properties. (see file location below)
3. The controller configuration will then always keep the specific gamepad selected (as long as its plugged in at least).

"input-settings.ini" file location:
Unless you changed the default Config Dir Path then you can find the "input-settings.ini" file under c:\Users\<USERNAME>\AppData\Roaming\Mupen64Plus\ 
(you will need to make hidden items visible in your USERNAME folder so that you can see the AppData folder)

**Comment by ulfman** [comment]
I had the same Problem.

write-protect the following File : "input-settings.ini"

**Comment by mdueck** [comment]
where is that file found?

I only have 3 .ini files in my main folder, see attached image. I don't see it in any of the other sub folders as well.

![image](https://user-images.githubusercontent.com/21231631/82596239-d4a2f500-9b5b-11ea-8873-306141f5f273.png)

**Comment by ulfman** [comment]
Then you dont changed your CONFIG-FILE Path.

The Default one is here located :
c:\Users\<USERNAME>\AppData\Roaming\Mupen64Plus\

**Comment by mdueck** [comment]
It works now! Thank you so much.
