### ISSUE TITLE
New Controller Plugin

### ISSUE THREAD

**Issue by loganmc10** [loganmc10/m64p#4]
I am currently working on re-writing the controller plugin, here are some screenshots:

![image](https://user-images.githubusercontent.com/848146/75620241-bb357280-5b43-11ea-9474-61077ab0eb1c.png)
![image](https://user-images.githubusercontent.com/848146/75620247-c25c8080-5b43-11ea-81fe-e9e7a94bf5f2.png)
![image](https://user-images.githubusercontent.com/848146/75620252-c9838e80-5b43-11ea-9fdf-23e6d828b797.png)

The idea is that for each controller (1-4) you'll be able to select a profile (Auto will be an option, which will give you typical defaults), you'll be able to select which gamepad is associated with each controller (Again there will be an "Auto" option that will assign gamepads automatically), and you can select a pak (memory, rumble, transfer, none)

Then the user will also be able to create controller profiles.

I'm open to any early feedback on the design. I anticipate this will take me 2-4 weeks to complete

**Comment by zmarotrix** [comment]
I was about to submit a bug report because keyboard bindings were not working correctly, but I guess I'll just wait for the next release. I'm really excited for a reasonable frontend for mupen.

**Comment by jaoxford** [comment]
Looks good!

**Comment by loganmc10** [comment]
I'm a little bit stuck at the moment, I'm hoping you guys can help me out. I don't have a controller right now that I can test. I've attached a build below.

Can you guys try it out and let me know if the controller works? If it does, can you do a bit of testing and let me know what is broken? I basically just wrote the controller code "blind", I might not have access to a USB controller that I can use for a little while

[m64p-win64-d79badc.zip](https://github.com/loganmc10/m64p/files/4289525/m64p-win64-d79badc.zip)
[m64p-linux64-d79badc.zip](https://github.com/loganmc10/m64p/files/4289527/m64p-linux64-d79badc.zip)

**Comment by jaoxford** [comment]
I was just about to have a look into this and I've noticed that the GUI script seems to be missing from the build folder?

![image](https://user-images.githubusercontent.com/26263928/75924866-9997fc00-5e5f-11ea-8e10-5cb2d2872945.png)

**Comment by loganmc10** [comment]
Yes good catch, fixed, here is the new linux build, windows build is still building, I'll post it in a bit:

[m64p-linux64-a865772.zip](https://github.com/loganmc10/m64p/files/4289881/m64p-linux64-a865772.zip)

**Comment by jaoxford** [comment]
The new controller setup seems to have both of the thumbsticks with the Y axis the wrong way around.

I've tried to make a new profile and map the controls manually, but they are still backwards.

**Comment by jaoxford** [comment]
![image](https://user-images.githubusercontent.com/26263928/75928723-eaf7b980-5e66-11ea-99b9-b95a0e317f6b.png)

**Comment by loganmc10** [comment]
You're assigning the profile to controller 1 correct?

I'll look into the inverted Y axis in a bit, thanks for testing

**Comment by jaoxford** [comment]
That's right, assigning the profile to controller #1.

**Comment by loganmc10** [comment]
Are the thumbsticks inverted when using them as C buttons?

I assumed that Up and Right were supposed to be positive axis values, but now my reading leads me to believe that Down and Right were positive on the N64.

**Comment by loganmc10** [comment]
Actually I guess I just misunderstood joysticks in general, down is positive. I'll fix that tonight

**Comment by loganmc10** [comment]
Can you double check the profile thing? Forget the axis for now, but maybe set the A and B buttons to be mapped differently and tell me if it honours your choice?

**Comment by jaoxford** [comment]
Just tried. No luck.

I'm assuming it's a problem with applying the profile to the controller?

![image](https://user-images.githubusercontent.com/26263928/75931205-51330b00-5e6c-11ea-81c6-21a1c72fb86e.png)


I've also noticed that the profiles don't get saved between sessions. So if I close the application, and reopen it. The profile doesn't get saved.

**Comment by loganmc10** [comment]
The profile saving thing is a bit odd. Can you look inside ```~/.config/mupen64plus``` is there anything in there? It seems like your computer can't save configurations

If for whatever reason that directory isn't writable, you can change the config directory here (Settings->Plugin and Path Selection):

![image](https://user-images.githubusercontent.com/848146/75938340-c12d9b00-5e44-11ea-860b-64d090e38bab.png)

Can you change "Config Dir Path" to somewhere you know it writable and restart mupen64plus-gui?

**Comment by loganmc10** [comment]
By the way, here is a new build that should hopefully have the inverted Y Axis fixed
[m64p-linux64-6d8c2cc.zip](https://github.com/loganmc10/m64p/files/4290482/m64p-linux64-6d8c2cc.zip)

**Comment by loganmc10** [comment]
I was able to get my hands on a controller and I think I was able to sort out most of the remaining issues, I've posted a release: https://github.com/loganmc10/m64p/releases/tag/Mar42020

@jaoxford I think your issues with the profile are unrelated, it seems like your config directory is probably not writable, so configurations aren't able to be saved

**Comment by jaoxford** [comment]
Awesome.

So what was happening is that the config dir path is left empty by default. Once I set that to something, the profile persists between sessions!

Would it not be preferable to set the default config directory to the same as the installation folder, so people don't make the same mistake that I did?

**Comment by loganmc10** [comment]
Many people prefer it outside the install directory, that way when they upgrade, they just delete their current folder, download the new one, and all their settings persist.

When it is empty (default), mupen64plus tries to find a good default using this function:
https://github.com/mupen64plus/mupen64plus-core/blob/77a2f8813251b5257382ec477c3f0ef3ea49c37f/src/osal/files_unix.c#L172

On most Linux system that ends up being ```~/.config/mupen64plus``` and on Windows it ends up being %APPDATA%\Roaming\Mupen64plus, I'm not sure why that isn't working on your system

**Comment by Piloto40** [comment]
there is no way to switch between memory pak or rumble pak with the game running?

**Comment by loganmc10** [comment]
Not currently no, I want to make sure things are bug free and then I'll work on that sort of thing

**Comment by loganmc10** [comment]
Closing this as the new input plugin has been released, and I haven't heard of any bugs. Any bugs related to the input plugin can be reported here:

https://github.com/m64p/mupen64plus-input-qt/issues

I added an issue for Pak switching, I hope to implement that in the near future
