### ISSUE TITLE
 Controller is failure  when a 60fps hack SM64 rom is run.

### ISSUE THREAD

**Issue by jlu511** [loganmc10/m64p#40]
I run a 60 fps hack rom of SM64. The rom is recognized as UNKNOWN ROM, but it can work. Only issue is that the controller is failure. No error can be seen. If i change to original SM64 rom, the controller is ok. Can you fix it?

**Comment by jlu511** [comment]
Whether I use a keyboard or a 360 controller
![图片1](https://user-images.githubusercontent.com/64378673/83228220-75c32880-a1b8-11ea-94aa-57b7e5e520b8.jpg)
![图片2](https://user-images.githubusercontent.com/64378673/83228233-7a87dc80-a1b8-11ea-86a6-d958bfb7b0e0.jpg)

**Comment by jlu511** [comment]
I cannot start game，any buttons is not work。

**Comment by loganmc10** [comment]
Does the ROM hack work on a real console? Only hacks that run on console are supported. Please reopen once you've confirmed it works on console
