### ISSUE TITLE
Angrylion-RDP-Plus and cxd4 RSP???

### ISSUE THREAD

**Issue by RokkumanX** [loganmc10/m64p#44]
Hi

Early early last year you could still use the Mupen64Plus version of the Angrylion-RDP-Plus plugin in m64p.

Then a lot of stuff started to happen and get in motion with the project, Patreon only and removal of cxd4 RSP and Angrylion-RDP-Plus.

While it is still possible to make so called Frankenstein builds using older m64p builds that supports angrylion and cxd4 it's not very practical and some things don't work as expected such as the ability to toggle fullscreen etc.

Will you ever consider bringing cxd4 and angrylion support back to m64p, sure I can understand that you took the road you did but for users wanting to use Mupen64Plus there isn't as great options using Project64 if you want cxd4 and angrylion.

m64p used to be a stable alternative back then for regular angrylion, cxd4 and Mupen64Plus updates and I hope it still can be one day again.

Thanks in advance!

**Comment by loganmc10** [comment]
Sorry, no plans for this, PJ64 or Retroarch (mupen-next core) are good options if you're looking for an LLE experience

**Comment by RokkumanX** [comment]
I kinda knew the answer would be something like that but I figured it was worth a shot asking.
Thanks!
