### ISSUE TITLE
Request: ESC exits full-screen without closing game

### ISSUE THREAD

**Issue by quattj** [loganmc10/m64p#46]
I'm used to hitting ESC in emulators to exit full screen (sometimes with a pop-up asking if I also want to quit the game in progress).  I do it in this emulator as well when I need to check something, and always forget that it will close the game, so I end up closing my games unintentionally quite often.  Any chance we can get an option to have it exit full-screen without ending emulation?

(I can't figure out how to add the ENHANCEMENT tag to the post)

**Comment by loganmc10** [comment]
Alt + Enter should toggle full screen for you

**Comment by quattj** [comment]
Yes, alt-enter works, but I always push ESC. It's a force of habit from years of emulation. It usually exits full screen or opens the menu in most other emulators. It would be handy if it didn't automatically quit the game :)

**Comment by karai17** [comment]
I think a more general request of "let users remap application hotkeys" could be good, instead of hard coding them all. I personally prefer using F11 as the fullscreen key but that doesn't work in this program.

**Comment by GhostlyDark** [comment]
You are able to change these with the old GUI editing mupen64plus.cfg in `%appdata%/mupen64plus/`
It's under **[CoreEvents]**.

Default config:
https://mupen64plus.org/wiki/index.php/KeyboardSetup

Keycodes:
http://www.libsdl.org/release/SDL-1.2.15/include/SDL_keysym.h

So "fixing" fullscreen would be:
```
# SDL keysym for stopping the emulator
Kbd Mapping Stop = ""
# SDL keysym for switching between fullscreen/windowed modes
Kbd Mapping Fullscreen = 27
```

"" disabling a hotkey entirely (so you don't stop the emulation accidentally), 27 is the Escape Key
