### ISSUE TITLE
GameCube Controller has an inverted axis.

### ISSUE THREAD

**Issue by karai17** [loganmc10/m64p#47]
When I use the official build of Mupen64Plus, my input seems to be fine. When I use the latest version of m64p, both the left and right shoulder triggers (I am trying to use one as my Z trigger) seem to be inverted and I have to hold them down to deactivate them, and let go to activate them.

I am using a GameCube controller via the Wii U adapter on Windows 10 x86_64.

**Comment by loganmc10** [comment]
You may need to make a custom controller profile. The auto profile isn't able to figure out the correct inputs 100% of the time

**Comment by karai17** [comment]
I am using a custom profile, not auto.

**Comment by karai17** [comment]
![image](https://user-images.githubusercontent.com/590332/85190670-da8e1200-b290-11ea-9840-9a3c7432d99e.png)

Above is my custom profile. You'll note that Z is assigned to Axis 2-, which is my L trigger. My assumption is that L- has a range of -1 to 0, and L+ (which does not exist) would have a range from 0 to 1. But because there is no L+ , perhaps L- has inverted thresholds or is the wrong range? I'm not really sure unless there is some way I can debug this. My first thought for a potential work around would be to add the ability to invert individual axes either via some checkbox or some other means? Let me know if there is anything I can do to provide more useful data.

**Comment by loganmc10** [comment]
Thanks I think I've been able to reproduce this, I'll try to work on a fix.

In the meantime, I think I workaround would be to hold down the trigger before clicking the button, and then release the trigger after clicking it, that should register the opposite axis direction and let you play

**Comment by karai17** [comment]
yup that work around does indeed work! thanks

**Comment by loganmc10** [comment]
I just put out a new release that should hopefully fix this issue:

https://github.com/loganmc10/m64p/releases/tag/June282020

Can you try and let me know?
