### ISSUE TITLE
Tony Hawks Pro Skater 1 A Button stops working

### ISSUE THREAD

**Issue by Kazmakistan** [loganmc10/m64p#48]
The A Button works on the various in game menus, however when I went to play the game, the A Button stopped working. I was unable to make my character jump. The bug does not seem to be present in Tony Hawks Pro Skater 2.

**Comment by loganmc10** [comment]
![image](https://user-images.githubusercontent.com/848146/85955936-51857380-b93f-11ea-9b4e-d612800a1e6d.png)

I believe this is just the control scheme of the game, C Down is jump.

See: https://www.gamesdatabase.org/Media/SYSTEM/Nintendo_N64//Manual/formated/Tony_Hawk-s_Pro_Skater_-_2000_-_Activision.pdf

**Comment by Kazmakistan** [comment]
Whoops. Feel real dumb now. Thank you!
