### ISSUE TITLE
Request : Add the ability to type in an IP to connect to a net-play server.

### ISSUE THREAD

**Issue by dara1429** [loganmc10/m64p#49]
I noticed that hosting a server on a VLAN, it will not show up in the server list when trying to host or join a room. I don't know if this is because the program only searches 192.x.x.x. ranges or what but it would be nice if you could add a simple text box to type in an IP and port directly so me and my friends can connect to the net-play server we hosted.

**Comment by loganmc10** [comment]
For locally hosted games, it uses multicast to advertise the server. This is similar to how a Chromecast advertises itself. Playing a locally hosted server with people on different LANs isn't supported, and likely won't be ever

**Comment by dara1429** [comment]
Thanks for the quick response. I think i should have clarified my situation and what I am requesting better. I put a copy of your net-play server on a friend's Ubuntu server that is connected to a VLAN that me and and a bunch of others are on. The problem is when you try and host or join a game, the server list only populates with the 3 servers that you are currently running yourself (The Europe one and the two US ones). Basically what I wanted to ask is the ability to manually put in the IP of a net-play server so that we can host and join games on the one we setup rather than the ones you are hosting.

I already know our server works over VLAN because I tested it by altering the source code for mupen64plus-gui and manually adding in the IP of the net-play server so that it shows up in the server list. I was then able to connect two laptops to our server and host a game successfully. I have included a screenshot below for clarity. 
![Untitled](https://user-images.githubusercontent.com/11980947/85939292-59a6ca00-b8d1-11ea-864e-a793a06787c7.png)

**Comment by loganmc10** [comment]
Understood, I'd be more interested in figuring out why the multicast discovery didn't work, rather than adding the ability to manually specify an IP address 

What kind of network is this? I assume it's not a house?

**Comment by dara1429** [comment]
All of us are on Internets at our house (including the server computer). To connect to each other though, we use Zerotier, a program that creates a virtual LAN network. When connected to the Zerotier network, games that have LAN server browsers or other LAN capabilities function as they would if everyone was connected to the same network at one house. 

Zerotier works by creating a network adapter and then when you join a network, it assigns an IP to you that acts as a LAN IP, allowing you to directly connect to others in the same network (as if you were in the same house). I'll attach a picture below to help clarify for you.
![Capture](https://user-images.githubusercontent.com/11980947/85953725-bdf87680-b92f-11ea-9caf-21e34191ff31.PNG)

I am not familiar with how multi-casting works so I don't have much of the way of figuring out why m64p can't see the server. If you need anything from me I am more than happy to help. Thank you so much for taking the time with this. I appreciate it.

**Comment by loganmc10** [comment]
Does zerotier itself have any settings you could post? The documentation on the website seems to say it supports multicast but it sounds like there are some settings to configure it?

**Comment by dara1429** [comment]
The majority of settings are on a web-page for the network. By default everything looks OK and multicast is enabled. Maybe something is missing?
![Capture](https://user-images.githubusercontent.com/11980947/85963149-8e6a5e00-b971-11ea-903b-fd96c20c5a17.PNG)

**Comment by loganmc10** [comment]
OK I think I understand the issue, it seems that Windows is probably sending the multicast traffic out the local interface, instead of the Zerotier interface.

I released a new build: https://github.com/loganmc10/m64p/releases/tag/June282020
I also updated the server, so please use the latest git master there.

I changed it use to Broadcast instead of Multicast, I'm hoping Windows is less picky about which interface it uses to send the broadcast in this case.

By the way though, you'd probably have a better experience just using one of the publicly available netplay servers, rather than using something like Zerotier, if you are playing with others over the Internet

**Comment by dara1429** [comment]
Looks like that did it. Out server showed up right away. Thank you so much!

**Comment by EFDos** [comment]
> For locally hosted games, it uses multicast to advertise the server. This is similar to how a Chromecast advertises itself. Playing a locally hosted server with people on different LANs isn't supported, and likely won't be ever

Hi! I'm curious, why is that not a feature you're planning to support?

Me and some friends in Brazil loved this project as a cross-platform solution to play N64 with Netplay, but currently there are no servers that will work for us without some considerable delay.
Even if I connect to one of the servers just by myself, the delay is bad enough to make games like Mario Kart too hard to control.

I think that the ability to type an IP and a Port, or the ability to add a Custom Server to the Server List would be really useful.
Kinda like how Dolphin allows you to use a Traversal Server or a Direct Connection to host your game.

**Comment by loganmc10** [comment]
Yes it would be technically possible, however my goal is to create a solution that is usable by everyone. There is a cloud region in Sao Paulo, Brazil that could be used to host a m64p netplay server.

My preference would be for people to donate at https://www.patreon.com/m64p so that we could host a South American netplay server that is usable by everyone

**Comment by EFDos** [comment]
> Yes it would be technically possible, however my goal is to create a solution that is usable by everyone. There is a cloud region in Sao Paulo, Brazil that could be used to host a m64p netplay server.
> 
> My preference would be for people to donate at https://www.patreon.com/m64p so that we could host a South American netplay server that is usable by everyone

That's awesome, I'll definitely donate!
Meanwhile I did a quick hack that allows me to do what I needed. If you have any interest on having that as a secondary feature I could polish and wrap it up to make a PR. 
Though most players (me included) will probably prefer to rely on the dedicated servers anyway.
