### ISSUE TITLE
Fullscreen behaviour not being honoured

### ISSUE THREAD

**Issue by jaoxford** [loganmc10/m64p#5]
When I enter fullscreen to play a game, and after playing for a few minutes (however long is dictated by my energy saving settings) with a controller, and not touching the mouse or the keyboard . The screen begins to dim.

What would ideally happen is that being fullscreen behaviour would ignore my OS settings.

Although, correct me if I'm wrong. But the fullscreen is a borderless window, even then it would ideally not dim and logout?

**Comment by loganmc10** [comment]
I pushed this fix:

https://github.com/m64p/mupen64plus-gui/commit/701973d2910ce5cc988526e247dee79d5f295e3b

Which should work for Windows. Are you using Windows or Linux?

Really it's kind of an OS problem, the OS should be registering gamepad usage as activity, or realize that there is an OpenGL window playing video, but I guess they aren't doing that.

**Comment by jaoxford** [comment]
Nice work!

I'm using Linux, specifically Manjaro KDE if that's any help.

**Comment by loganmc10** [comment]
That commit will only work for Windows, I'll need to spend some time looking into the best way to do it on Linux.

For building, you do this:
```
git clone --recursive https://github.com/loganmc10/m64p.git
cd m64p
./build.sh
```
When it compiles it may complain about missing libraries, you'll have to track down whatever is missing and install them, the process for that is different for every Linux distro

**Comment by jaoxford** [comment]
Just saw that you updated the README, beat me to making a PR for that! :)

**Comment by jaoxford** [comment]
The build ran fine without any issues by the way!

**Comment by loganmc10** [comment]
Just keep in mind that I'm currently working on the input plugin, so the current builds have a not quite finished version of that plugin. Keyboard input should work OK but probably not controllers yet

**Comment by loganmc10** [comment]
This should hopefully be fixed in Linux and WIndows in the build I posted on the controller thread, please let me know

**Comment by jaoxford** [comment]
The patch seems to have fixed the issue!
