### ISSUE TITLE
Trying to build just the GUI in Armv7 for Raspberry Pi 4

### ISSUE THREAD

**Issue by Inotamira** [loganmc10/m64p#50]
I'm getting fairly close, but it seems a few changes made recently are causing things to not compile correctly. I have a compiled Mupen64, and I'm trying to compile your GUI to go along with it. I am forced to use make -j 4 since nproc isn't something the compiler seems to understand and it's the best alternative I can seem to find.

https://pastebin.com/YPaMnxmy here is the output

**Comment by loganmc10** [comment]
The GUI can't be built independent of the rest of the package, it is a component of https://github.com/loganmc10/m64p, it's all meant to be built together

**Comment by Inotamira** [comment]
> The GUI can't be built independent of the rest of the package, it is a component of https://github.com/loganmc10/m64p, it's all meant to be built together

Well, mupen CAN be built for arm, it's just in a testing phase. Would the adjustments needed to build mupen work to build the rest of this, or would the same issues I'm already having arise?

**Comment by loganmc10** [comment]
I'm not 100% I understand what you mean. The only supported build method is the one mentioned in this repo, which is basically

git clone https://github.com/loganmc10/m64p
./build.sh

**Comment by Inotamira** [comment]
> I'm not 100% I understand what you mean. The only supported build method is the one mentioned in this repo, which is basically
> 
> git clone https://github.com/loganmc10/m64p
> ./build.sh

You can build mupen as described here https://www.raspberrypi.org/forums/viewtopic.php?t=246552 for the raspberry pi. Could that be applied to m64p, as it seems like all the dependencies are otherwise satisfied, or is there something else I'm not seeing?

**Comment by loganmc10** [comment]
m64p uses customized versions of mupen64plus-core and GLideN64, as well as its own audio and input plugins, so it's not just vanilla mupen64plus + a GUI.

You can look at the build script here: https://github.com/loganmc10/m64p/blob/master/build.sh and try to adapt it for a Raspberry Pi, that would be my best suggestion.
