### ISSUE TITLE
How do I use cheats?

### ISSUE THREAD

**Issue by StephanFS** [loganmc10/m64p#53]
I've been trying to use cheats, but eveytime I select Cheats, a blank window with nothing on it appears. How do I use it?

**Comment by Toadfield** [comment]
Did you try to start a game and then select cheats while it's running?
If I try to select cheats while no game is running then nothing will appear,but if I start a game and then slelect cheats,then it works.

**Comment by anonymous7002** [comment]
Where's the cheats menu?

**Comment by loganmc10** [comment]
The cheats menu was removed because it was really bad/didn't work well
