### ISSUE TITLE
Is there a way to add gameshark codes?

### ISSUE THREAD

**Issue by Toadfield** [loganmc10/m64p#56]
I want to use a 100% cheat for Mario Party 3,but if I look into the cheat option,I can't find one or an option to add cheat codes,so is that even possible?

**Comment by Toadfield** [comment]
I figured out that I can add Gameshark Codes in "~/usr/share/mupen64plus/mupencheat.txt"

**Comment by 64fanatic** [comment]
> I figured out that I can add Gameshark Codes in "~/usr/share/mupen64plus/mupencheat.txt"

how do you enable them in the text file?

**Comment by Toadfield** [comment]
I forgot how to do that.
I don't use M64P anymore,I use the Mupen64Plus-Next Core.
