### ISSUE TITLE
Shindou Wave Race crashes at Nintendo logo

### ISSUE THREAD

**Issue by gamer-gamer** [loganmc10/m64p#57]
Hello, I tried the newest and some previous versions, then I also tried using the different compiler and interpretor modes and the same thing.

**Comment by loganmc10** [comment]
It doesn't seem to crash for me, but it does hang. Setting "CountPerOp" to 3 in the Advanced Setting seems to fix it for me, can you confirm?

**Comment by gamer-gamer** [comment]
This did correct it, and yes, was more like a freeze and not a crash, although does this setting make a difference to accuracy ? Thanks

**Comment by loganmc10** [comment]
I've opened a PR in mupen64plus to make the setting the default for this game. Yes setting CountPerOp to 3 is somewhat like underclocking the CPU, so it's possible the game will run slower, but barring another fix, this is the only thing I can tell that makes the game playable at the moment
