### ISSUE TITLE
Support for custom memory paks and memory pak editor

### ISSUE THREAD

**Issue by AbandonedWitchStarlight** [loganmc10/m64p#58]
I would request support for custom memory paks and editing contents of MPK files, because M64P only supports one save pak per game, but the regular size of memory paks is limited to 256kb and almost MPK saves are empty when opened in the memory pak menu ingame, so I am requesting for that feature. This is common on the other emu - but not on Mupen64 or M64P.

**Comment by loganmc10** [comment]
No plans to add this. I believe there are external tools that can modify a MPK file, I don't think it needs to be included in the emulator
