### ISSUE TITLE
Frame drops when window is focused

### ISSUE THREAD

**Issue by James-Coyne** [loganmc10/m64p#6]
Using the latest version of m64p (9e36e5d) games start to drop frames while the window is focused. Clicking out of the window returns the framerate to normal. During this time the FPS and VI/s do not appear to go down according to the OSD nor are there any other indications of slowdown from the game itself, i.e. stuttering sound.

The previous version I was using was from Feb 19 (aff9457) and did not have this problem.

**Comment by loganmc10** [comment]
What OS are you using?

**Comment by James-Coyne** [comment]
Windows 10 1909.

**Comment by James-Coyne** [comment]
Issue may have been caused by Windows' Game Mode. Disabling it seems to have resolved the problem.
