### ISSUE TITLE
Portable Install / Relative Pathing

### ISSUE THREAD

**Issue by agrider** [loganmc10/m64p#60]
Is there any way in the windows version currently to do relative pathing? I have a launchbox setup on an external hard drive that I've taken great pains to build out as a go anywhere ultimate emulation station. All of my existing emulators have portable install options. It seems obviously that the windows version doesn't leverage the registry so it *could* be portable but when I try to set up paths to config, etc, I can't seem to get relative pathing to work. Am I missing something? If not, would this be something that could be added?

**Comment by loganmc10** [comment]
You can do relative pathing in the config options by manually typing ```./``` instead of using the file browser

**Comment by agrider** [comment]
I had done that but wasn't seeing configs written into the updated config path. It seems that changing the path itself doesn't trigger a write out of the existing config files over to the new dir, I had to update one of the config items before the write actually happened.
