### ISSUE TITLE
mupen64plus-gui DK64 - Severe Slowdown

### ISSUE THREAD

**Issue by Zageron** [loganmc10/m64p#61]
(This also happens to Conker, and both Banjos)
So Donkey Kong 64 USA runs at 17fps / VI with default settings in the intro, start screen, and in game.
Front matter and start menu run at 60fps / VI.

CPU and GPU are running at full power.
I've tried fiddling with every setting with no effect.
Any ideas?

Microsoft Windows 10 Pro
10.0.19041 Build 19041

Build:  Sept22020

![image](https://user-images.githubusercontent.com/1892473/92424998-c395e800-f13a-11ea-8c29-bd69f94a4ebf.png)
![image](https://user-images.githubusercontent.com/1892473/92425012-cf81aa00-f13a-11ea-8b60-bcca4a599cfa.png)

**Comment by quattj** [comment]
Do you have N64 style depth compare enabled?  This causes slowdown on certain NVidia cards.

**Comment by Zageron** [comment]
Unfortunately, I do not have this enabled. (I tried enabling it but saw no change in performance.)

**Comment by schmurtzm** [comment]
Just try with the last release, don't have any slowdown with gtx 970

**Comment by Zageron** [comment]
Tried, same crazy slow stutter. Must be something specific to my machine or config.

**Comment by soulwa** [comment]
Same issue, just downloaded latest mupen64plus build, had slowdown on DK Rap, title screen, and in-game. Haven't tested with other Rare games yet, but other N64 games are smooth. GPU is an NVIDIA 1050 Ti.

**Comment by Jj0YzL5nvJ** [comment]
> **CPU and GPU are running at full power.**
> I've tried fiddling with every setting with no effect.
> Any ideas?

Sounds like a typical NVIDIA's Optimus driver issue, but the "desktop variant". Try renaming `mupen64plus-gui.exe` to `bf3.exe` for check quickly.

**Comment by Zageron** [comment]
> 
> 
> > **CPU and GPU are running at full power.**
> > I've tried fiddling with every setting with no effect.
> > Any ideas?
> 
> Sounds like a typical NVIDIA's Optimus driver issue, but the "desktop variant". Try renaming `mupen64plus-gui.exe` to `bf3.exe` for check quickly.

Was a good idea, but unfortunately it didn't help. :P
DIscord did offer to stream battlefield 3 though.

**Comment by fedecorigliano** [comment]
Same problem here, slowdown in rap scene in Donkey Kong 64 USA, and the castle scene in the intro of Zelda OOT. AMD Ryzen 9 5900x, NVIDIA Geforce GTX 1660 Super. Windows 10 Pro 64-bit 20H2.

**Comment by Jj0YzL5nvJ** [comment]
Try with a **local user** profile (new local user account). NVIDIA setting can break games for spastic users and account setting synchronization is a real issue.

**Comment by Zageron** [comment]
![image](https://user-images.githubusercontent.com/1892473/108638900-67075a80-7446-11eb-9b5a-89ede6d90477.png)
![image](https://user-images.githubusercontent.com/1892473/108638903-6b337800-7446-11eb-8fa7-c43a7d820710.png)

**Comment by loganmc10** [comment]
Going to close this since we recently changed GFX plugins (no longer using GLideN64). Please open a new issue if this is still a problem with ParaLLEl-RDP
