### ISSUE TITLE
Input Latency issue

### ISSUE THREAD

**Issue by mcmull500** [loganmc10/m64p#62]
Is Ocarina of Time supposed to have latency? I know it runs at about 20FPS and I'm fine with that, but it seems that there is an inordinate amount of input latency.

I've never played the game before so I don't know how it feels on an actual N64. I've played through Mario 64 and it feels great, so I know it's not my controller.

If this is just how the N64 Zelda games are, so be it, that's fine. I just wanted a second opinion. If this is a stupid question, I'll delete it once someone answers. Thanks in advance, and I love this emulator!

**Comment by mcmull500** [comment]
I'm using almost all default settings except that I turned on vsync (because I needed it), turned off threaded, and put the internal resolution to 6x. I've messed around with a ton of settings trying to fix it but I'm at a loss.

**Comment by loganmc10** [comment]
Yes this is normal, and could be reproduced on a real console
