### ISSUE TITLE
No obvious way to assign mempak/rumble/etc toggle to button?

### ISSUE THREAD

**Issue by DangusTaargus** [loganmc10/m64p#63]
Is there a way to do this? For instance I'm using an Xbox One controller and I'd like to use the 'select' button to cycle through the mempack/rumble/transfer/none options in-game. 

This would be great to add as a feature, but if that's too much trouble, any way to just add this by hand to a config file that'd be ok too... just not sure how? I see references to mempak/rumble swap in the mupen64plus config file but when using the default input plugin I'm assuming this is bypassed?

Thanks!

**Comment by loganmc10** [comment]
Closing in favour of https://github.com/loganmc10/m64p/issues/106
