### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by inukaze** [loganmc10/m64p#66]
Hi there, is me again xD jajaja

1) On the Binary Precompile Windows version please include the files :

dnsapi.dll
liblzma-5.dll
libtiff-5.dll
libwebp-7.dll
libwebpdemux-2.dll
libwebpmux-3.dll
netapi32.dll

For make it can run out-the-box under Wine (because i can't start the native version, and i can't compile it under Slackware) i test using Wine-5.17 but the mupen64plus-gui.exe needs thats dll to run in the same folder of the mupen64plus-gui executable

2) The gui needs some improvements like in 

A) The controls, add the mouse support, right now i try to configure the mouse, but just had "keyboard" not "Mouse enable" option, well the official mupen64plus grab absolute analog stick, and i think that not should be, the user must customize the controls on games depends because the users comforts is not equal universally

B) The plugins, i don't notice where i can set another plugin for : rsp, audio, video, i just see is can be change the input plugin.

Dunno, this version include the "netplay-server" internally for create rooms? because i try to create a local room, but i just see on the "Server" appears 3 options [Europe (Paris), US East (Virginia), US West (Oregon)] , like if depends on internet, but i want to use just on Intranet without internet connection

The rest i think is awesome specilly the profile save in the video plugin, for years i ask if that can be included, because the N64 Games & PlayStation 1 Games, needs very specific configurations for works like in the console. 

Well thanks for read :)

**Comment by loganmc10** [comment]
1. I won't fix since Wine isn't supported. The emulator is cross platform.

2. A. Yes there is no mouse support, no plans to add it unless someone else does that work. B. Correct that plugins aren't configurable, m64p is meant to be used with the included plugins

The netplay server is a different project located here: https://github.com/loganmc10/m64p-netplay-server
