### ISSUE TITLE
Audio Lag when playing games?

### ISSUE THREAD

**Issue by OrisX** [loganmc10/m64p#67]
Whenever I try to play a game with M64P, I get about half a second worth of audio lag. Like, say I am playing Zelda and I pull up the shield, the sound for the shield won't play until half a second after I push the button. I'm not sure if it is an issue with the driver or a configuration thing I've screwed up.

**Comment by loganmc10** [comment]
The latest release: https://github.com/loganmc10/m64p/releases/tag/Oct122020 contains a potential fix for this. Can you try it out and let me know?

**Comment by loganmc10** [comment]
Closing, please reopen if it's still an issue
