### ISSUE TITLE
Castlevania 64 crash

### ISSUE THREAD

**Issue by JJ2670** [loganmc10/m64p#68]
The emulator crashes when I try to use the key to the Torture Chamber in the Castle Center. I use no cheats, and my settings are mostly default. I use Windows 10 if that helps.

**Comment by loganmc10** [comment]
Do you have a save state that could get me to this point so I can easily reproduce it?

**Comment by JJ2670** [comment]
[Castlevania.zip](https://github.com/loganmc10/m64p/files/5385369/Castlevania.zip)

Here it is. Will you be also needing the rom in question?

**Comment by loganmc10** [comment]
No this is perfect thanks

**Comment by loganmc10** [comment]
@JJ2670 sorry I've never played this game before, can you walk me through what I need to do to reproduce the issue once I've loaded the save state?

**Comment by loganmc10** [comment]
Actually I've got it figured out, I diagnosed the issue and reported it in GLideN64: https://github.com/gonetz/GLideN64/issues/2360 . I'm not exactly sure of the proper fix, but gonetz will figure that out soon enough.

**Comment by loganmc10** [comment]
Going to close this since it is an issue with gliden64 and it has now been reported there
