### ISSUE TITLE
Feature Request:Being able to add Gameshark Codes in a gui way

### ISSUE THREAD

**Issue by Toadfield** [loganmc10/m64p#69]
I found out how to add Gameshark Codes in a text file ( https://github.com/loganmc10/m64p/issues/56 ),but I would like it more if I could Just go to "Cheats" in M64P and being able to add cheats there for the game I'm playing (like with Project 64)

**Comment by AXDOOMER** [comment]
Would be great if it also worked in netplay, although I wonder if it should be possible to activate codes while the game is running.  Does Project 64 allow activating codes mid-game?
