### ISSUE TITLE
Problems with trying to run a rom hack

### ISSUE THREAD

**Issue by deopdeop** [loganmc10/m64p#7]
When I try to play sm64 romhacks every time m64p just crashes. I would love to try out romhacks for sm64 on m64p.

**Comment by loganmc10** [comment]
mupen64plus aims to mimic the behavior of a real N64, many SM64 ROM hacks were designed to run with Project64 and don't actually run on a real N64.

If there is a ROM hack that runs on actual hardware I can look into it, but I would need a specific ROM that was verified.

**Comment by deopdeop** [comment]
Does mupen64plus work with rom's that are expanded

**Comment by loganmc10** [comment]
It's not really about the size. For instance, there is a Goldeneye ROM hack called Goldfinger that has completely redesigned levels, it works on a real N64 and mupen64plus as well.

I don't know much about how the SM64 ROM hacks were created, but they do a number of things that aren't compatible with a real N64, but happen to work with Project64

**Comment by jlu511** [comment]
I run a 60 fps hack rom of SM64. The rom is recognized as UNKNOWN ROM, but it can work. Only issue is that the controller is failure. No error can be seen. If i change to original SM64 rom, the controller is ok. Can you fix it?
