### ISSUE TITLE
Crashes after checking and unchecking cheats

### ISSUE THREAD

**Issue by Toadfield** [loganmc10/m64p#70]
If I check and uncheck cheats to often it crashes.
Btw is that because of M64P or because of the Mupen 64 core?

**Comment by Toadfield** [comment]
Why did you close it?

**Comment by loganmc10** [comment]
Cheat support was removed from the GUI, the cheat interface wasn't very good. Unless someone rewrites a new cheat interface this is no longer relevant

**Comment by Toadfield** [comment]
ok.
Are you currently working on a new cheat interface?

**Comment by loganmc10** [comment]
No I'm not, someone else would need to take that on.

**Comment by Toadfield** [comment]
ok
