### ISSUE TITLE
Is there any way to install other plugins?

### ISSUE THREAD

**Issue by Toadfield** [loganmc10/m64p#71]
I don't like this version of GlideN64,it doesn't have all the features I want for some reason,so I removed the glideN64 Plugin that came by the emulator because there would be problems if I install another version of GlideN64 version,said an error when I tried to do that.
But if I try to start M64P with another GlideN64 Plugin,it says that Mupen64Plus.gui is missing,so is there any way to install another GlideN64 Pulgin or any other Plugin?
Btw would I be able to play online with other plugins?
And why is that other GlideN64 version the build in Video Plugin for this emulator in the first place,doesn't it just have less features?

**Comment by loganmc10** [comment]
You may be able to drop in other plugins, but it's not supported. m64p aims for a good out-of-the-box experience for the majority of users. It's not always a perfect fit for power users. There are other options, like Project64 or RetroArch, that support multiple plugins and a variety of setup options.

> Btw would I be able to play online with other plugins?

No, this would cause desyncs

**Comment by Toadfield** [comment]
(sorry for answering late,I forgot about this thread)
> You may be able to drop in other plugins, but it's not supported.

Could you add a gui option to change the plugins?
>m64p aims for a good out-of-the-box experience for the majority of users. It's not always a perfect fit for power users.

What is better about the GlideN64 plugin M64P uses by default instead of the notmal GlideN64?
Cause it would be a better out of the box experience if the graphics plugin would be the normal GlideN64 in my opinion,it just has more options.
>There are other options, like Project64 or RetroArch, that support multiple plugins and a variety of setup options. 

I hate Project64,it has much worse accuracy than Mupen64 and it isn't even available natively for Linux.
The Mupen64Plus next libretro core has better performance than normal Mupen64Plus,but I hate the gui that Retroarch has.
I found a Mupen64Plus gui that looks exactly like Project64,but I can't find it anymore,I will search for it,cause if the cheat menu and plugin selection exists there,then I could try this.
Btw is it possible to implement your netplay code and gui in other emulators?

**Comment by Toadfield** [comment]
> No, this would cause desyncs

Why is that so?
I mean is it a problem of GlideN64 or your network code or something else?
Btw I meant if Netplay works if both user in the server use the same video plugin.

**Comment by loganmc10** [comment]
> Could you add a gui option to change the plugins?

It's possible, but it would go against the design goals of the project.

> I found a Mupen64Plus gui that looks exactly like Project64,but I can't find it anymore,I will search for it,cause if the cheat menu and plugin selection exists there,then I could try this.

You're probably thinking about https://github.com/Rosalie241/RMG

> Btw is it possible to implement your netplay code and gui in other emulators?

Yes, all the code is open source, in fact Mupen64plus FZ (Android) just ported the netplay code to work there, so Android users can play with each other.

> I mean is it a problem of GlideN64 or your network code or something else?
Btw I meant if Netplay works if both user in the server use the same video plugin.

If 2 users played using different video plugins it would cause desyncs. Also if 2 users play with the same video plugin, but different settings, it could cause desyncs. The modified version of GLideN64 included with m64p includes code to sync the video plugin settings when using netplay.
