### ISSUE TITLE
Missing options from GLideN64 plugin settings

### ISSUE THREAD

**Issue by SamRohod** [loganmc10/m64p#72]
Hi
I was trying to use a .hts texture pack for Paper Mario using the "texture enhancement" settings in GLideN64 but the tab seems to be missing. [This is what's missing](https://user-images.githubusercontent.com/31742919/68077961-aaf7cb80-fdcd-11e9-87c8-a6146824dc62.png)
Is there a way to enable it or was it removed from m64p. How/why?
thank you

Side question: What does the PIF rom file do? is it important for emulation accuracy?

**Comment by loganmc10** [comment]
m64p doesn't support texture enhancements or texture packs. If you'd like to use those I'd suggest using Project64

The PIF ROM is basically the BIOS. It is embedded directly in the N64 console. Most N64 emulators implement an HLE version of the PIF ROM. That is to say they've written code to emulate what the PIF/BIOS does.

m64p includes the option to boot using the binary code from the actual ROM. This is usually distributed online as a file called "pifdata.bin". As with cartridge ROMs, it is copyrighted code and not freely available.

I haven't seen any game where it makes a difference, it's mostly just for development/testing/fun.
