### ISSUE TITLE
super easy to use emulator requires code compile and several hundred dev package dependencies 

### ISSUE THREAD

**Issue by cdoublejj** [loganmc10/m64p#76]
So easy my grandma can do it!  Are there not forums? this emulator looks amazing! it's supposedly THE version ot use on linux but, not even a lowly .deb package :(
``~/m64p$ ./build.sh
make: Nothing to be done for 'all'.
make: Nothing to be done for 'all'.
make: Nothing to be done for 'all'.
make: Nothing to be done for 'first'.
make: Nothing to be done for 'all'.
current revision "e6180a8e0766707df29d94b4ad59a039a48b0dd2"
last build revision "e6180a8e0766707df29d94b4ad59a039a48b0dd2"
Project ERROR: Unknown module(s) in QT: `websockets`

i have no business fooling with code or installing an ass tone of dev packages :(

**Comment by cdoublejj** [comment]
sad panda

**Comment by loganmc10** [comment]
No problem, these are the dependancies for Ubuntu:
```sudo apt install qt5-default libqt5websockets5 libsdl2-2.0-0 libsdl2-net-2.0-0 libhidapi-hidraw0 libminizip1 p7zip-full```

You don't need to compile anything, just download the latest release here: https://github.com/loganmc10/m64p/releases

Unzip and execute ```mupen64plus-gui```

**Comment by cdoublejj** [comment]
i read the read me and installed the dependencies but, it still i had to grab multi packages before it would try to compile and give error above.  

thank you for pointing that out, i failed to notice mupen64plu-gui was NOT .so file but, executable/bin
