### ISSUE TITLE
Nuclear Escape button

### ISSUE THREAD

**Issue by renandr** [loganmc10/m64p#78]
Nowadays most of the software use the escape button to leave the full-screen mode. Most users are used to this functionality. It is very frustrating trying to exit full screen mode and end up nuking the game entirely.
I suggest the shortcut to stop the game to be something more specific like ctrl+esc or similar.

**Comment by loganmc10** [comment]
You'll have you file an issue with https://github.com/mupen64plus/mupen64plus-core . These shortcuts are set by the core (upstream mupen64plus).

**Comment by loganmc10** [comment]
Specifically here: https://github.com/mupen64plus/mupen64plus-core/blob/872751df5d7bf3e5e8b50f2c90b7ebaf3fc5b391/src/main/eventloop.c#L541

Is where escape is set as the key to end emulation

**Comment by renandr** [comment]
Nice, thanks and wow that was a quick answer!

**Comment by renandr** [comment]
Wait.. if this is not the official thing, how did I end up here?

**Comment by loganmc10** [comment]
m64p (this project) pulls together a number of projects to make a great emulator. Mupen64plus is its own project.

m64p is: mupen64plus, GlideN64, as well as a custom GUI and input plugin.

I don't control the mupen64plus repository, although I do contribute

**Comment by renandr** [comment]
Ooooh... okay
By the way I had an issue with the controller configuration by the way..
I just started using the emulator and I have this controller I'm using https://www.amazon.de/dp/B01AD478L6/ref=asc_df_B01AD478L6/
And was creating profiles and saw some issues with the configurator.
The first time I used it it all worked fine. I created a new profile just to play F-Zero X :)
I went to play another game and created another profile (just to change the B to my controller's B and change the Z and R, also analog sensibility). But when I clicked on the button to change and the little countdown started, I pressed the button and nothing changed, it didn't work. I started a ROM and the controller worked fine (without the changes).
I tried closing and opening the emulator and the issue was still there, I restarted my (Win10) pc and it worked, but the second time I opened the configurator the problem started again.
I killed the emulator via task manager and managed to make it work again.
Is this something on your own code or also from another repo?

**Comment by loganmc10** [comment]
This is the right place for that issue. I'm surprised that closing the emulator didn't fix it. Although I was aware it didn't work after playing a game.

You can try this build: https://ci.appveyor.com/api/buildjobs/7rcrov4upm2x2rje/artifacts/m64p-win64-30437e4.zip

It's the latest (not yet released) build that should allow the controller configuration to work after launching a game

**Comment by loganmc10** [comment]
Actually that may not be the correct build, I'll post a different link in a bit

**Comment by renandr** [comment]
No hurries. Just wanted to report the issue :)

**Comment by renandr** [comment]
By custom GUI do you mean this: mupen64plus-gui?
Is this your own code or also from somewhere else?

**Comment by loganmc10** [comment]
Correct, I wrote mupen64plus-gui and mupen64plus-input-qt

I've contributed quite a bit to the main mupen64plus repository (for instance the netplay code), but it's maintained/owned by other people

**Comment by renandr** [comment]
I'm a little noob on this but I've worked with qt in the past (without understanding much of it). I'm trying to make it run xD (Instead of playing games...)
Wanna test my skills and see if I can do something (and will probably fail)

**Comment by loganmc10** [comment]
You can try this build to see if the controller config works better: https://ci.appveyor.com/api/buildjobs/dki8rmuj7jxu1tbo/artifacts/m64p-win64-f6da15d.zip

Yeah I'm a big fan of Qt, these are the projects I maintain (GUI, input and audio plugin): https://github.com/m64p They are all written in Qt, if you want to help out or do something with them it would be great.

The netplay server is also written in Qt if you want to take a look at that: https://github.com/m64p/m64p-netplay-server

**Comment by renandr** [comment]
Hey, I gave up on the code thing and went back to playing some Perfect Dark and started to have issues with getting stuck on the aiming with the L+R buttons... after some research I've found this.

https://answers.microsoft.com/en-us/windows/forum/games_windows_10/xbox-controller-z-axis-problem/e9319285-2eb5-403a-a3aa-20c00f5c243d
https://docs.microsoft.com/en-us/windows/win32/xinput/xinput-and-directinput?redirectedfrom=MSDN

Is this something that the input of your code is related to?

**Comment by loganmc10** [comment]
I'm not exactly sure what you mean by stuck. If you have general questions it's probably better to join the discord server: https://discord.gg/B5svWhR where we/others can have discussions

**Comment by renandr** [comment]
ok thanks :)
I think sometimes during gameplay I turned the aim on and couldn't get out of it, because the Z-Axis used by the L+R canceled each other out. I'll play some more tomorrow and see what is happening. And join the discord thing too :)
