### ISSUE TITLE
No sound at all

### ISSUE THREAD

**Issue by lucarreguy** [loganmc10/m64p#82]
![image](https://user-images.githubusercontent.com/64933181/97627316-f907d500-1a09-11eb-8657-1943a8ac04c9.png)
![image](https://user-images.githubusercontent.com/64933181/97627398-15a40d00-1a0a-11eb-9d04-cade22cf74aa.png)

Every game I try to launch, there's no sound. My sound drivers are up to date,  it's the latest version of the emulator, and it's not muted.

**Comment by loganmc10** [comment]
A couple questions: What OS is this? Also, after launching a game, can you go to Emulation->View Log, and paste the output here?

**Comment by lucarreguy** [comment]
It's Windows 7.
And here's the log
![image](https://user-images.githubusercontent.com/64933181/97766785-c687d600-1af6-11eb-8cc0-8c6a33cb56df.png)

**Comment by loganmc10** [comment]
I'm going to guess it is because your computer doesn't support floating point audio samples, which is what the audio plugin requires.

Windows 7 is no longer supported, I would suggest upgrading your OS if possible. This would probably solve the issue.
