### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by anpansparking** [loganmc10/m64p#84]
Hello! Thanks for this great emulator :> 

When I try to update, Windows defender reports \AppData\Local\Temp\mupen64plus-gui-DBLvUb\**116dc900-182b-11eb-8926-8e44a25b9281** as Trojan:Win32/Wacatac.DA!ml

Is it a false positive?

Thanks!

**Comment by loganmc10** [comment]
Yes, you can see the source code for the updater here:
https://github.com/m64p/m64p-updater

I suspect some antivirus don't like it because it's an unknown file that is copying files onto your computer. I'll need to think of a solution for this... I'm open to suggestions

**Comment by anpansparking** [comment]
Hello! Sorry for the late reply. I don't really now anything about developing and programming so I can't help you with that, sorry. I tried the updater but same as #83 it's stuck on the extracting release part.

**Comment by loganmc10** [comment]
Ok thanks, can you or @GoodWall533 download https://github.com/m64p/m64p-updater/releases/download/1.0/m64p-updater.exe and run it in PowerShell/CMD like this:

```m64p-updater.exe temp_path```

And let me know if it prints anything out?

**Comment by loganmc10** [comment]
You might need to make a folder named temp_path in the same directory as m64p-updater.exe first

**Comment by GoodWall533** [comment]
I did it both on PS and CMD and they did the same thing. Still stuck on the extracting part.

**Comment by loganmc10** [comment]
@GoodWall533 but was anything printed to the console?

**Comment by GoodWall533** [comment]
No. nothing.

**Comment by loganmc10** [comment]
@anpansparking can you give it a try and let me know if anything prints to the CMD/PowerShell window?

**Comment by loganmc10** [comment]
@GoodWall533 @anpansparking another question. Are there any spaces in the path leading to the emulator? (For instance "C:\Users\My Name\Desktop").

**Comment by GoodWall533** [comment]
@loganmc10 no. did it again just to make sure but still does the same thing.

**Comment by loganmc10** [comment]
I can't reproduce this, I tried on 2 different Windows machines. @GoodWall533 is it possible there are any special/non-English characters in the path leading to the emulator?

**Comment by GoodWall533** [comment]
There weren't any special characters in the path but there were non-english ones. Brazillian Portuguese actually.

**Comment by loganmc10** [comment]
Ok, in the latest release (Nov 1) I included an update to wrap the path in quotes, which should help with spaces and other types of "non-standard" characters. You'll have to manually update to the Nov 1 release, and then the next time an update comes out, test from there.

To confirm this is the issue, you could try putting the emulator in a path with only English characters and no spaces (like C:/Temp or something), and try running the update from there.

**Comment by GoodWall533** [comment]
Ok. Will do.

**Comment by Kiiro-Yakumo** [comment]
If I may~
Downloaded the file and checked with the VirusTotal
https://www.virustotal.com/gui/file/bdbd88690d8cf932a8ef4b4334a2fe4650ebd4ecca1a5c09d6b349ebf463b949/detection
Only some three obscure antiviruses see it as a virus. That's a false positive in my book.

**Comment by loganmc10** [comment]
Yes I believe I got the virus issue sorted out, it was because it was built with PyInstaller, and someone previously made some virus using PyInstaller. Anyway there was a way to compile it using PyInstaller so it would no longer match the signature of that virus

**Comment by GoodWall533** [comment]
Also, a update on the updater: I finally updated, everything now works fine. Thanks for the fix.
