### ISSUE TITLE
Crashes when turning off LLE

### ISSUE THREAD

**Issue by msstter** [loganmc10/m64p#88]
I'm pretty new to emulating stuff and using github, so my apologizes if anything here is extremely stupid or not explained correctly. 

M64p crashes for me when I turn off LLE for the default downloaded version. Messed around turning things on/off in video settings for a while, but nothing seemed to make it not crash with LLE off. I left all the Default Paths and Plugins to their default locations as I'm not sure where I should link everything, so maybe that's the issue?

I also used Brew to download the additional dependencies from the Readme file, however when I run:

```
ln -s /usr/local/Cellar/qt/5.15.1/plugins /usr/local/plugins
ln -s /usr/local/Cellar/qt/5.15.1/mkspecs /usr/local/mkspecs
ln -s /usr/local/Cellar/qt/5.15.1/qmake /usr/local/bin/qmake

___
Building:

git clone https://github.com/loganmc10/m64p.git
cd m64p
./build.sh
```
I then get this:
```
bquote> 
```

...and I'm not what that means. Any and all help is appreciated!

Using Macbook Pro 16 with Catalina 10.15.7

**Comment by loganmc10** [comment]
Did you try the .dmg from the releases page? You shouldn't need to compile it

**Comment by msstter** [comment]
Thanks for the response, and sorry I was just being dumb and I figured it out. When I disabled LLE, I guess I never tried turning off MSAA, which is the thing that crashes the program for me. It also seems that Enabling threaded video crashes the program for me too, but it looks like everything is working great now! I've only tried out one game so far, but I'll keep an eye out for any more crashes or bugs I run into. Thanks so much for the hard work in making this thing!

**Comment by loganmc10** [comment]
No worries. Yes unfortunately threaded video is not supported on Mac. OS X does not allow OpenGL rendering outside the main thread

**Comment by msstter** [comment]
No problem! I'm just happy this exists 😄 

But another little issue - I'm using a keyboard as a controller, and when I remapped the 'B' button to the '[' key, the game doesn't seem to register it, although most of the other keys seem to work no problem. I'm happy just using something else, but I found that to be a bit weird. Also, I know it's not a bug/issue so sorry for asking it here, but is there a way to edit the Toggle Speed Limiter and set it to a shortcut?

**Comment by loganmc10** [comment]
Yeah mupen64plus has some built-in shortcuts (you can see them here: https://mupen64plus.org/wiki/index.php/KeyboardSetup). '[' is Decrease Volume. Unfortunately I don't have a way in the GUI right now to remap those shortcuts, so those keys are off limits for controller bindings.

There is no toggle speed limiter shortcut, but holding "F" should fast forward (up to 250% speed)
