### ISSUE TITLE
Flatpak Support

### ISSUE THREAD

**Issue by gal20** [loganmc10/m64p#89]
Hi Logan, would you be interested in distributing m64p as a flatpak application?
If you are unfamiliar with it, Flatpak is a framework for distributing universal Linux applications in a sandboxed environment. It allows Linux users to easily download applications and receive updates for them.
You can submit an app to their central repository at [flathub.org](https://flathub.org), by creating a new pull request to [flathub/flathub](https://github.com/flathub/flathub).
I have some experience writing flatpak manifests, and I can create the manifest and submit m64p to flathub if you are interested.

**Comment by loganmc10** [comment]
Closing as a wontfix
