### ISSUE TITLE
Directory Issue under Linux

### ISSUE THREAD

**Issue by emucosmos** [loganmc10/m64p#9]
when I open m64p under Xubuntu 19.10 and try to configure any options it will show a popup screen saying "Couldn't load core library, please set the path in settings", when checking the paths under Plugin and Path Selection the paths are correct and pointing to the right files, is there any library I'm missing? any tips to make this run properly?
![Captura de pantalla_2020-03-12_13-21-42](https://user-images.githubusercontent.com/62116832/76559249-70c9c500-6464-11ea-8765-75c40d153954.png)

**Comment by loganmc10** [comment]
On Linux sometimes this happens when the core library couldn't find all the libraries it needed to load

Can you do a ```ldd libmupen64plus.so.2```?

**Comment by emucosmos** [comment]
this is what it shows me:
linux-vdso.so.1 (0x00007ffe441fa000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa78eb9a000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa78eb7e000)
	libminizip.so.1 => not found
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fa78eb46000)
	libSDL2-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007fa78e9f1000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fa78e936000)
	libGL.so.1 => /lib/x86_64-linux-gnu/libGL.so.1 (0x00007fa78e8a0000)
	libGLU.so.1 => /lib/x86_64-linux-gnu/libGLU.so.1 (0x00007fa78e82e000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa78e640000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa78e4f1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa78e300000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa793e95000)
	libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007fa78e201000)
	libpulse.so.0 => /lib/x86_64-linux-gnu/libpulse.so.0 (0x00007fa78e1aa000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa78e06c000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fa78e057000)
	libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007fa78e04a000)
	libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007fa78e045000)
	libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007fa78e033000)
	libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007fa78e024000)
	libXss.so.1 => /lib/x86_64-linux-gnu/libXss.so.1 (0x00007fa78e01f000)
	libXxf86vm.so.1 => /lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fa78e018000)
	libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007fa78e013000)
	libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007fa78e002000)
	libwayland-cursor.so.0 => /lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007fa78dff9000)
	libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007fa78dfb6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa78df93000)
	libGLX.so.0 => /lib/x86_64-linux-gnu/libGLX.so.0 (0x00007fa78df5f000)
	libGLdispatch.so.0 => /lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007fa78dea2000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa78de88000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa78de7b000)
	libpulsecommon-13.0.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.0.so (0x00007fa78ddfb000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fa78ddac000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa78dd83000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fa78db79000)
	libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fa78d971000)
	libffi.so.6 => /lib/x86_64-linux-gnu/libffi.so.6 (0x00007fa78d967000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fa78d8bf000)
	libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007fa78d8b3000)
	libsndfile.so.1 => /lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007fa78d837000)
	libasyncns.so.0 => /lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007fa78d62f000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa78d629000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa78d621000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fa78d5fa000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fa78d5da000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fa78d4ba000)
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007fa78d49d000)
	libFLAC.so.8 => /lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007fa78d45e000)
	libogg.so.0 => /lib/x86_64-linux-gnu/libogg.so.0 (0x00007fa78d451000)
	libvorbis.so.0 => /lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007fa78d424000)
	libvorbisenc.so.2 => /lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007fa78d379000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa78d35c000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fa78d342000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fa78d31f000)

**Comment by emucosmos** [comment]
OK, so I answered my own issue here, I was missing libminizip1, as simple as apt installing it and there we go, now it's working perfectly fine, thanks for the ldd tip
