### ISSUE TITLE
Parallel RSP don't seem to work on standalone Mupen64Plus, m64p exclusive only?

### ISSUE THREAD

**Issue by Sancti2020** [loganmc10/m64p#90]
Hi

I'm trying to use the mupen64plus-rsp-parallel.dll with the standalone command line version of Mupen64Plus but from my testing and findings it seems that it's not compatible and is only working with m64p properly.

The error message in the picture below states that the "specified module could not be found" but it clearly shows that it's there in the folder and added to the mupen64plus.cfg like the rest of the plugins.

![Parallel_rsp](https://user-images.githubusercontent.com/74352723/99247157-d695fa00-2806-11eb-9334-a62ddb3ea294.png)

It seems to me that the error in reality would be something else, like "The specified module is not supported"

Is there something that I have missed or is Parallel RSP m64p exclusive?

**Comment by loganmc10** [comment]
Not related to m64p

**Comment by Sancti2020** [comment]
Not related to m64p?

m64p is a front end for Mupen64Plus and you are the one who brought Parallel RSP to m64p which again is a front end to Mupen64Plus. 

Parallel RSP should in theory work in the stand alone command line version of Mupen64Plus but don't and even the dll file name have mupen in it. 

You could at least give me a more detailed answer then not related to m64p.

I have straight up giving up hope in humanity and being civilized. 

I'm sorry that I thought that you who made Parallel RSP possible and have knowledge about Mupen64Plus could answer my question, clearly I was very wrong.

**Comment by loganmc10** [comment]
m64p is not a frontend. m64p is a bundle of software that I distribute. I don't test the individual DLLs with other mupen64plus frontends. I don't offer support for anything other than what I distribute on this page (which is the entire m64p package used as a whole, not picked apart into pieces).

If you want my best guess, it would be that you are using a 32-bit version of standalone mupen64plus, whereas the Parallel RSP DLL is 64 bit. Also, the Parallel RSP DLL is compiled using MinGW, meaning you can't just grab the "mupen64plus-rsp-parallel.dll" file and drop it anywhere you like, it depends on the other DLLs that are distributed with m64p.

**Comment by Sancti2020** [comment]
Now that's the answer I wanted and it was perfect, thank you very much.
I know it's not x86 or x64 related since I only use x64 but the last thing you wrote made perfect sense and that's probably why it won't work.

Thank you again, now I understand better!

**Comment by Sancti2020** [comment]
@loganmc10 ITWORKS!!!!

I just copied the dlls from m64p to the standalone Mupen64Plus folder and it works perfectly.

**Comment by Sancti2020** [comment]
Thank you thank you thank you.
Again it's all because you answered my question so good.

**Comment by Jj0YzL5nvJ** [comment]
Strictly speaking, you only need `msvcrt.dll`, `libgcc_s_seh-1.dll`, `libstdc++-6.dll` and `libwinpthread-1.dll` as far as this _MSYS2_ `mupen64plus-rsp-parallel.dll` is concerned.

_MSVC_ msvcrt.dll is part of [Microsoft Visual C++ Redistributables](https://support.microsoft.com/kb/2977003), irrelevant to casuals in the Win10 world.

**Comment by Sancti2020** [comment]
Even better, thanks a ton!
