### ISSUE TITLE
PS4 Controller Binding isn't working as expected

### ISSUE THREAD

**Issue by danielharvey** [loganmc10/m64p#92]
I am using a PS4 Controller with the latest version of m64p (Nov 1st) and when I bind the "Right Trigger" to the right trigger of the PS4 Controller I get some weird behavior when holding down the button (example scenario, Mario Kart 64, Right Trigger is the power slide, you need to hold that button down).  I ultimately need to bind the "Right Trigger" to the right bumper of the PS4 Controller in order to play.  Can you please take a look and fix?  Thanks.  I have attached an image with my config.

![WeirdBehavior](https://user-images.githubusercontent.com/7558277/99450757-31a31c00-28ef-11eb-9c72-11cc28aebd43.JPG)

**Comment by loganmc10** [comment]
Can you please define what you mean by "weird behavior"?

**Comment by danielharvey** [comment]
When I click and hold down the Right Trigger with the above configuration it doesn't perform a power slide in the example of Mario Kart.  It only happens when I click and release the Right Trigger and there is no way to cancel the action since I already released the button.  This is the weird behavior I am referring to.

The expected behavior is that when I click and hold down the Right Trigger it should perform a power slide until I release the button.  I can get that behavior when I bind the Right Trigger to the PS4's Right Bumper instead.  Working fine on the Xbox Controllers.

**Comment by zenon49** [comment]
Hey there. I wanted to test the emulator but I have also problems with my dualshock specific with this emulator.
I use DS4Windows to map to a 360 layout. When I am in the settings for controller button mapping I can map the N64 controls by pressing the buttons on my dualshock, it register something in the emulator. Just 
![2021-01-15 07_09_58-PS4 Controller Binding isn't working as expected · Issue #92 · loganmc10_m64p](https://user-images.githubusercontent.com/6626688/104688114-c31ce780-5700-11eb-949f-0f3864bfc318.png)
![2021-01-15 07_09_58-PS4 Controller Binding isn't working as expected · Issue #92 · loganmc10_m64p](https://user-
images.githubusercontent.com/6626688/104688370-e9428780-5700-11eb-8ee2-2987eceb7cb1.png)

**Comment by loganmc10** [comment]
Closing in favour of https://github.com/loganmc10/m64p/issues/122
