### ISSUE TITLE
New versions of the GlideN64 plugin do not access the settings menu.

### ISSUE THREAD

**Issue by vanderleivieirainacio** [loganmc10/m64p#93]
The emulator does not access new versions of the video plugins through the settings menu. I download a new plugin from the official website of the GlideN64 plugin from the Appveyor website, put it in the emulator folder but when I try to access the plugin options they don't work. I tried all the ways and it didn't work.

**Comment by loganmc10** [comment]
Yes this doesn't work, you have to use the version included with m64p. However there is no newer version anyway, m64p includes the very latest version of GlideN64

**Comment by vanderleivieirainacio** [comment]
I'm sorry to say but it doesn't include the latest version. I tested it
here and the version of the GlideN plugin that comes with the emulator
still contains bugs in the game Mortal kombat 4, something that the new
plugin straight from the page on GlideN's Appveyor website doesn't have. Why
not improve the emulator so that the user can update the plugin and change
the settings manually as in Project64?

Em qui., 19 de nov. de 2020 às 01:00, Logan <notifications@github.com>
escreveu:

**Comment by loganmc10** [comment]
If you post a more detailed description of the issues you're seeing in MK4 (with screenshots) I can look into it

**Comment by Jj0YzL5nvJ** [comment]
- `m64p` uses [its own fork of `GLideN64` with UX code enchantments](https://github.com/loganmc10/GLideN64/tree/NUI) for the "frontend", so `m64p` is no longer a frontend and the `GLideN64` within it's no longer a plugin, it's a module. It's a independent emulator (OOTB), similar to `BizHawk`, `OpenEmu`, `RetroArch`, etc. but focused only on N64.
- The `mupen64plus` plugins provided by `gonetz/GLideN64` in Appveyor are CLI-exclusive (`mupen64plus-ui-console`) or GUI's "embedded" to it (m64py, etc.) and are incompatible with `m64p`, [`RMG`](https://github.com/Rosalie241/RMG), `BizHawk`, etc.
- The issue with MK4 can be a bug and should be treated as such.
- You really can't compare a **_single-platform / "almost exclusive" x86 architecture_** emulator to a **_cross-platform / multi-subsystem / multi-arch_** emulator. `Project64`'s strength is its stupid simplicity and also its greatest weakness.
