### ISSUE TITLE
[Fedora 33] QT, QDialog, QString not found

### ISSUE THREAD

**Issue by Kiiro-Yakumo** [loganmc10/m64p#94]
Hello~

I have tried everything I could come up with for the moment and still no dice so it's time to ask I guess.
When compilling from the source (git cloned few minutes ago) it claims to not being able to find:
`fatal error: Qt`
`fatal error: QDialog`
`fatal error: QString`
I have executed the recommended dependency installation (everything was already there).
Unless for some reason it's searching for 32-bit libs then I have no idea what can be wrong in there.

Thank you for advance and have a good day~

Kiiro Yakumo

**Comment by loganmc10** [comment]
Can you post the full output of the error? And just to double check, you're building by executing the ```build.sh``` script?

In the meantime though, you should be able to download the binary release from https://github.com/loganmc10/m64p/releases and play using that

**Comment by Kiiro-Yakumo** [comment]
Of course.
Had to translate some messages to english but should be intact and fully english now:
`In file included from /home/user/m64p/mupen64plus-input-qt/qt2sdl2.cpp:1:
/home/user/m64p/mupen64plus-input-qt/qt2sdl2.h:4:10: fatal error: Qt: There is no such file or directory
    4 | #include <Qt>
      |          ^~~~
compilation terminated.
In file included from /home/user/m64p/mupen64plus-input-qt/configdialog.cpp:1:
/home/user/m64p/mupen64plus-input-qt/configdialog.h:7:10: fatal error: QDialog: There is no such file or directory
    7 | #include <QDialog>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:158: qt2sdl2.o] Error 1
make: *** Waiting for incomplete tasks ...
In file included from /home/user/m64p/mupen64plus-input-qt/moc_configdialog.cpp:11:
/home/user/m64p/mupen64plus-input-qt/configdialog.h:7:10: fatal error: QDialog: There is no such file or directory
    7 | #include <QDialog>
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:155: configdialog.o] Error 1
make: *** [Makefile:169: moc_configdialog.o] Error 1
In file included from /home/user/m64p/mupen64plus-input-qt/main.cpp:28:
/home/user/m64p/mupen64plus-input-qt/main.h:4:10: fatal error: QString: There is no such file or directory
    4 | #include <QString>
      |          ^~~~~~~~~
compilation terminated.`

Ironically the release package runs just fine (and works great!)

**Comment by loganmc10** [comment]
oh ok I understand the problem, the dependencies listed on the main page of this repository are what is required to run the binary package.

I didn't list the packages required to compile, every Linux distro names packages differently. 

I'm guessing most of these errors would go away by doing ```dnf install qt5-qtwebsockets-devel```, although you might run into further requirements

**Comment by Kiiro-Yakumo** [comment]
No luck.
I have installed
`libwebsockets libwebsockets-devel python3-websockets qt5-qtwebsockets qt5-qtwebsockets-devel`
Still the same error.
Also these qt5 devel-like packages among others installed:
`qt5-qtbase-devel qt5-qtwebengine-devel qt5-qtwebkit-devel`
to name few of probably most importance (the full list would be somewhat long)

**Comment by loganmc10** [comment]
No sorry i'm not sure

**Comment by Jj0YzL5nvJ** [comment]
> Would that be possible to somehow force the code or whatever you use for building (MAKE probably?) to search only for qt5?

export QT_SELECT=5

**Comment by loganmc10** [comment]
It's also possible that you could try replacing instances of ```qmake``` in build.sh with ```qmake-qt5``` to force it to use QT5

Lines like this:
https://github.com/loganmc10/m64p/blob/master/build.sh#L41

**Comment by Kiiro-Yakumo** [comment]
Mmm confirming~ changing to qmake-qt5 makes it compiles successfully :)
From what I recall not every Linux distro goes with "qmake-qt5" so would it be possible to somehow add it in the build.sh in a way like... mmm... "Check if qmake-qt5 exists" -> "if yes continue with it" / "if no then go with qmake" ?
Also :+1: for adding -j4 to make it go faster :) (I'm increasing it on my end but -j4 is pretty universal these days so no objections to this part)

**Comment by Jj0YzL5nvJ** [comment]
> It's also possible that you could try replacing instances of `qmake` in build.sh with `qmake-qt5` to force it to use QT5

That is a bad idea if you have multiple versions of QT and the build project requires `moc`.
```
$ export QT_SELECT=4
$ qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
$ moc -v
Qt Meta Object Compiler version 63 (Qt 4.8.7)
$ export QT_SELECT=5
$ qmake --version
QMake version 3.0
Using Qt version 5.6.1 in /usr/lib/x86_64-linux-gnu
$ moc --version
moc 5.6.1
```

Example: [qBittorrent](https://github.com/qbittorrent/qBittorrent)

**Comment by Kiiro-Yakumo** [comment]
Fedora is such an example, we have qmake-qt4 and qmake-qt5 from what I recall... and qt3 to some extend :stuck_out_tongue:

**Comment by Jj0YzL5nvJ** [comment]
Xubuntu 16.04.7 LTS:
```
$ ls -la /usr/bin/qmake*
lrwxrwxrwx 1 root root  9 may 23  2016 /usr/bin/qmake -> qtchooser
lrwxrwxrwx 1 root root 37 jun  2  2016 /usr/bin/qmake-qt4 -> ../lib/x86_64-linux-gnu/qt4/bin/qmake
$ ls -la /usr/bin/moc*
lrwxrwxrwx 1 root root      9 may 23  2016 /usr/bin/moc -> qtchooser
lrwxrwxrwx 1 root root     35 jun  2  2016 /usr/bin/moc-qt4 -> ../lib/x86_64-linux-gnu/qt4/bin/moc
$ ls -la /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
-rwxr-xr-x 1 root root 3558984 jun  2  2016 /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
$ ls -la /usr/lib/x86_64-linux-gnu/qt4/bin/moc
-rwxr-xr-x 1 root root 1224200 jun  2  2016 /usr/lib/x86_64-linux-gnu/qt4/bin/moc
$ ls -la /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
-rwxr-xr-x 1 root root 3099816 dic 22  2016 /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
$ ls -la /usr/lib/x86_64-linux-gnu/qt5/bin/moc
-rwxr-xr-x 1 root root 1137712 dic 22  2016 /usr/lib/x86_64-linux-gnu/qt5/bin/moc
```
