### ISSUE TITLE
Auto-update stalls at "Extracting release"

### ISSUE THREAD

**Issue by jsarich** [loganmc10/m64p#96]
Auto-updater stalls at Extracting release.  I am running Windows 10, on mupen64plus-gui build Nov 16, 2020.  I confirmed there are NO windows defender log entries for this.  I don't have any other anti-virus installed, so I don't think that is the problem here.  

Is there a command line variable to disable checking for update?  I would rather not be asked every time the program starts whether or not I want to update.

**Comment by loganmc10** [comment]
I made some changes to the auto updater. When you get a chance can you try it again and let me know if it still gets stuck at the same spot?

**Comment by loganmc10** [comment]
Closing as stale, please reopen if it's still an issue
