### ISSUE TITLE
Discord Game Activity undetected

### ISSUE THREAD

**Issue by adityasundar15** [loganmc10/m64p#97]
It is a small bug but I just wanted to inform you that discord does not recognize the m64 emulator running. So if I add it manually the question mark logo appears and it just looks weird.

**Comment by loganmc10** [comment]
I reached out to Discord about this. They told me that basically it's supposed to happen automatically after some time, but usually doesn't happen for games with less than like 10,000 users. There is unfortunately nothing I can do besides wait and hope that one day it'll start working

**Comment by loganmc10** [comment]
Closing this as there is nothing I can do to fix this
