### ISSUE TITLE
Version Nov302020 Doesn't Launch on macOS Big Sur

### ISSUE THREAD

**Issue by jerrypc2036** [loganmc10/m64p#99]
While launching m64p osx version Nov302020,
a pop-up message "Failed to load core library" displayed and the program end by itself.
This issue doesn't happen in previous Nov182020 build.

**Comment by joeldenning** [comment]
I see this, too. Here is the full error message: https://gist.github.com/joeldenning/3ec3c12e2e4179e522f3e9a6bc595f86

**Comment by joeldenning** [comment]
Note that I am still able to develop m64p on Big Sur, although I had to do some manual symlinking to trick it into using the latest version of xcode to do so. So It definitely does run on Big Sur, if properly linked. I will investigate it further.

**Comment by joeldenning** [comment]
@jerrypc2036 can you confirm if the following DMG works for you? I built it locally on Big Sur. My theory is that it's related to the environment that the DMG is built on - Travis CI is still building on Catalina (see https://docs.travis-ci.com/user/reference/osx/#macos-version).

[Big Sur Build](https://drive.google.com/file/d/1OLhwU4O2l7cb00PbwUL2N5aFAYV5ktqb/view?usp=sharing)

**Comment by jerrypc2036** [comment]
@joeldenning Yes, this build worked well. No more error message while launching!

**Comment by joeldenning** [comment]
@jerrypc2036 does Audio work for you? A friend I had test this build said that audio didn't work for him.

**Comment by joeldenning** [comment]
Also, could you test whether the DMG at https://github.com/loganmc10/m64p/actions/runs/411158075 works for you? That dmg works for me on Big Sur - I think that @loganmc10 fixed this issue by switching from Travis to Github actions.

**Comment by jerrypc2036** [comment]
Sorry for late reply.
Both the builds worked for me and both has working audio.
I tried both HLE video and LLE video, two modes were also working fine.

**Comment by Jj0YzL5nvJ** [comment]
mupen64plus/mupen64plus-core#805
